### ISSUE TITLE
[dependency parsing] Zebra does not properly handle all relationship fields listed in the control file of a package.

### ISSUE THREAD

**Issue by mwoolweaver** [zbrateam/Zebra#1083]
**Describe the bug**

If you use the `Provides:` field in a package Zebra does not handle it properly all the time.

**To Reproduce**

I have created a repo that will help demonstrate the issue, [mwoolweaver/essential4all](https://github.com/mwoolweaver/essential4all), it's hosted on github for convenience. Not sure how to link to the repo for Zebra to be able to add it natively (maybe that's for another issue?) but the readme has instructions on how to add also the URL is in the traditional APT format.

`https://mwoolweaver.github.io/essential4all/ ios main`

1.  In that repo you will find a package named `noCydia` (it's [control file](https://github.com/mwoolweaver/essential4all/blob/master/raw/noCydia/DEBIAN/control) relevant for it's dependencies).

	If you install this package and then try to uninstall `Cydia` you will notice that Zebra tries to uninstall the Essential package and Cydia Translations. And if you allow Zebra to uninstall these 2 packages (it should not uninstall either per the control file I linked to). Now try to install either the Essential package or Cydia Translations, they will succeed w/o Zebra queuing up `Cydia` as it should since `noCydia` has `Provides: cydia` in its [control file](https://github.com/mwoolweaver/essential4all/blob/3338a0c0509235039a8f7f57a28d179c45cabdd5/raw/noCydia/DEBIAN/control#L10). 

2.  In that same repo you will also find a named `essential w/o Cydia` (it's [control file](https://github.com/mwoolweaver/essential4all/blob/master/raw/essential/DEBIAN/control) relevant for it's dependencies). 

    This package is meant to provide a replacement for the `essential` package found on https://apt.bingner.com w/o using the same packageID but instead by using the `Provides:` field in the control file. Zebra ignores this and still shows an update for the `essential` package provided by bingner. [relevant line](https://github.com/mwoolweaver/essential4all/blob/3338a0c0509235039a8f7f57a28d179c45cabdd5/raw/essential/DEBIAN/control#L10)

**Expected behavior**

Zebra should properly handle all relationship fields listed in the control file of a package.

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1-beta5
 - Device Type [e.g. iPhone or iPad]: iPhone 8 Plus
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Additional context**

**Debian Policy Manual**

1. [Declaring relationships between packages](https://www.debian.org/doc/debian-policy/ch-relationships.html)

	> The relations allowed are <<, <=, =, >= and >> for strictly earlier, earlier or equal, exactly equal, later or equal and strictly later, respectively. The exception is the Provides field, for which only = is allowed.
    
    I only use an `=` and it appears as `Provides: essential (= 0-2)` as that's the current version. I have tried using higher version such as `Provides: essential (= 0-3)` but Zebra ignores that as well.

2. [Virtual packages - Provides](https://www.debian.org/doc/debian-policy/ch-relationships.html#virtual-packages-provides)

   > As well as the names of actual (“concrete”) packages, the package relationship fields `Depends`, `Recommends`, `Suggests`, `Enhances`, `Pre-Depends`, `Breaks`, and `Conflicts` may mention “virtual packages”. 
   
   > A virtual package is one which appears in the Provides control field of another package. The effect is as if the package(s) which provide a particular virtual package name had been listed by name everywhere the virtual package name appears. 
     
     this means it's as if the package is installed if mentioned as a `Provides:`??

3. [5.6.9. Essential](https://www.debian.org/doc/debian-policy/ch-controlfields.html#essential)  

   > If set to yes then the package management system will refuse to remove the package (**upgrading and replacing** it is still possible).

   Since an Essential package can be replaced the Essential tag shouldn't be the issue here.

**Comment by wstyres** [comment]
I'll take a look at this but this might require some larger fixes to be put in place.

Why is this "essential" package necessary?

Also, the second point of your issue about the upgrade still showing is because the package is marked as "Essential or Required" this is mimicking Cydia's behavior to show upgrades for packages that are not installed that are essential/required. The upgrade will continue to show unless Bingner's repo is removed.

**Comment by mwoolweaver** [comment]
> I'll take a look at this but this might require some larger fixes to be put in place.

Thank you and if you need any assistance in nailing this down let me know I'd be glad to help.

> Why is this "essential" package necessary?

it's dependencies are:

`Pre-Depends: bootstrap | dpkg (>= 1.13.25-5)
Depends: cydia | com.ripdev.icy, cy+model.iphone (<< 11.0) | cy+model.ipad (<< 11.0) | cy+model.ipod | science.xnu.substituted, cy+model.iphone (<< 11.0) | cy+model.ipad (<< 11.0) | cy+model.ipod | com.ex.substitute`

So it basically forces a user to have Cydia installed even if (like me) they don't want or need it. So when a user uninstalls Cydia this package will forever show an update and as mentioned in #1029 Zebra also refuses to "ignore updates" for this package.([new comment w/ video](https://github.com/wstyres/Zebra/issues/1029#issuecomment-614196808))


> Also, the second point of your issue about the upgrade still showing is because the package is marked as "Essential or Required" this is mimicking Cydia's behavior to show upgrades for packages that are not installed that are essential/required. The upgrade will continue to show unless Bingner's repo is removed.

But if I have a package installed that provides that package it shouldn't show an update for it. If `package A` Provides: `package B` then `package B` isn't needed ever for anything. That's how APT works anyways..

**Comment by wstyres** [comment]
Was more referring to the question of why you have created this new essential package, not what the current one is used for. 

Yeah the update thing seems to be a lapse in logic, I think the current logic is to display an update if the package isn't installed, doesn't check for provides or ignoring updates. I'll look into that as well eventually.

**Comment by mwoolweaver** [comment]
> Was more referring to the question of why you have created this new essential package, not what the current one is used for.

So I don't have to be forced to have Cydia installed? Otherwise you are forced to either install it or dodge updates for it as I mentioned [here](https://github.com/wstyres/Zebra/issues/1029#issuecomment-614196808). 

Also, mine doesn't replace Bingner's by default because it has a different packageID but it should make the updates not show anymore when mine is installed because it does Provide it.


> Yeah the update thing seems to be a lapse in logic, I think the current logic is to display an update if the package isn't installed, doesn't check for provides or ignoring updates. I'll look into that as well eventually.

Let me know if I can be of any help.

**Comment by mwoolweaver** [comment]
@wstyres Could I suggest a partial fix for the essential Package from Bingner's repo? 

The first would be to add a `Provides: cydia` which would fix the want for Zebra to update it all the time when Cydia is absent.


The second would depend on whether Zebra validates the GPG signatures of repos but that would be to include a few things from `/etc/apt/` but to do that you'd have to include `Replaces: cydia` in Zebra's control file so APT doesn't complain about overwriting files from another package. 

`/etc/apt/trusted.gpg.d/` - contains GPG signatures of the default repos (are included with Cydia)

**Comment by absidue** [comment]
Adding `Replaces: cydia` to Zebra's control file seems like a bad idea. From what I understand it would break Cydia updates for everyone who wants them, unless you do the replace with a specific version.

**Comment by mwoolweaver** [comment]
> Adding Replaces: cydia to Zebra's control file seems like a bad idea.

That’s only needed if 

> Zebra validates the GPG signatures of repos 

But I read a comment on a different issue where @wstyres said that Zebra doesn’t fetch a Release/InRelease file so those files might not be required?

**Comment by absidue** [comment]
Release files are not mandatory, but they get downloaded to `/var/mobile/Library/Application Support/xyz.willy.Zebra/lists` if  a repo does have it. I haven't looked in to it enough to tell you whether Zebra does anything important with it.

**Comment by mwoolweaver** [comment]
> I haven't looked in to it enough to tell you whether Zebra does anything important with them.

If Zebra only grabs Release and not InRlease then the GPG signatures in `/etc/apt/trusted.gpg.d` would not be needed as the InRelease file is the only one signed with GPG.

signed with GPG
https://apt.bingner.com/dists/ios/1443.00/InRelease


Not signed
https://apt.bingner.com/dists/ios/1443.00/Release

**Comment by mwoolweaver** [comment]
This issue can also been seen when using @ArtikusHG’s [PreferenceLoader](https://github.com/ArtikusHG/PreferenceLoader)

**Comment by wstyres** [comment]
Resolved in 2.0 alpha.
