### ISSUE TITLE
Seperator cells issue

### ISSUE THREAD

**Issue by qasim311** [zbrateam/Zebra#1154]
**Describe the bug**
In adaptive dark mode, sometimes the seperator lines are different widths or colors

**To Reproduce**
Use system tint, refresh sources after re opening the zebra app after it has been idle some time on dark mode. 

**Expected behavior**
The first screenshot should look like the second

**Screenshots**
![31F92849-5075-4051-A5AA-26294E0DDA1B](https://user-images.githubusercontent.com/57723688/80335079-13b58300-8808-11ea-8790-227d3482d352.png)
![0D2A5B96-1653-4DDF-A298-DB45CAA92AC0](https://user-images.githubusercontent.com/57723688/80335085-1912cd80-8808-11ea-8942-badb937abfdc.png)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.4.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1~beta7 (latest beta)
 - Device Type [e.g. iPhone or iPad]: iPhone X
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Comment by aabosh** [comment]
Hi there, we're planning to redesign this whole view in 1.2, which will fix this bug in the process. Expect to see this resolved in the future! Thanks.

**Comment by PoomSmart** [comment]
See if 1.1.1 fixes this by any chances.

**Comment by qasim311** [comment]
It does not. 

@
![99DCBFCE-38A6-4F96-8DFE-5C3EE4C5FCB0](https://user-images.githubusercontent.com/57723688/81635012-f74b4600-93c4-11ea-98c6-95c5cccf961e.png)

**Comment by wstyres** [comment]
Closing this issue for housekeeping reasons, if the issue persists when the pure-black theme is re-added please open another issue.
