### ISSUE TITLE
Any page opened via context menus has broken dark mode

### ISSUE THREAD

**Issue by worldlydev** [zbrateam/Zebra#1155]
**Describe the bug**

Opening a page via context menus will break the dark mode for that page. This goes for packages accessed from any tab and Reddit posts.

**To Reproduce**

^
Accessing the page though pressing normally will not result in a broken dark mode.

**Expected behavior**

I expect the dark mode to stay dark and not the "watered-down grey" color that comes when haptic-touching.

**Screenshots**

Screen recording:
https://imgur.com/a/VHLqIPd

Dark mode functioning properly to the left and malfunctioning to the right:
![F784AEE8-4544-4A3A-BA8D-55FB6D63AB13](https://user-images.githubusercontent.com/51668635/80358915-667d5200-887d-11ea-81db-b6330d04daf0.jpeg)
![4DFFDE26-5EE3-4119-B71F-4D016A936E44](https://user-images.githubusercontent.com/51668635/80358924-69784280-887d-11ea-9c30-029863854990.jpeg)

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1 beta 7
 - Device Type [e.g. iPhone or iPad]: iPhone 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Uncover

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

N/A

**Additional context**

N/A

**Comment by eve0415** [comment]
I was going to say that :/

**Comment by worldlydev** [comment]
Also adding this here since it is similar. Don't want to open a new issue:

Screenshots:
![33B72BA5-A59A-48AB-9339-6F5F512FC836](https://user-images.githubusercontent.com/51668635/80365596-28d1f680-8888-11ea-9303-948a05610735.png)
![723E58C1-EEBA-47C7-91D8-4416891CACFB](https://user-images.githubusercontent.com/51668635/80365609-2cfe1400-8888-11ea-9c4d-c9b56427ca05.png)

Screen recording:
https://imgur.com/a/HaMCtfx

The same dark mode issue appears when opening a package depiction page with haptic-touching sometimes.

When accessing the depiction page through search or in featured packages the dark mode also becomes "watered-down"

**Comment by SeMoOoR** [comment]
I noticed also selecting a package using the search function causes the same issue with dark mode. In addition, white border are present in the depiction page.
![B2E35932-F9A6-4322-8D63-3C4FA2D747EC](https://user-images.githubusercontent.com/25428973/80386057-8c234f00-88af-11ea-96ac-d0eb6723a627.png)

**Comment by SeMoOoR** [comment]
Since issue #1172 is related and closed. I would ask to take a look at the comment I posted after the mentioned issue got closed. Thanks.

**Comment by wstyres** [comment]
Going to close this issue for now for housekeeping reasons. If the issue persists when context menus are re-added please open another issue.
