### ISSUE TITLE
Issue adding multiple sources

### ISSUE THREAD

**Issue by Greigh** [zbrateam/Zebra#1290]
**Describe the bug**
When trying to add a bunch of sources, it ignores some of them and you have to figure out which ones aren't being added. 

**To Reproduce**
1. Clear all sources.
2. Add a ton of sources. For example, I have 203 in my database [here](https://raw.githubusercontent.com/Greigh/iOS-Jailbreak-Master-Repository/2.4.1.2/General%20Repos).
3. Check to see if ALL of them were added. 

**Expected behavior**
1. Add as many repos as you'd like. 

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1.9
 - Device Type [e.g. iPhone or iPad]: iPhone XS Max
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver 5.0.0

**Comment by wstyres** [comment]
I just imported all of those repos and this is the result. Does a popup like this not pop up? ![Simulator Screen Shot - iPhone 11 Pro - 2020-05-26 at 16 55 47](https://user-images.githubusercontent.com/19736790/82949521-c432b600-9f71-11ea-9739-888bb37d78b4.png)

**Comment by Greigh** [comment]
I just removed my sources and added them again. There was no pop up of any sort. And in fact both those sources in your screenshot worked. 

However when I look at my sources https://ocean.webjungle.ch/ has the Invalid Source error. I went to the webpage right after, it worked, and it worked in Cydia. It has done that a few times with other repos. Even a refresh doesn't update the existence of the repo.

**Comment by wstyres** [comment]
Which repos were not added then? The way the "add multiple" dialog works currently is that it uses a URL detector which means that if any URL is malformed in any way it won't end up attempting to add the URL. I can run your list through the URL detector again and see which text shows up as non-URLs.

As for that repo, I get that error too. It looks like a 510 for some reason? I'll do some more investigating on it.

**Comment by Greigh** [comment]
With such a big of a list, it is hard for me to figure out which ones exactly without time of searching for things to see if they exist or not. This comes back to request #814 :P 

Just a thought, not sure it is legit or not: It may have been related to when the jailbreak first came out and a lot of repos were having high traffic.

**Comment by Greigh** [comment]
Just found one: https://repo.niceios.com/.

**Comment by Greigh** [comment]
Yet another one: https://shiftcmdk.github.io/repo/. And when I add it by itself it adds the repo to my sources, but it doesn't even seem to want to bring anything up for it while Cydia does.

**Comment by wstyres** [comment]
Seems like a random chance issue. I'll see if I can ever reproduce.

**Comment by wstyres** [comment]
Hi! Thanks for your issue report. Unfortunately we do not support the 1.2 beta versions anymore and this issue will be closed. You can either downgrade to the latest stable version (1.1.18) or install the Zebra 2.0 Alpha and see if your issue still persists. If the issue does still persist, please file a new issue.
