### ISSUE TITLE
[1.2] [Low] UI bug switching dark to light

### ISSUE THREAD

**Issue by Greigh** [zbrateam/Zebra#1323]
**Describe the bug**
When switching from dark to light with having Pure Black mode you get a weird UI issue. See screenshots and video

**To Reproduce**
1. Turn on Pure Black and Dark mode or light.
2. Go out and back in or just try to switch right there.

**Expected behavior**
Smooth transition from each pure black, dark, and lights modes. 

**Screenshots**
Video: https://cdn.discordapp.com/attachments/572784833714192395/715408489912205321/video0.mp4
![A5E70D56-45A8-4D52-8645-B7F3CE1C0886](https://user-images.githubusercontent.com/57759540/83096217-23c4ba80-a073-11ea-8f8a-bdbef6585b8f.png)
![D6124739-2DEE-46D4-8373-32C70C6FCB15](https://user-images.githubusercontent.com/57759540/83096224-26271480-a073-11ea-9062-79b9ef506162.png)
**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2~beta1a
 - Device Type [e.g. iPhone or iPad]: XS Max
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: u0 5.0.1

**Comment by gkeep** [comment]
Fixed back in 1.2~beta1b. This issue can be closed.

**Comment by Greigh** [comment]
Done. Thanks @gkeep.
