### ISSUE TITLE
Make package info section more useful

### ISSUE THREAD

**Issue by p0358** [zbrateam/Zebra#1343]
**Is your feature request related to a problem? Please describe.**
From the package info, at the bottom, I see some info that I would like to learn more about, but I can't either view it at all or in convenient way.

**Describe the solution you'd like**
"Source" should open up the source repo on click
"Section" should probably open up said repo under the selected section
"Dependencies", "Conflicts", when clicked they should display the info from these fields, maybe in some new view or an alert, and there replace `,` to newlines to make it more readable

and maybe:
"Bundle Identifier" and perhaps others should be copiable on press and hold (when that small tooltip appears)
"Installed version" could show all available versions at the repo?

The more interactive the better, I believe. But at minimum "Source" and "Dependencies"/"Conflicts" should be clickable. "Source" should have the same arrow as "Author", others don't need to.

**Describe alternatives you've considered**
—

**Additional context**
![obraz](https://user-images.githubusercontent.com/5182588/83293774-855c6480-a1ec-11ea-944f-53502edbcd81.png)

**Comment by wstyres** [comment]
As of a273feb049f8985ac77630c6abb57e4b1984043d:
- Source is selectable in package depictions
- Dependencies and Conflicts now drop down to show them for each package
