### ISSUE TITLE
Allow adding to the wishlist always

### ISSUE THREAD

**Issue by p0358** [zbrateam/Zebra#1344]
**Is your feature request related to a problem? Please describe.**
I want to uninstall a package and save it in the wishlist for later. I treat wishlist as a list of packages that are of interest to me, but I don't want to have them on my device for any reason, mainly.
So for that I now need to remove it, respring and then remember what was the name, find it, and then finally add it.

**Describe the solution you'd like**
When you press the "..." menu on the right, it should always include the wishlist add/remove button, not only if the package is not installed!

**Describe alternatives you've considered**
Doing it manually and having to remember that each time is really not viable...

**Additional context**
I think it was possible to add an installed package to the wishlist before the last big 1.2 beta update landed. Turns out it was a very important detail for me

**Comment by wstyres** [comment]
The wishlist is meant to be a list of packages you have not yet installed so we're not going to allow packages that you've installed on the wishlist. We'll consider adding another feature in order to keep track of more important packages.

**Comment by p0358** [comment]
@wstyres I strongly disagree with that. And I would suggest expanding this option to be just a kind of "bookmarks" for tweaks. Because why not? I think this should just be a list of tweaks, where tweaks can be added onto, and it should be the user's decision what do they add to it.
Like my use-case is that I frequently want to uninstall a tweak and save it somewhere for later, so I have an easy hook to get back to it later when I need it again.

**Comment by p0358** [comment]
If anyone is looking for an ad hoc solution, I've created ZebraWishlistForAll tweak to solve this, available at my repo https://repo.p0358.net/ or GitHub https://github.com/p0358/ZebraWishlistForAll

**Comment by wstyres** [comment]
I've gone back on this and decided to renamed "wishlist" to "favorites" and make it so that every package can be added to your favorites.
