### ISSUE TITLE
White console screen for light mode.

### ISSUE THREAD

**Issue by CanerKaraca23** [zbrateam/Zebra#1347]
iPhone 5S
iOS 12.4.7
Zebra 1.2-beta1a

**Describe the solution you'd like**
White console screen for light mode.

![6EC6D4A0-3CC4-4779-B13B-6B92D3FDCBCF](https://user-images.githubusercontent.com/37447503/83341498-e0758080-a2ec-11ea-8713-c74c141b2a0d.png)

**Comment by wstyres** [comment]
The console is meant to be dark by design, text is not very readable on the console when it is black on white.
