### ISSUE TITLE
Show latest version of tweak installed

### ISSUE THREAD

**Issue by mainhathao** [zbrateam/Zebra#1358]
Hi, the recent UI update to Zebra is amazing and I love how it looks! However, I have some requests that I suggest adding to Zebra.

- [x] It'd be great to add an option to not bring up the versions prompt when I want to install a tweak. I think by tapping on 'Install' it mostly means users want to install the latest versions. IF there are older versions, 'Install' can be replaced with 'Modify,' just like Cydia. At least it should be applied to the swiping actions, swiping actions are used to quickly queue up/remove tweaks so I think the versions prompt is not necessary.

- [ ] I can tell which version of the tweak is installed, however I don't know what the latest version of the tweak is natively by looking at Zebra's new depiction UI. I mean it's possible to find for it in the repo depiction, but that wouldn't be as convenient as before the UI change. For instance, Packix provides a Version section in the depiction, but quickly looking at Zebra, I can't tell what the latest version is, and would have to wait for the depiction to finish loading. Therefore, one more line of texts to indicate the tweak's latest version would be great.

**Comment by eve0415** [comment]
> * It'd be great to add an option to not bring up the versions prompt when I want to install a tweak. I think by tapping on 'Install' it mostly means users want to install the latest versions. IF there are older versions, 'Install' can be replaced with 'Modify,' just like Cydia. At least it should be applied to the swiping actions, swiping actions are used to quickly queue up/remove tweaks so I think the versions prompt is not necessary.

There is a setting to change that `Always Install Latest`

**Comment by mainhathao** [comment]
Oops I totally missed that one. I guess first request is closed then. Thank you!

**Comment by wstyres** [comment]
As of c856aaecaa439d5104c6eec23376224c1df54c38 we show the "Latest Version" in the package information section if applicable.
