### ISSUE TITLE
When installing a deb file, the screen of it doesn’t automatically get dismissed. I have to get it down manually.

### ISSUE THREAD

**Issue by TomerKILLer** [zbrateam/Zebra#1364]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 13.3
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2~beta1b
 - Device Type [e.g. iPhone or iPad]: iPhone X
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Should be fixed in 5b92d290f9d22756ea52026d42d3a0852041c0f3.
