### ISSUE TITLE
"Refresh Sources" 3D touch shortcut

### ISSUE THREAD

**Issue by Aransh** [zbrateam/Zebra#1366]
**Is your feature request related to a problem? Please describe.**
I often open Zebra to check for new packages, sometimes when I know a certain package is supposed to be released, so I would love for a shortcut that will enable me to open the app and immediately refresh sources when needed, even if they were just refreshed a minute ago.

**Describe the solution you'd like**
Add a shortcut when you 3D touch the app icon to open and refresh sources

**Describe alternatives you've considered**
As far as I know the "automatic refresh" toggle won't do anything if the sources were recently updated, having it always refresh is another solution but seems unnecessary.

**Comment by wstyres** [comment]
Automatic refresh toggle refreshes Zebra's sources after 30 minutes when enabled.

**Comment by wstyres** [comment]
Implemented in 45c3b0aab60271db1ef18622a9b28c6a9b9af4ca.
