### ISSUE TITLE
[Bug] List all available version in upgrade from two repos (stable & beta)

### ISSUE THREAD

**Issue by yur1xpp** [zbrateam/Zebra#1371]
**Is your feature request related to a problem? Please describe.**
With both stable and beta repo added in sources, the upgrade list will only shows the one from a single repo, in my case, the beta repo. Sometimes users want to stay on the stable version, but occasionally wanted to upgrade to beta version. For example, Zebra 1.2beta is quite buggy for me, so I decided to stay on 1.1.9. However when 1.1.10 drops, I can't upgrade to that version, but only the 1.2 betas version.

**Describe the solution you'd like**
To list all available upgrade from stable and beta repos.

**Additional context**
https://imgur.com/a/IcpK3aD
The video is taken on 1.1.9 upgrading to 1.1.10. I'm currently on 1.1.10 now (temporary removed beta repo), so I'm not sure 1.1.10 fixed/improved this.

**Comment by wstyres** [comment]
I'm not able to reproduce this anymore, are you able to?

**Comment by wstyres** [comment]
Going to close due to inactivity. Feel free to file another issue if this still occurs on the latest beta.
