### ISSUE TITLE
Ability to filter out sectionless packages

### ISSUE THREAD

**Issue by worldlydev** [zbrateam/Zebra#1381]
**Is your feature request related to a problem? Please describe.**

N/A

**Describe the solution you'd like**

None

**Describe alternatives you've considered**

None

**Additional context**

Would be nice to have the ability to filter out packages without a section like in Cydia:

![E46493AA-13E0-4CF3-B164-1C9B014D360C](https://user-images.githubusercontent.com/51668635/83780208-2768ca80-a68d-11ea-8a46-40f77e58ded4.png)
![C544C783-5896-440E-8B11-FB24A3948E2C](https://user-images.githubusercontent.com/51668635/83780216-2afc5180-a68d-11ea-816b-53a916d87db3.png)

**Comment by wstyres** [comment]
Implemented as of b035b20db6a1d6ccac99a2c1786a870d8d47a075.
