### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by worldlydev** [zbrateam/Zebra#1390]
**Describe the bug**

Zebra crashed while opening a package in the changes tab.

**To Reproduce**

Not sure what caused it but it happend while doing what is written above.

**Expected behavior**

No crash

**Screenshots**

N/A

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2-beta1b
 - Device Type [e.g. iPhone or iPad]: iPhone 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Uncover

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

https://ghostbin.co/paste/vh7hz

**Additional context**

N/A

**Comment by wstyres** [comment]
Can you reproduce the issue? The crash log isn't super helpful

**Comment by worldlydev** [comment]
> Can you reproduce the issue? The crash log isn't super helpful

This just happens at random. I tried just messing around in the changes tab (refreshing sources, adding to installation queue, open depictions, etc) and Zebra crashed again.

https://ghostbin.co/paste/eop4x

**Comment by wstyres** [comment]
The second crash log doesn't even appear to be the same crash

**Comment by worldlydev** [comment]
> The second crash log doesn't even appear to be the same crash

Not sure that it is the same crash. It was random. That's why I added it here. Since I'm not sure what caused it.

**Comment by wstyres** [comment]
If you don't have steps to reproduce then I can't really do anything about it. I would refrain from reporting crashes unless they are reproducible.

**Comment by worldlydev** [comment]
> If you don't have steps to reproduce then I can't really do anything about it. I would refrain from reporting crashes unless they are reproducible.

Give it some time. I may be able to find out what causes them since they happen quite often. If I can't find out within a week I'll close the issue.

**Comment by worldlydev** [comment]
Still have no clue what causes the crashes but they still occur.

**Comment by worldlydev** [comment]
Hasn't occurred in a while.
