### ISSUE TITLE
Allow state change of "Get" button when package is queued

### ISSUE THREAD

**Issue by brennanleblanc0** [zbrateam/Zebra#1395]
In the current beta (1.2b1), when the get button is selected to install a package, it’s state does not change and remains at “Get”.

What would solve this is to change "Get" to "Queued" (or something along the lines) when the package is selected. This would help avoid confusion when you’re selecting many packages at a time.

**Comment by Hhss503** [comment]
is:open label:suggestion

**Comment by Hhss503** [comment]
is:open label:suggestion
