### ISSUE TITLE
Update all crash

### ISSUE THREAD

**Issue by worldlydev** [zbrateam/Zebra#1404]
**Describe the bug**

I pressed update all and Zebra crashed.

**To Reproduce**

^

**Expected behavior**

No crash

**Screenshots**

![41E66546-4B5F-49AA-8192-78852CF2148F](https://user-images.githubusercontent.com/51668635/83979311-bf74e700-a90d-11ea-85d5-d7ba9dce34b4.png)

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2 - beta 1b
 - Device Type [e.g. iPhone or iPad]: iPhone 11 pro
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Uncover

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

2 seperate logs:
https://ghostbin.co/paste/eufcx
https://ghostbin.co/paste/e5yaq

**Additional context**

N/A

**Comment by worldlydev** [comment]
AppList (applist) v1.5.16 by Ryan Petrich  via BigBoss
APT (apt) v1.8.2-3 by Ukjent via Bingner/Elucubratus
APT (apt-key) (apt-key) v1.8.2-1 by Ukjent via Bingner/Elucubratus
APT 1.4 Transitional (apt1.4) v1:0 by Ukjent via Bingner/Elucubratus
Base Structure (base) v1-5 by Ukjent via Bingner/Elucubratus
Bourne-Again SHell (bash) v5.0.3-2 by Ukjent via Bingner/Elucubratus
Berkeley DB (berkeleydb) v6.2.32-1 by Ukjent via Bingner/Elucubratus
bzip2 (bzip2) v1.0.6-1 by Ukjent via Bingner/Elucubratus
CA Certs (ca-certificates) v0.0.2 by Ukjent via Bingner/Elucubratus
libflora (co.dynastic.ios.lib.flora) v1.0 by Dynastic via Dynastic Repo
ipadify (codes.rambo.ipadify) v0.0.3 by Guilherme Rambo via Packix
PicaHide (com.aeonlucid.snaphide2) v1.2.2 by AeonLucid  via BigBoss
DigitalBattery13 (com.asterix.digitalbattery13) v1.1.0 by Asterix  via BigBoss
BetterCCXI (com.atwiiks.betterccxi) v1.6.0 by ATWiiks via Packix
AppStore++ (com.cokepokes.appstoreplusplus) v0.9.11 by CokePokes via Phantom Apps LLC 
libnotifications (com.cokepokes.libnotifications) v0.3-1 by CokePokes  via Phantom Apps LLC 
libCSPreferences (com.creaturecoding.libcspreferences) v1.4.6 by CreatureSurvive  via https://creaturecoding.com/repo/
shuffle (com.creaturecoding.shuffle) v1.2.8 by CreatureSurvive  via https://creaturecoding.com/repo/
libCSColorPicker (com.creaturesurvive.libcscolorpicker) v1.0.3 by CreatureSurvive  via https://creaturecoding.com/repo/
ByeBreadcrumbs (com.cydiageek.byebreadcrumbs) v1.0.3 by CydiaGeek  via BigBoss
QuitAll (com.daveapps.quitall) v1.0.1 by Dave van Wijk  via Chariz
Substitute (com.ex.substitute) v0.1.13 by comex  via Bingner/Elucubratus
iCleaner Pro (com.exile90.icleanerpro) v7.8.3~beta1 by Ivano Bilenchi  via Lokal kilde
Zenumbra (com.foxfort.zenumbra) v1.0.3 by FoxfortMobile  via Foxfort Repo
CCCalc (com.gilesgc.cccalc) v1.1.2 by gilesgc via gilesgc repo
Wraith (com.ion.wraith) v0.0.6 by Justin Carlson  via BigBoss
SugarCane (com.ioscreatix.sugarcane) v1.2-3+debug by iOS Creatix, kasiimh1, baptistecdr via Lokal kilde
Dayn (com.jannikcrack.devvix.dayn) v1.0.1 by Devvix, JannikCrack  via Chariz
Maple 2 (com.laughingquoll.maple2) v1.3.1 by LaughingQuoll via Packix
PrefixUI (com.laughingquoll.prefixui) v1.2.6 by LaughingQuoll  via Chariz
Locale Profiles in UTF-8 (com.linusyang.localeutf8) v1.0-1 by Linus Yang  via BigBoss
ReProvision (com.matchstic.reprovision) v0.5.2~EOL by Matt Clarke  via Matchstic
kindaStock (com.mirac.kindastock) v1.0 by Mirac  via Lokal kilde
Cr4shed (com.muirey03.cr4shed) v4.1.4 by Muirey03 via Lokal kilde
Flow (com.muirey03.flow) v1.1.6 by Muirey03 via Packix
libMRYIPC (com.muirey03.libmryipc) v1.0 by Muirey03 via Dynastic Repo
PowerModule (com.muirey03.powermodule) v1.3.1 by Muirey03 via Packix
CCSupport (com.opa334.ccsupport) v1.2.2 by opa334  via BigBoss
Choicy (com.opa334.choicy) v1.2 by opa334  via BigBoss
RocketBootstrap (com.rpetrich.rocketbootstrap) v1.0.9 by Ryan Petrich  via rpetrich
Sileo Safe Mode (checkrain/substrate) (com.saurik.substrate.safemode) v1.1-1 by Ukjent via Sileo (checkra1n)
AutoUnlockX (com.spark.autounlockx) v1.0.16 by Spark via SparkDev
CircleSettings (com.spark.circlesettings) v1.0.1 by Spark via SparkDev
HideBarX (com.spark.hidebarx) v0.0.4 by Spark via SparkDev
libSparkAppList (com.spark.libsparkapplist) v1.0.9 by Spark via SparkDev
LowBatteryBanner (com.spark.lowbatterybanner) v1.0.2 by Spark via SparkDev
NoCCBar (com.spark.noccbar) v2.0.0 by Spark via SparkDev
SnowBoard (com.spark.snowboard) v1.3.3~Beta3 by Spark via SparkDev
Sposify (com.spos) v8.5.52 by aesthyrica via Dynastic Repo
FloatyDock (com.synnyg.floatydock) v2.3 by SynnyG  via BigBoss
Filza File Manager (com.tigisoftware.filza) v3.7.5-9 by TIGI Software  via BigBoss
PerfectTimeXS (com.yourepo.kingmehu.perfecttimexs) v0.2.1-2 by HuChundong  via kingmehu Source - YouRepo
Core Utilities (coreutils) v8.31-1 by Ukjent via Bingner/Elucubratus
Core Utilities (/bin) (coreutils-bin) v8.31-1 by Ukjent via Bingner/Elucubratus
Cydia Compatibility Package (Checkrain) (cydia) v2.3-checkra1n by CoolStar  via Sileo (checkra1n)
Cydia Installer (cydia-dark) v2.1-1 by Jay Freeman (saurik)  via Sileo (checkra1n)
Cydia Translations (cydia-lproj) v1.1.32~b1 by Jay Freeman (saurik)  via Bingner/Elucubratus
Darwin Tools (darwintools) v1.1-1 by Ukjent via Bingner/Elucubratus
Debian Utilities (debianutils) v4.8.6-1 by Ukjent via Bingner/Elucubratus
libaurora (dev.ayden.ios.lib.sys.aurora) v1.0.2 by Ayden Panhuyzen via Dynastic Repo
Diff Utilities (diffutils) v3.6-1 by Ukjent via Bingner/Elucubratus
diskdev-cmds (diskdev-cmds) v593.221.1-1 by Ukjent via Bingner/Elucubratus
Debian Packager (dpkg) v1.19.7-1 by Ukjent via Bingner/Elucubratus
Essential (essential) v0-2 by Ukjent via Bingner/Elucubratus
file (file) v5.35-2 by Ukjent via Bingner/Elucubratus
Find Utilities (findutils) v4.6.0-2 by Ukjent via Bingner/Elucubratus
iPhone Firmware (/sbin) (firmware-sbin) v0-1 by Ukjent via Bingner/Elucubratus
GNU Cryptography (gcrypt) v1.8.3-1 by Ukjent via Bingner/Elucubratus
gettext (gettext) v0.19.8-1 by Ukjent via Bingner/Elucubratus
GnuPG (gnupg) v2.2.11-2 by Ukjent via Bingner/Elucubratus
GnuTLS (gnutls) v3.5.19-1 by Ukjent via Bingner/Elucubratus
grep (grep) v3.1-1 by Ukjent via Bingner/Elucubratus
gzip (gzip) v1.9-1 by Ukjent via Bingner/Elucubratus
FlyJB (kr.xsf1re.flyjb) v0.2.5.3 by XsF1re  via 새콤한 칠리소스
Launch Daemon Controller (launchctl) v23-1 by Ukjent via Bingner/Elucubratus
Link Identity Editor (ldid) v2:2.1.2+g5420cb5-1 by Jay Freeman (saurik)  via Bingner/Elucubratus
APT 1.8 Strict (lib) (libapt) v1.8.2-sileo6 by Ukjent via Sileo (checkra1n)
Assuan (libassuan) v2.5.1-1 by Ukjent via Bingner/Elucubratus
GNU Multiple Precision Arithmetic Library (libgmp10) v6.1.2-1 by Ukjent via Bingner/Elucubratus
GnuPG Errors (libgpg-error) v1.32-1 by Ukjent via Bingner/Elucubratus
libidn2 (libidn2) v6.1.2-1 by Ukjent via Bingner/Elucubratus
KSBA (libksba) v1.3.5-1 by Ukjent via Bingner/Elucubratus
libplist (libplist) v2.0.0-2 by Ukjent via Bingner/Elucubratus
OpenSSL 1.0 Libraries (libssl1.0) v1.0.2s-1 by Ukjent via Bingner/Elucubratus
OpenSSL 1.1.1 Libraries (libssl1.1.1) v1.1.1c-1 by Ukjent via Bingner/Elucubratus
libtasn1 (libtasn1) v4.13-1 by Ukjent via Bingner/Elucubratus
libunistring (libunistring) v0.9.10-1 by Ukjent via Bingner/Elucubratus
LZ4 (lz4) v1.7.5-1 by Ukjent via Bingner/Elucubratus
LZMA Utils (lzma) v2:4.32.7-2 by Ukjent via Bingner/Elucubratus
dotto+ (me.conorthedev.dotto+) v1.0.5 by ConorTheDev & Mirac via Dynastic Repo
SnapBack (me.midnightchips.snapback) v2.0.1 by MidnightChips via Dynastic Repo
New Curses (ncurses) v6.1+20181013-1 by Ukjent via Bingner/Elucubratus
New Curses (ncurses5-libs) v5.9-1 by Ukjent via Bingner/Elucubratus
AppSync Unified (net.angelxwind.appsyncunified) v76.0 by Linus Yang, Karen/あけみ  via Karen/あけみ's Repo
libbulletin (net.limneos.libbulletin) v0.1-153 by Elias Limneos via Limneos
Nettle (nettle) v3.4.1-1 by Ukjent via Bingner/Elucubratus
New GNU Portable Threads (npth) v1.6-1 by Ukjent via Bingner/Elucubratus
Sileo (org.coolstar.sileo) v1.8.2 by Sileo Team  via Sileo (checkra1n)
libcolorpicker (org.thebigboss.libcolorpicker) v1.6.8 by PixelFire  via BigBoss
BigBoss Icon Set (org.thebigboss.repo.icons) v1.0 by Ukjent via Bingner/Elucubratus
p11-kit (p11-kit) v0.23.12-1 by Ukjent via Bingner/Elucubratus
7-zip (POSIX) (p7zip) v16.02-1 by Ukjent via Bingner/Elucubratus
PreferenceLoader (preferenceloader) v2.2.4 by Sam Bingner  via BigBoss
Profile Directory (profile.d) v0-1 by Ukjent via Bingner/Elucubratus
readline (readline) v8.0-1 by Ukjent via Bingner/Elucubratus
rsync (rsync) v3.1.3-2 by Ukjent via Bingner/Elucubratus
Unc0ver Policy Softener (science.xnu.substituted) v1.0.0 by pwn20wnd  via Lokal kilde
sed (sed) v4.5-1 by Ukjent via Bingner/Elucubratus
shell-cmds (shell-cmds) v118-8 by Ukjent via Bingner/Elucubratus
Sileo Prep (checkra1n) (sileoprep) v1.1 by Ukjent via Sileo (checkra1n)
system-cmds (system-cmds) v790.30.1-2 by Ukjent via Bingner/Elucubratus
Tape Archive (tar) v1.30-2 by Ukjent via Bingner/Elucubratus
UIKit Tools (uikittools) v1.1.17-1 by Ukjent via Bingner/Elucubratus
unrar (unrar) v5.6.4-1 by Ukjent via Bingner/Elucubratus
unzip (unzip) v6.0+deb9u1-1 by Ukjent via Bingner/Elucubratus
Cephei Tweak Support (ws.hbang.common) v1.15.1 by HASHBANG Productions  via Chariz
NewTerm (iOS 10 – 13) (ws.hbang.newterm2) v2.4 by HASHBANG Productions  via Chariz
Jellyfish (xyz.royalapps.jellyfish) v1.5.1 by Justin Proulx and Ayden Panhuyzen via Dynastic Repo
DragEnabler (xyz.skitty.dragenabler) v1.0 by Skitty via Skitty's Repo
Zebra (xyz.willy.zebra) v1.2~beta1b by Wilson Styres  via Zebra Beta
XZ Utils (xz) v5.2.4-4 by Ukjent via Bingner/Elucubratus
zip (zip) v2.32-1 by Ukjent via Bingner/Elucubratus

**Comment by worldlydev** [comment]
deb https://manolzrepo.github.io/ios/ ./
deb https://getzbra.com/repo/ ./
deb https://julioverne.github.io/ ./
deb https://repo.incendo.ws/ ./
deb https://gilesgc.github.io/repo/ ./
deb https://getzbra.com/beta/ ./
deb https://xtm3x.github.io/repo/ ./
deb https://apt.htv123.com/ ./
deb http://repo.pixelomer.com/ ./
deb https://ryleyangus.com/repo/ ./
deb https://skitty.xyz/repo/ ./
deb https://poomsmart.github.io/repo/ ./
deb https://apt.bingner.com/ ios/1676.10 main
deb https://repo.dynastic.co/ ./
deb https://cokepokes.github.io/ ./
deb https://repo.supercharge.app/ ./
deb https://foxfort.yourepo.com/ ./
deb https://samgisaninja.github.io/ ./
deb https://creaturesurvive.github.io/ ./
deb https://akusio.github.io/ ./
deb https://apt.alfhaily.me/ ./
deb https://yungspecht.github.io/ ./
deb https://repo.packix.com/ ./
deb https://alexpng.github.io/Nepeta-Mirror/ ./
deb https://pr0crustes.github.io/repo/ ./
deb https://dirtybeans.github.io/ ./
deb https://beta.apptapp.me/ ./
deb https://captinc.github.io/ ./
deb http://repo.bonventre.ch/ ./
deb https://sparkdev.me/ ./
deb https://thisrepo.justsucksass.com/ ./
deb https://www.yourepo.com/ ./
deb https://repo.xsf1re.kr/ ./
deb https://repounclutter.coolstar.org/ ./
deb https://apt.cydia.love/ ./
deb https://spicat.github.io/ ./
deb https://repo.getsileo.app/ ./
deb https://repo.chariz.com/ ./
deb https://limneos.net/repo/ ./
deb https://cydia.akemi.ai/ ./
deb https://repo.twickd.com/ ./
deb https://creaturecoding.com/repo/ ./
deb https://rpetri.ch/repo/ ./
deb https://revulate.dev ./
deb https://level3tjg.xyz/repo/ ./
deb http://qwertyuiop1379.com/ ./
deb https://kingmehu.yourepo.com/ ./
deb https://repo.mtac.app/ ./
deb http://apt.thebigboss.org/repofiles/cydia/ stable main
deb https://ib-soft.net/cydia/beta/ ./

**Comment by wstyres** [comment]
Is this reproducible?

**Comment by worldlydev** [comment]
Tweak list:
https://ghostbin.co/paste/r6zgw

Source list:
https://ghostbin.co/paste/63nd6

**Comment by worldlydev** [comment]
> Is this reproducible?

Yes. I purposely didn't update the packages to possibly help debug. This seems to happen like a third of the time. Pressing the update all button multiple times (2 - 3) also makes it crash. They generate 2 different logs. Some weird stuff happens in the queue as well. Multiple of the same package get queued or a ton of packages get queued.

**Comment by worldlydev** [comment]
I went ahead and updated my packages due to them including bug fixes but I don't think this issue had anything to do with my specific packages. This also happened with other package updates after.

**Comment by wstyres** [comment]
This is a hard crash to track down but it *might* be fixed as of 988c555519d441adeff66e8275fa74ee068e6c61. I'm unable to reproduce myself so I don't know. Try again in the next beta and let me know.

**Comment by worldlydev** [comment]
> This is a hard crash to track down but it _might_ be fixed as of [988c555](https://github.com/zbrateam/Zebra/commit/988c555519d441adeff66e8275fa74ee068e6c61). I'm unable to reproduce myself so I don't know. Try again in the next beta and let me know.

Needed access to an app with unbypassable jailbreak detection so had to unjailbreak. Therefore I cannot test and will just go ahead and close the issue.

☺️
