### ISSUE TITLE
Version numbers and other labels missing

### ISSUE THREAD

**Issue by ghost** [zbrateam/Zebra#1412]
**Describe the bug**
When I go to download a new tweak the version selector appears. Non of the versions numbers and letters appear so it’s a blank menu. Buttons still work but non of the text appears
**To Reproduce**
Download tweak on IPhone X on iOS 13.5 using unc0ver
**Expected behavior**
Version selector with numbers and letters appear 
**Screenshots**
![B8F9EDA2-7AB8-4EFF-8CF1-23EE8787AD59](https://user-images.githubusercontent.com/45472267/84339153-cef16b80-ab6b-11ea-8026-aee63368f1b7.png)

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: <13.5>
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: <1.2 beta 1b>
 - Device Type [e.g. iPhone or iPad]: <iPhone X>
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: <Unc0ver 5.1>

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Does this only happen when using the black tint color?

**Comment by wstyres** [comment]
Should be fixed as of 6bc0f2043f31cf61966e40ea3463f640cfb20b3a.
