### ISSUE TITLE
Package Click Issue

### ISSUE THREAD

**Issue by CanerKaraca23** [zbrateam/Zebra#1421]
**Describe the bug**
Packages cannot be clicked on when adding anything to the queue.

**Video**
https://streamable.com/g5p506

**Device Information**
iPhone 5S
iOS 12.5.1
Chimera
Zebra 1.1.15 and 1.2 beta7 (Cannot reproduce on 1.2 beta9a)

**Comment by PoomSmart** [comment]
Weird. I cannot reproduce this.

**Comment by CanerKaraca23** [comment]
> Weird. I cannot reproduce this.

I'm still having this issue. Are you using iOS 12?

**Comment by CanerKaraca23** [comment]
Still having this issue on beta5c

**Comment by CanerKaraca23** [comment]
Still having this issue

**Comment by CanerKaraca23** [comment]
Cannot reproduce on beta 9a but it's occurs on stable.
