### ISSUE TITLE
Reinstalling downgraded package upgrades said package

### ISSUE THREAD

**Issue by NICHOLAS85** [zbrateam/Zebra#1434]
**Describe the bug**
When you reinstall a downgraded package the latest version of the package is queued for installation instead of the version currently installed.

**To Reproduce**
Downgrade any package then reinstall it. You’ll find the latest version installed afterwards.

**Expected behavior**
If the currently installed version is available for reinstallation it should be reinstalled, otherwise an error can be shown stating that version is no longer available for reinstallation.

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.5.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2~beta1b
 - Device Type [e.g. iPhone or iPad]: iPhone X
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Odysseyra1n

**Comment by wstyres** [comment]
Should be fixed as of 14cbb40ea28c56fbff918265c3a8b80f657d29f9.

**Comment by NICHOLAS85** [comment]
Can confirm the correct behavior now occurs, thanks!
