### ISSUE TITLE
Zebra does not recognize APT pinning

### ISSUE THREAD

**Issue by CookieCoder15** [zbrateam/Zebra#1464]
**Is your feature request related to a problem? Please describe.**
This feature request is due to an issue where two tweaks with the same bundle identifier (e.g. one is a drop-in replacement for another) and Zebra tries to get you to update from one tweak to the other if the version is higher. Specifically, I am having this problem with preferenceloader as the Odyssey jailbreak uses [preferenceloader by DHowett](https://github.com/DHowett/preferenceloader) and Zebra tries to get me to "update" to Sam Bingner's version. I also can't differentiate between the two when searching as they have the same bundle identifier. (Although that is less of an issue as you can select which version to install.)

**Describe the solution you'd like**
The ability to hide tweaks updates for a specific repo so that I can hide updates from one repo but still see when the tweak is updated on a repo I want. (e.g. Hide preferenceloader updates from BigBoss repo but allow from Odyssey repo.)

**Describe alternatives you've considered**
I have tried using the current "hide updates" button. The problem is that it hides updates from all repos, meaning I don't know if an update comes out for the tweak on the correct repo.

Edit: I don't want this feature request to be specifically about PreferenceLoader but seeing as there was a comment asking about it (which has just vanished for me) I'll quickly explain. One version of PreferenceLoader is bundled in with Odyssey on the Odyssey repo. Sam Bingner's copy is on the BigBoss repo, which is a default repo on Sileo and helpful to have regardless of which jailbreak I use. Zebra thinks the version on BigBoss is newer and tries to update to it, but the version on the Odyssey is modified specifically for the Odyssey jailbreak and I would like to use that one.

**Comment by absidue** [comment]
If you are jailbroken with Odyssey you shouldn't be using Sam Bingner's repos.

**Comment by absidue** [comment]
Also the Odyssey repo doesn't have preferenceloader

**Comment by absidue** [comment]
At least it doesn't on my device or in Sileo

**Comment by wstyres** [comment]
I can see why this would be a useful feature but I don't think it is actually needed. It should be up to the repo maintainer to be able to specify that their package is higher than another (in this case, coolstar should be able to bump the version number on their package so that the package from BigBoss would never show up on Zebra or Sileo). I'll do a little more investigation to be sure I'm right but I think `2.2.4~coolstar2` (hosted on Odyssey's repo) is actually a lesser version than `2.2.4` (hosted on BigBoss) so that it will always show as an update as long as you have BigBoss added. Not sure why it was set up this way.

I'm not opposed to the feature but I will do a little more thinking before adding it. My main reservation at the moment is it might be confusing to a lot of users to use and the *specific* use case of it for these two packages is pretty small.

**Comment by wstyres** [comment]
I looked into it a little more and it appears that Coolstar's repo has been APT pinned higher than BigBoss which Zebra is not recognizing. Pinning will be put on the list and added in a future version of Zebra and I think that this is the proper solution to the issue as opposed to a unique feature like this.

**Comment by mwoolweaver** [comment]
sorry to come in kinda late but would it be possible to read pinning prefs from `/etc/apt/preferences.d/`?

**Comment by wstyres** [comment]
Yes, fixing pinning would require reading from `preferences.d`

**Comment by wstyres** [comment]
The latest beta includes support for source pinning but it is still a beta feature and may not properly work yet. Try it out and let us know how it works.

**Comment by PoomSmart** [comment]
@CookieCoder15 Any updates?

**Comment by CookieCoder15** [comment]
Ah sorry my iPhone is running stock iOS 14.2 right now so I can't test. If anyone else could test that would be great. In the meantime, I'll see if my old iPad is in a position to test but I don't think it is.

**Comment by mwoolweaver** [comment]
It's 2 am (TX) here but I will test on my 8 plus when the sun comes back up and I have gotten some sleep.

**Comment by wstyres** [comment]
Going to close this issue, if any individual issues come up with this later, feel free to file another issue.
