### ISSUE TITLE
New Sources page does not follow 'Display Swipe Actions As' setting

### ISSUE THREAD

**Issue by gkeep** [zbrateam/Zebra#1533]
**Describe the bug**
Even if 'Display Swipe Actions As' is set to 'Text' new Sources page still displays icons.

![image](https://i.nuuls.com/Bu770.jpeg)

**Device Information:**
 - iOS Version: 12.4.8
 - Zebra Version: 1.2~beta4a
 - Device Type: 5s
 - Jailbreak Type: unc0ver

**Comment by absidue** [comment]
Should be fixed as by #1545
