### ISSUE TITLE
Missing Upgrade All button

### ISSUE THREAD

**Issue by eve0415** [zbrateam/Zebra#1535]
**Describe the bug**
As the title says. There is no `Upgrade All` button when there are upgrades available.

**To Reproduce**
Wait for some package(s) to have an upgrade.

**Expected behavior**
Show `Upgrade All` button.

**Device Information (please complete the following information):**
 - iOS Version: 13.5
 - Zebra Version: 1.2~beta4a
 - Device Type: iPhone
 - Jailbreak Type: unc0ver

**Comment by wstyres** [comment]
Fixed as of 65e141a5f7f06ebf0154e9f9098ef0861bdb4b6b.

**Comment by eve0415** [comment]
Fixed in [v1.2-beta5a](https://github.com/zbrateam/Zebra/releases/tag/v1.2-beta5a)
