### ISSUE TITLE
Reset scrolling on sources tab not working

### ISSUE THREAD

**Issue by kyondev** [zbrateam/Zebra#1538]
**Describe the bug**
After scrolling a bit in the sources tab and then tapping on the sources tab button does not do anything

**To Reproduce**
1. Scroll down in the sources tab
2. Press the sources tab button
3. Be disappointed that it doesn’t auto scroll back to the top :(

**Expected behavior**
I expect it to to scroll back to the top of the tab kind off like resetting it like the changes and packages tab does. 

**Screenshots**

**Device Information (please complete the following information):**

***Please do not use the word "latest" for Zebra Version because it's inconvenient for us to know the actual version you are talking about - harder to pinpoint the issue.***
 - iOS Version [e.g. 12.1.2 or 10.3.3]: iOS 12.4.8
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.2~beta4
 - Device Type [e.g. iPhone or iPad]: iPhone 6 / iPhone7,2
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: checkra1n

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by wstyres** [comment]
Should be fixed as of e2d7c291310f1e882d593848fe2915737ca756c1
