### ISSUE TITLE
Available upgrades doesn't show until you refresh source(s)

### ISSUE THREAD

**Issue by eve0415** [zbrateam/Zebra#1547]
**Describe the bug**

Available upgrades doesn't show after refreshing the sources and re-opening Zebra.

**To Reproduce**

1. Refresh a/all source(s)
2. Check if you have any upgrades available
3. Close Zebra
4. Open Zebra
5. Refresh any source to show upgrades

**Expected behavior**

To show upgrades without refreshing source if the updates info are already in database.

**Device Information:** 

 - iOS Version: 13.5
 - Zebra Version: 1.2~beta4a
 - Device Type: iPhone
 - Jailbreak Type: unc0ver

**Comment by wstyres** [comment]
Should be fixed as of 21849fbeac292ccbc4f3234d00d52c21b7388326.

**Comment by eve0415** [comment]
Fixed in [v1.2-beta5a](https://github.com/zbrateam/Zebra/releases/tag/v1.2-beta5a)
