### ISSUE TITLE
Queue page doesn't refresh automatically

### ISSUE THREAD

**Issue by eve0415** [zbrateam/Zebra#1548]
**Describe the bug**

The queue page doesn't refresh until I open the queue page twice

**To Reproduce**

1. Put any multiple packages into queue.
2. Open queue to see only 1 package showing in queue.
3. Close and re-open queue page to show all package in queue.

**Expected behavior**

Refresh queue page without opening.

**Screenshots**

https://cdn.discordapp.com/attachments/572784833714192395/754513657215582239/video0.mp4

**Device Information:** 

 - iOS Version: 13.5
 - Zebra Version: 1.2~beta4a
 - Device Type: iPhone
 - Jailbreak Type: unc0ver

**Comment by wstyres** [comment]
Should be fixed as of 5efebd2a882346dc398e36b2589a72cab592db0a.
