### ISSUE TITLE
Queued tweaks not showing up in queue page

### ISSUE THREAD

**Issue by mainhathao** [zbrateam/Zebra#1555]
**Describe the bug**
When queuing tweaks, it shows how many tweaks are queued in the small bar but when it’s expanded, there’s only 1 tweak shown and I have to dismiss the queue page and open it again to see all the queued tweaks. 

**To Reproduce**
Queue more than 2 tweaks and expand the queue page

**Expected behavior**
It’s supposed to show all queued tweaks instead of just 1
**Device Information:** 

 - iOS Version: <13.5>
 - Zebra Version: <1.2~beta5c>
 - Device Type: <iPhone Xs Max>
 - Jailbreak Type: <Odyssey>

**Comment by mainhathao** [comment]
Device type: iPhone Xs Max
Jailbreak: Odyssey

**Comment by wstyres** [comment]
Duplicate of #1548
