### ISSUE TITLE
Cannot slide to copy or refresh "Zebra's stable" source

### ISSUE THREAD

**Issue by eve0415** [zbrateam/Zebra#1557]
**Describe the bug**

I don't know if this is a bug or intended, but I cannot slide to copy or refresh default source

**To Reproduce**

 Try to slide and do something

**Expected behavior**

Slide to show copy or refresh button.

**Device Information:** 

 - iOS Version: 13.5
 - Zebra Version: 1.2~beta5b
 - Device Type: iPhone
 - Jailbreak Type: unc0ver

**Comment by wstyres** [comment]
Fixed as of a8f11c024c827b09ba21dea1efd04c854847e26a.
