### ISSUE TITLE
It’s not working

### ISSUE THREAD

**Issue by deshnawysameh** [zbrateam/Zebra#1559]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by eve0415** [comment]
What's not working? Please fill out the problem you are having to this template properly.
Just saying `It's not working' does not fix your problem nor does tell the developer what's wrong.

**Comment by deshnawysameh** [comment]
Update source kiiimo not complete

**Comment by deshnawysameh** [comment]
Always asking to upgrade source kiiimo and it's not upgraded
