### ISSUE TITLE
Parcility Source

### ISSUE THREAD

**Issue by CanerKaraca23** [zbrateam/Zebra#1566]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Use Parcility instead of iOS Repo Updates. Because it has more repos and correct repo sources. Check it: https://parcility.co/

**Describe alternatives you've considered**
-
**Additional context**
-

**Comment by wstyres** [comment]
I've switched to Parcility in 6fdf99e3a5b8ae085575e6532e80e809e212ffe6.
