### ISSUE TITLE
Crash when adding too many sources

### ISSUE THREAD

**Issue by Oliverkiller** [zbrateam/Zebra#1570]
**Describe the bug**
zebra crashes if many sources are added at once

**To Reproduce**
try adding many sources at once

**Expected behavior**
add the sources

**Screenshots**

**Device Information:** 

 - iOS Version: <iOS 14>
 - Zebra Version: <1.2~beta6a>
 - Device Type: <iPhone 6s >
 - Jailbreak Type: < odessyra1n >

**Crash Log or System Log**

https://paste.bingner.com/paste/4sg3t

**Additional context**

**Comment by wstyres** [comment]
Would be helpful to know a concrete reproduction steps. How many sources adding at once does it take to crash? Does it happen every time?

**Comment by Oliverkiller** [comment]
30 sources using libhooker as tweak injector

**Comment by wstyres** [comment]
And does it happen every time? Is it the same 30 sources?

**Comment by Oliverkiller** [comment]
Not every single time like 1/10 rate for me and not 30 I said 30 because I have 30 sources written in notes so that's why

**Comment by wstyres** [comment]
Well this is hard to fix without some reproduction steps if it doesn't happen every time. We'll be on the lookout for possible causes and if we find one we'll close the issue.
