### ISSUE TITLE
Crash when unblocking an author

### ISSUE THREAD

**Issue by udevsharold** [zbrateam/Zebra#1573]
**Describe the bug**
Zebra crashed when unblocking an author from the depiction page.

**To Reproduce**
Go to a package's depiction page and try to unblock an already blocked author.

**Expected behavior**
Unblocked as expected.

**Screenshots**
https://imgur.com/a/DQbqelX

**Device Information:** 

 - iOS Version: 13.5
 - Zebra Version: 1.2~beta6
 - Device Type: iPhone
 - Jailbreak Type: unc0ver

**Crash Log or System Log**
https://pastebin.com/70mYt7fS 

**Additional context**
None

**Comment by eve0415** [comment]
I haven’t tested a lot but this crash may occur when the author doesn’t have an email address. And removing from filter section in settings will not crash.
