### ISSUE TITLE
cant download this tweak it keeps on saying there was a issue

### ISSUE THREAD

**Issue by dan69420bitch** [zbrateam/Zebra#1579]
![3172118A-CFB4-475E-8D67-547AC242B852](https://user-images.githubusercontent.com/71949722/94351849-cbeb8f80-0023-11eb-86a5-79dbf1acd658.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by Plasmapea987** [comment]
Get the sparkdev.me repo 🙂
