### ISSUE TITLE
Can't clear or refresh sources on Zebra 1.1.10-13 and 1.2~beta6a

### ISSUE THREAD

**Issue by AdamSaketume26** [zbrateam/Zebra#1586]
**Describe the bug**

My older version of Zebra (1.1.13?) was not updating **all** of my sources. I knew this because Cercube had an update in Cydia, but in Zebra is was still showing it outdated by one version. I cleared my source cache in hopes of it working, but in 1.1.13 I was met with a black screen and no indication of progress. I stayed like this for a minute until I gave up.

So I upgraded to the most recent beta in hopes of it fixing. **All** my sources were not even being added let alone updated. There were no packages being listed at all. When I refreshed my sources, they would all refresh instantly, but **none** of the sources would list any packages, I can't even click on them. Not even the ones I know to be working like Packix were loaded and shown to have packages. I tried clearing my sources again. This time, I was met with a verbose log of what happened, but it **never finished clearing**. I waited for 3 minutes, nothing. Sources were still showing as to be refreshing when that wasn't the case.

I think this is because of sources timing out and not being able to be reached at all.

**To Reproduce**

idk just have Kritanta's repos still added and maybe Aesthyrica's. Originally they both were http but the beta told me to change it to https, still didn't help

`https://repo.openpack.io/`
`https://repo.kritanta.me/`
`https://aesthyrica.com/repo/`

**Expected behavior**

I expect for all my sources to update. For my sources to clear successfully and prompt me to close the clear verbose UI when it's done. For the app to allow me to cancel the refresh of sources via the refresh tab.

**Screenshots**

![image](https://user-images.githubusercontent.com/72011070/94410596-88894200-0145-11eb-8639-26d0507fbe74.png)

**Device Information:** 

 - iOS Version: 13.5
 - Zebra Version: 1.1.10-13, 1.2~beta6a
 - Device Type: iPhone XR
 - Jailbreak Type: unc0ver

**Crash Log or System Log**

**Additional context**

Video of attempting to refresh sources: https://streamable.com/vnymqz
Video of attempting to clear sources: https://streamable.com/cy3lud

**Comment by absidue** [comment]
Is this still an issue on the most recent beta (1.2~beta7b)?

**Comment by wstyres** [comment]
Closing as inactive.
