### ISSUE TITLE
Unable to install tweaks

### ISSUE THREAD

**Issue by Oliverkiller** [zbrateam/Zebra#1589]
**Describe the bug**
every time I try install any tweak and error shows which is included in screenshot

**To Reproduce**

Try installing a tweak
**Expected behavior**
to install

**Screenshots**
 ![image](https://user-images.githubusercontent.com/38816578/94916287-b60c1d80-04ae-11eb-93a9-7e41df548924.png)

**Device Information:** 

 - iOS Version: <iOS 14>
 - Zebra Version: <1.2~beta6a>
 - Device Type: <iPhone 6s>
 - Jailbreak Type: < odessyra1n >

**Crash Log or System Log**

**Additional context**
the last tweak I tried installing before it happened was gestures13 from big boss repo by iCraze & Ryan Nair which the issue started first at if it helps

**Comment by absidue** [comment]
Can you please refreshing your sources and try downloading it again?

**Comment by Oliverkiller** [comment]
Sry for inconvenience it was a corrupt tweak 50% installed from Sileo

**Comment by Oliverkiller** [comment]
My bad
