### ISSUE TITLE
Repo updates don't register in Zebra for whatever reason.

### ISSUE THREAD

**Issue by Va1a** [zbrateam/Zebra#1590]
**Describe the bug**
For many tweaks, updates just fail to show up even though they have already been pushed to the repo. If I go into Cydia for example, the tweak updates have shown up, but for some reason, even with multiple source refreshes, the tweaks do not show as updatable in Zebra. Not sure what's going on.

**To Reproduce**
Have a tweak installed long term, and when the developer announces they've pushed an update, refresh the source, only to see that the update has shown up in other package managers like Cydia, but not in zebra.

**Expected behavior**
Updates should show up in the packages tab as normally expected.

**Screenshots**

N/A
**Device Information:** 

 - iOS Version: 13.2.2
 - Zebra Version: 1.1.13
 - Device Type: iPhone 11,2
 - Jailbreak Type: unc0ver

**Crash Log or System Log**

N/A
**Additional context**

N/A

**Comment by PoomSmart** [comment]
What if you try "Reset Sources Cache"?

**Comment by Va1a** [comment]
That worked, but I feel as though this step should not be mandatory for everyday usage.

**Comment by PoomSmart** [comment]
We probably know the root cause for this. Will push the fix soon.
