### ISSUE TITLE
Visual Glitch with light and dark mode on zebra for ios 12

### ISSUE THREAD

**Issue by F0lkl0re** [zbrateam/Zebra#1591]
**Describe the bug**
It is a visual bug for dark and light mode on zebra. I think it only works on ios 12.

**To Reproduce**
Just launch the app lol

**Expected behavior**
Have no visual glitches and have a clean dark or light mode.

**Screenshots**

![image](https://user-images.githubusercontent.com/51024076/94998046-3731e600-057d-11eb-839b-742257b84228.png)

**Device Information:** 
 - iOS Version: <12.4.8>
 - Zebra Version: 1.2-beta6a
 - Device Type: Iphone 6+
 - Jailbreak Type: unc0ver

**Additional context**

The visual glitch is quite annoying, and a temp fix is to click zebra settings and click back. Then, the dark/light mode is fixed for while the app is launched. When relaunching zebra, dark mode/light mode issue is reverted.

**Comment by CanerKaraca23** [comment]
https://github.com/zbrateam/Zebra/issues/1331
