### ISSUE TITLE
After the update to the last version, I cant Fully download any package. The once solution that I found was to downgrade to the older version.

### ISSUE THREAD

**Issue by pierreluctcyr** [zbrateam/Zebra#1592]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by wstyres** [comment]
Please fill out the template fully to file an issue. If you're using CyDown and having trouble with downloads, please remove it.
