### ISSUE TITLE
Unable to get a repo

### ISSUE THREAD

**Issue by Oliverkiller** [zbrateam/Zebra#1600]
**Describe the bug**

Repo gives an error 
**To Reproduce**
try to add the repo: https://ocean.webjungle.ch/

**Expected behavior**

To add
**Screenshots**

**Device Information:** 

 - iOS Version: <iOS 14>
 - Zebra Version: <1.1.13>
 - Device Type: <iPhone 6s >
 - Jailbreak Type: < odessyra1n >

**Crash Log or System Log**

**Additional context**
I tried adding the same repo in other installers and it worked

**Comment by Oliverkiller** [comment]
![image](https://user-images.githubusercontent.com/38816578/96197857-7ab02b00-0f53-11eb-924b-56aa1639924e.png)

**Comment by wstyres** [comment]
We're not able to reproduce this issue. Does it still occur? It looks like a sever issue that may have been temporary.

**Comment by Oliverkiller** [comment]
It was added successfully now
