### ISSUE TITLE
TweakCompatible/TweakReviewsDB built into Zebra

### ISSUE THREAD

**Issue by Garydunlop00** [zbrateam/Zebra#1603]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
A ✅ or ❌ on the tweaks icon to show if it's reported working or not on the list view and a small bar at the bottom of the tweak depiction with the text "Working or Not Working"

**Describe alternatives you've considered**
An alternative would be to use tweakCompatible or TweakReviewsDB to make it easier.

**Additional context**

**Comment by wstyres** [comment]
Zebra 1.2 allows for developers to set their own compatibility tags within their tweaks and a ✅ or an ❌ will display if the developer has marked their tweak as compatible.

At the time, we have no plans of integrating community reports via any separate tweak. This may change in the future though.
