### ISSUE TITLE
zebra is not works on iphone SE 1st running ios 14.0.1😒

### ISSUE THREAD

**Issue by pisethsamoeurn** [zbrateam/Zebra#1607]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by absidue** [comment]
Duplicate of #1604
