### ISSUE TITLE
Zebra stuck at refreshing/resetting sources when a repo is downed

### ISSUE THREAD

**Issue by yur1xpp** [zbrateam/Zebra#1613]
**Describe the bug**
Timed out repo effectively making Zebra in infinite refresh sources loop. The timeout was already set to 5 seconds, so I expect it to continue refreshing other sources even though a repo was timed out, but it’s not. As of writing this, http://cydia.angelxwind.net/ is down and zebra is currently unable to do a refresh or reset sources cache (in my humble opinion, this should not be happening, as reset shouldn’t be stuck due to one repo downed).

**To Reproduce**
Refresh sources/reset sources with a downed repo on the list.

**Expected behavior**
Refresh as usual. Removed the said repo fixed it. I low key really would love if zebra team added an quick table swipe action to temporary disable a repo. It helps a lot for situation like this.

**Screenshots**
1. When automatic refresh is enabled (which means zebra is refreshing when launched) and trying to reset sources, it stuck at empty console (also, can’t be cancelled using the cancel button): https://imgur.com/a/N5oeWl7

2. When zebra is not refreshing (automatic refresh is not enabled) and trying to reset cache, it stuck at downed repo: https://imgur.com/a/3dP5JYZ 

**Device Information:** 

 - iOS Version: 13.5
 - Zebra Version: 1.2beta6a
 - Device Type: iPad & iPhone 
 - Jailbreak Type: unc0ver

**Crash Log or System Log**

**Additional context**

**Comment by AdamSaketume26** [comment]
Same issue for a long time now https://github.com/zbrateam/Zebra/issues/1586

**Comment by absidue** [comment]
Is this still an issue on the most recent beta (1.2~beta7b)?

**Comment by yur1xpp** [comment]
I can't actually try out the beta7a yet, since I'm having all these problems listed in https://github.com/zbrateam/Zebra/issues/1657
Currently downgraded to previous beta.

**Comment by wstyres** [comment]
Hi! Thanks for your issue report. Unfortunately we do not support the 1.2 beta versions anymore and this issue will be closed. You can either downgrade to the latest stable version (1.1.18) or install the Zebra 2.0 Alpha and see if your issue still persists. If the issue does still persist, please file a new issue.
