### ISSUE TITLE
Dont have store át zebra hơn page

### ISSUE THREAD

**Issue by Teppi0309** [zbrateam/Zebra#1614]
**Describe the bug**

U using IP5C.
I installed zebra. But I dont have store at My home page

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by wstyres** [comment]
Zebra does not support stores and package purchasing on iOS 10 and earlier, this is due to a limitation with the modern payment API.
