### ISSUE TITLE
Cannot find download URL if reinstalling local package from repo

### ISSUE THREAD

**Issue by p0358** [zbrateam/Zebra#1615]
**Describe the bug**

If there is a local version of a package and it has just been published on a repo (after Zebra finished refreshing ofc), pressing Reinstall causes Zebra to show yellow message that it couldn't find the download URL.

**To Reproduce**

1. Install some package from a local deb file (with theos in this case)
(the version might be newer or the same of what's available on a repo)
2. Open package view, press Reinstall button
3. The package gets correctly queued, with the version from repo shown to reinstall
4. You press the confirm button, and get the mentioned error
(**this seems to work if Zebra is restarted after that!**)

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: 13.5
 - Zebra Version: 1.2~beta6a
 - Device Type: iPhone
 - Jailbreak Type: Odysseyra1n

**Crash Log or System Log**

**Additional context**

I frequently find myself in a situation where I upload a package to my repo, and then press Reinstall to make sure it all downloads and installs flawlessly, from what I remember it didn't cause any issues in earlier versions of Zebra.
Also worth to note that many already installed packages frequently show as from "Local repo", when in fact they're not. Then depiction isn't shown, and also pressing on the author on the bottom reveals an empty page.

**Comment by PoomSmart** [comment]
@p0358 Does this still happen on beta 8a?

**Comment by PoomSmart** [comment]
@p0358 I understand that the packages installed locally will not have their source information, unless the user restarts Zebra and Zebra seemingly sync all packages in background.

> I frequently find myself in a situation where I upload a package to my repo, and then press Reinstall to make sure it all downloads and installs flawlessly

Shouldn't you refresh your repo first before trying to reinstall a package?

**Comment by PoomSmart** [comment]
Nonetheless, I think this PR may help aid this issue somewhat. https://github.com/zbrateam/Zebra/pull/1744
