### ISSUE TITLE
Lack of view refresh after packages list or package state was changed

### ISSUE THREAD

**Issue by p0358** [zbrateam/Zebra#1616]
**Describe the bug**

When repos have finished refreshing, "Packages" and "Changes" views and any opened package view should be refreshed.
After a package was installed/uninstalled, opened package view should be refreshed.
Both are not refreshed and require switching tab back and forth or reentering the package details page.

This leads to latest updates not showing immediately on "Packages" tab, despite the badge is changed.
After a package is installed, its state is not updated, so you have a "Get" or "Modify" button, despite their caption being wrong. You also have certain package details missing, such as the list of installed files.

**To Reproduce**
Variant A (assume there are new updates published, of which Zebra is not aware yet)
1. Open Zebra, it starts to refresh sources in the background automatically
2. Go into "Packages" tab
3. Zebra finishes updating repos, the badge is updated showing some number of updates available
4. Nothing is changed in the opened tab, no packages to update appear

Variant B
1. Install a package
2. Close out the installation window
3. The package still has "Get" button ("was it not installed?", a user might think), other details like the list of installed files are missing

Variant C
1. Open supposedly local package for which Zebra hasn't loaded info yet, it shows as from "Local repo"
2. Zebra had finished refreshing sources and found that exact package in there
3. User still sees "Local repo" as the source
4. They need to reenter the depiction page to show the correct package details page

**Expected behavior**

Views are outdated and user needs to reenter them to update with the latest information.

**Screenshots**

**Device Information:** 

 - iOS Version: 13.5
 - Zebra Version: 1.2~beta6a
 - Device Type: iPhone
 - Jailbreak Type: Odysseyra1n

**Crash Log or System Log**

**Additional context**

**Comment by wstyres** [comment]
Hi! Thanks for your issue report. Unfortunately we do not support the 1.2 beta versions anymore and this issue will be closed. You can either downgrade to the latest stable version (1.1.18) or install the Zebra 2.0 Alpha and see if your issue still persists. If the issue does still persist, please file a new issue.
