### ISSUE TITLE
Unable to install/reinstall/delete tweaks

### ISSUE THREAD

**Issue by JellyPeixe** [zbrateam/Zebra#1618]
**Describe the bug**
 The bug is that when I try to install, reinstall, upgrade, downgrade or remove any tweaks I get an error “incompatible cpu-subtype”

**To Reproduce**
Whenever I try to install/remove/update a tweak

**Expected behavior**
Be able to manage my tweaks as I please, installing or removing them

**Screenshots**
![image](https://user-images.githubusercontent.com/54193604/99689619-f840ec80-2a65-11eb-9456-07805a9c093a.jpeg)
 

**Device Information:** 

 - iOS Version: <13.5>
 - Zebra Version: <1.1.14>
 - Device Type: iPhone
 - Jailbreak Type: unc0ver

**Crash Log or System Log**
https://pastebin.com/zEZ5pi9X

**Additional context**
When I get the error, I algo get a crash from supersling

**Comment by Juvencus** [comment]
Same issue on iPad Pro 2018 and iPhone X, both 13.5 with unc0ver 5.3.1

**Comment by itsTyrion** [comment]
Same. 
iOS 13.5, iPhone 11 Pro, unc0ver
[Log](https://pastebin.com/GeZq6dtb)

**Comment by JellyPeixe** [comment]
Also, downgrading Zebra to the previous 1.1.13 version seems to solve the problem. You need to use Cydia to downgrade because, as stated above, Zebra doesnt allow it.

**Comment by itsTyrion** [comment]
> Also, downgrading Zebra to the previous 1.1.13 version seems to solve the problem. You need to use Cydia to downgrade because, as stated above, Zebra doesnt allow it.

Can confirm

**Comment by wstyres** [comment]
It looks to be a problem when building Zebra using Xcode 12. We're working on a fix now.

**Comment by wstyres** [comment]
I've just released Zebra 1.1.15. See if this version fixes the error for you.

**Comment by JellyPeixe** [comment]
> I've just released Zebra 1.1.15. See if this version fixes the error for you.

It seems like the new version 1.1.15 fixes the error for me! That was really quick, thanks so much for the support!
