### ISSUE TITLE
Error when upgrading from 1.1.14 to 1.1.15

### ISSUE THREAD

**Issue by kmcnamaratx** [zbrateam/Zebra#1621]
**Describe the bug**
When updating zebra from 1.1.14 to 1.1.15 (in zebra), I am getting the error dyld: incompatible cpu-subtype: 0x80000002 in /usr/lib exec/zebra/supersling

**To Reproduce**
Go into zebra and go through the upgrade process. This is occurring on an iPhone XR jailbroken with Unc0ver 5.0.1

**Expected behavior**
Error should not occur and upgrade should complete successfully

**Screenshots**
Attached
![83DB8094-7A2D-42F3-A776-86ED0CDA999A](https://user-images.githubusercontent.com/17275786/99843537-54c00c80-2b37-11eb-8824-b58bc2aac193.png)

**Device Information:**
This is occurring on an iPhone XR running iOS 13.5 jailbroken with Unc0ver 5.0.1

**Comment by wstyres** [comment]
This was an error that occurred exclusively with 1.1.14. You'll have to use another package manager to upgrade Zebra and it should work fine after that. If you don't have another package manager, you can download and install the deb from here: https://getzbra.com/downloads/latest

**Comment by kmcnamaratx** [comment]
Used Cydia and this fixed it. Thanks for the quick response.

**Comment by kmcnamaratx** [comment]
Fixed by using Cydia to update.

**Comment by Official-Darkn** [comment]
I was going to say to use Cydia and upgrade Zebra there, but I wasn't fast enough, nice thing it works for you now!
