### ISSUE TITLE
zebra crashes when using swipe gesture/actions repeatedly within short period of time

### ISSUE THREAD

**Issue by whiteblacksmiths** [zbrateam/Zebra#1622]
**Describe the bug**
 crash

**To Reproduce**
 just searching for packages and use the swipe gestures to queue them (be it uninstall, install or downgrade) very quickly and zebra will crash

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <13.5>
 - Zebra Version: <1.2-beta6>
 - Device Type: <ipX>
 - Jailbreak Type: <odyssey>

**Crash Log or System Log**
 https://ghostbin.com/paste/POs4H

**Additional context**

**Comment by wstyres** [comment]
I'm not able to reproduce this myself, could you take a screen recording of the crash you're trying to show and upload it?

**Comment by wstyres** [comment]
Closed due to inactivity.
