### ISSUE TITLE
Zebra is not working

### ISSUE THREAD

**Issue by grambouli** [zbrateam/Zebra#1623]
**Describe the bug**
 when I install/reinstall/uninstall any tweak, it gives me an error message saying ( The package mobilesubstrate needs to be reinstalled, but I can't find an archive for it.)

**To Reproduce**
 when I try to upgrade or install any tweak

**Expected behavior**
 Tweaks be installed without error.

**Screenshots**
 ![image](https://user-images.githubusercontent.com/74867195/99908205-47c62900-2caf-11eb-9329-420324c5e308.png)

**Device Information:** 

 - iOS Version: <INSERT-HERE> 13.6.1
 - Zebra Version: <INSERT-HERE> 1.1.15
 - Device Type: <INSERT-HERE> iphone 11 pro max
 - Jailbreak Type: <INSERT-HERE> Odyssey v1.2

**Crash Log or System Log**
 Downloading APT 0.6 Transitional (apt)
Downloading XZ Utils (xz-utils)
Downloading APT 0.7 Transitional (lib) ( apt7-lib)
Downloading 0.7 Transitional (apt7)
Downloading APT 1.4 Transitional (apt1.4)
Done APT 0.6 Transitional (apt)
Done APT 0.7 Transitional (lib) (apt7-lib)
Done APT 0.7 Transitional (apt7)
Done APT 1.4 Transitional (apt1.4)
Done XZ Utils (xz-utils)
Installing Packages...
E: The package mobilesubstrate needs to be reinstalled, but I can't find an archive for it.
Importing local packages.
Finished importing local packages.
Finished.

**Additional context**

**Comment by absidue** [comment]
As you are on Odyssey please remove the Elucubratus repo.

**Comment by grambouli** [comment]
> As you are on Odyssey please remove the Elucubratus repo.

Can You tell me how to do it?

**Comment by grambouli** [comment]
> As you are on Odyssey please remove the Elucubratus repo.

I deleted it but that did not fix the problem.

**Comment by wstyres** [comment]
This is not a bug with Zebra, you do not have the proper sources added in order to download mobile substrate. I would recommend removing sources that are used by other jailbreaks (Bingner/Eclubaratus, checkrain, Cydia) and adding the Odyssey and Procursus repos.
