### ISSUE TITLE
zebra crashes when viewing multiple sources

### ISSUE THREAD

**Issue by whiteblacksmiths** [zbrateam/Zebra#1624]
**Describe the bug**
 zebra crashes when i tap into sources to see the packages. the first repo sometimes works, but after going back to the sources page and tapping into second source zebra crashes. 

**To Reproduce**
 tap into any source, then tap/swipe to go back to main sources page. tapping into second source usually crashes zebra. it may be because i have ~110 sources though. 

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <13.5>
 - Zebra Version: <1.2 beta6a>
 - Device Type: <ipX>
 - Jailbreak Type: <odyssey>

**Crash Log or System Log**
 https://ghostbin.com/paste/ZfR40

**Additional context**

**Comment by wstyres** [comment]
I'm not able to reproduce this crash. Could you take a screen recording and upload it here so that we're able to see the steps better?

**Comment by whiteblacksmiths** [comment]
hey, thanks for the reply. https://imgur.com/a/EpAlvPU in the screen recording, i had to click on 4 to 5 repos, but usually the crash happens right after the second repo. as the video shows, just by tapping on the repos as they are loading, zebra crashes. hope this helps!

**Comment by whiteblacksmiths** [comment]
https://imgur.com/a/EpAlvPU when the repos are loading, tapping on a few repos would crash zebra. i‘ve tried disabling certain tweaks with choicy, and disabling the tweaks increases the number of repos i have to tap on before the crash happens, but i could never pinpoint a specific tweak that is responsible for the crash. https://ghostbin.com/paste/8ct8o this is my current tweaklist if you require more info. hope this helps! thanks!

**Comment by wstyres** [comment]
Hi! Thanks for your issue report. Unfortunately we do not support the 1.2 beta versions anymore and this issue will be closed. You can either downgrade to the latest stable version (1.1.18) or install the Zebra 2.0 Alpha and see if your issue still persists. If the issue does still persist, please file a new issue.
