### ISSUE TITLE
No space left on device when updating sources

### ISSUE THREAD

**Issue by Nexinity7** [zbrateam/Zebra#1625]
**Describe the bug**
After refreshing sources, many will output an error saying: No space left on device 

**To Reproduce**
Pull down to refresh sources in Zebra 

**Expected behavior**
Sources to update or put out a timeout error for bad sources 

**Screenshots**
https://share.icloud.com/photos/0s4kf09tmezQxFAN7lvOqY_8Q

**Device Information**
 - iOS Version: iOS 14.1
 - Zebra Version: 1.2~beta6a
 - Device Type: iPhone 6s
 - Jailbreak Type: checkra1n

**Crash Log or System Log**
idk how or where to get this, the discord was inactive and help would be great!

**Comment by wstyres** [comment]
Not really sure what could be causing this but my first question is do you have any space left on your device? Zebra does not produce these error messages itself and they are usually messages from the system. I'd suggest removing some repos and seeing if the error goes away.

**Comment by Nexinity7** [comment]
I have half of my space available, and removing repos didn’t fix anything

**Comment by wstyres** [comment]
Does this issue occur on the latest beta (1.2~beta7b) of Zebra?

**Comment by Nexinity7** [comment]
> Does this issue occur on the latest beta (1.2~beta7b) of Zebra?

yes it does

**Comment by wstyres** [comment]
Ok, we're still unsure of the cause of this issue. Zebra doesn't produce these error messages, they're produced by the system so iOS must think that you're out of storage for some reason. Could you run something like iCleaner and see how much space is freed up?

**Comment by Nexinity7** [comment]
> Could you run something like iCleaner and see how much space is freed up?

runing iCleaner freed 500mbs of space, and after a respring and refreshing sources zebra crashed and no longer opens

**Comment by PoomSmart** [comment]
@Nexinity7 Any crash logs?

**Comment by Nexinity7** [comment]
@PoomSmart how would i obtain them?

**Comment by mwoolweaver** [comment]
@Nexinity7 does [cr4ashed](https://repo.packix.com/package/com.muirey03.cr4shed) work on iOS 14?

**Comment by Nexinity7** [comment]
@mwoolweaver not sure, ill check it out

**Comment by PoomSmart** [comment]
@Nexinity7 You can also try CrashReporter from CokePokes repo: https://www.ios-repo-updates.com/repository/cokepokes/package/cokepokes.crash-reporter/

**Comment by Nexinity7** [comment]
installing cr4shed restarted my phone and I am unable to rejailbreak for a little bit but ill keep this thread posted for when i get a log

**Comment by Nexinity7** [comment]
zebra is opening again for some reason, maybe just a freak occurrence, and it's not outputting the out of space error anymore, but i'll keep testing for one

**Comment by Nexinity7** [comment]
fixed, no issues
