### ISSUE TITLE
Depiction slow loading

### ISSUE THREAD

**Issue by ca13ra1** [zbrateam/Zebra#1626]
**Describe the bug** 
Depiction page is very slow loading.

**To Reproduce**
Select package and when the depiction loads scroll down and doesn’t seem to load the entire page?

**Expected behavior**
Package depiction doesn’t fully load even after it’s finished loading.

**Screenshots**
https://m.imgur.com/a/r755Z4o

**Device Information:** 

 - iOS Version: iOS 14.2
 - Zebra Version: 1.1.15
 - Device Type: iPhone
 - Jailbreak Type: checkra1n

**Crash Log or System Log**

**Additional context**

**Comment by absidue** [comment]
Closing as this is fixed in the beta versions.

**Comment by ca13ra1** [comment]
Thank you! I’ll try the beta version. I didn’t know that was an option.
