### ISSUE TITLE
When I try to login to the repos within the store it keeps pulling the wrong email address and login for Twickd repo. Is there any way that I can set the usernames and passwords for each repo individually myself?

### ISSUE THREAD

**Issue by OCBiggiE** [zbrateam/Zebra#1627]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by OCBiggiE** [comment]
Sorry iPhone 11 Pro Max iOS 14.2 unfortunately... lost my jailbreak like an idiot

**Comment by wstyres** [comment]
Zebra doesn't save your login info after you log out. If you're unable to change which account is logged into after you sign out in Zebra, the repository might be saving your login information that way. Is this what you're experiencing?

**Comment by OCBiggiE** [comment]
Well when I first downloaded the repo and went to download everything I previously purchased, it had thebwrongbe MN ail address from the start. I have not used that the email addressbin over 10 years I have no idea where it pulled it from   
  

  
I can login to Twickd just fine through Safari but it doesn't translate over to Zebra so I can buy/download anything   
  
  
  
    
  

  
  
>

**Comment by wstyres** [comment]
Does this happen in any other repos? If not it might be a problem with Twickd.

**Comment by OCBiggiE** [comment]
So far I’ve only noticed tricked ad of course they are saying the same thing. They are telling me it’s zebra and your telling me it’s them lol.... to save everyone time and a headache do you know possibly of a work around

**Comment by wstyres** [comment]
I would suggest logging out of Twickd, clearing your website data in iOS Settings (under Safari), then clearing your web cache in Zebra (under reset), then reinstalling Zebra. After that, you may have luck with getting the cached information removed. Other than that I'm not too sure.
