### ISSUE TITLE
Error when installing reinstalling ... a tweak

### ISSUE THREAD

**Issue by MagicYT103** [zbrateam/Zebra#1637]
**Describe the bug**
 when I’m trying to install reinstall ... a tweak an error pops up which says: E: The Package ldid needs to be reinstalled, but I can’t find an archive for it.
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/40032411/100518143-7b65ef00-3198-11eb-866a-d30a3f2269da.jpeg)

**Device Information:** 

 - iOS Version:iOS 13.5 <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: unc0ver  <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by wstyres** [comment]
Are you sure that you've added the proper sources for ldid? Depending on your jailbreak, this should be Binger/Eclubaratus.

**Comment by MagicYT103** [comment]
> Are you sure that you've added the proper sources for ldid? Depending on your jailbreak, this should be Binger/Eclubaratus.
I fixed it I just restored root fs
