### ISSUE TITLE
I can’t download any tweak

### ISSUE THREAD

**Issue by 04062008** [zbrateam/Zebra#1645]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by 04062008** [comment]
I can’t download any tweak

**Comment by eve0415** [comment]
Please fill out the issue template.

**Comment by wstyres** [comment]
Please fill in the issue template and refile this issue. Without more information we cannot help you.
