### ISSUE TITLE
Carbridge is not work with my phone please help

### ISSUE THREAD

**Issue by mahfuzstr** [zbrateam/Zebra#1648]
![image](https://user-images.githubusercontent.com/75742363/102017707-8fedde00-3d79-11eb-881a-bf8ea21ffd49.png)
![Uploading 102017714...]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by wstyres** [comment]
Closing this as this is a forum for issues specifically related to Zebra, not the tweaks that it installs. I would suggest asking for help in the CarBridge Discord server: https://carbridgetweak.com/discord.

**Comment by mahfuzstr** [comment]
Thanks

**Comment by mahfuzstr** [comment]
Before three days was ok everything is my carbridge
