### ISSUE TITLE
添加bigboss源失败

### ISSUE THREAD

**Issue by Asce-nil** [zbrateam/Zebra#1649]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by wstyres** [comment]
Please fill out the issue template in order to provide more information so we can resolve the issue quicker.
