### ISSUE TITLE
Zebra 1.2~beta6a won’t download packages on Procursus Bootstrap

### ISSUE THREAD

**Issue by arinc9** [zbrateam/Zebra#1650]
**Describe the bug**

Zebra will be stuck on `Downloading Packages...` when installing/reinstalling any packages.
Useful to remind that this was fixed as of 1.1.10 but the issue still remains on 1.2.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: 13.7
 - Zebra Version: 1.2~beta6a
 - Device Type: iPhone X
 - Jailbreak Type: checkra1n + procursus

**Crash Log or System Log**

**Additional context**

**Comment by wstyres** [comment]
Is this just affecting the procursus repo? Do you have any tweaks like CyDown installed that might affect Zebra?

**Comment by arinc9** [comment]
You hit the nail on the head, it was indeed CyDown. Sorry, I should've been more careful.
