### ISSUE TITLE
Cannot block developer from the filter setting

### ISSUE THREAD

**Issue by eve0415** [zbrateam/Zebra#1656]
**Describe the bug**

Trying to search for developer to block, the results are always empty (It does not show up).

**To Reproduce**

1. Go to filter setting
2. Try to search for developer to block
3. Type something and nothing happens

**Expected behavior**

It should saw some developers that hit in the database

**Screenshots**

None

**Device Information:** 

 - iOS Version: <INSERT-HERE> 13.5
 - Zebra Version: <INSERT-HERE> beta7b
 - Device Type: <INSERT-HERE> iPhone
 - Jailbreak Type: <INSERT-HERE> unc0ver

**Comment by PoomSmart** [comment]
Note: commented out code in `ZBAuthorSelectorTableViewController.m`

**Comment by PoomSmart** [comment]
Re-implemented in https://github.com/zbrateam/Zebra/pull/1688

**Comment by PoomSmart** [comment]
Fixed in beta~7d
