### ISSUE TITLE
Fail to relaunch Zebra

### ISSUE THREAD

**Issue by eve0415** [zbrateam/Zebra#1658]
**Describe the bug**

As the title says. Because of incompatible CPU type

**To Reproduce**

Try to change language and press `Restart`

**Expected behavior**

Probably reopen Zebra

**Device Information:** 

 - iOS Version: <INSERT-HERE> 13.5
 - Zebra Version: <INSERT-HERE> beta7b
 - Device Type: <INSERT-HERE> iPhone
 - Jailbreak Type: <INSERT-HERE> unc0ver

**Crash Log or System Log**

<details>
<summary>Crash log</summary>

Date: 12/20/20, 10:51 AM
Process: relaunch
Bundle id: (null)
Device: iPhone SE (2nd generation), iOS 13.5

Exception type: EXC_SOFTWARE (SIGABRT)
Exception subtype: EXC_UNIX_ABORT
Exception codes: 0x0000000000010002, 0x0000000000000000
Culprit: Unknown
Termination Reason: incompatible cpu-subtype: 0x80000002 in /usr/libexec/zebra/relaunch

Triggered by thread: 18446744073709551615
Thread name: (null)
Call stack:
(null)

Register values:
PC: 0x0                 LR: 0x0                 CPSR: 0x0
x0: 0x0                 x1: 0x0                 x2: 0x0
x3: 0x0                 x4: 0x0                 x5: 0x0
x6: 0x0                 x7: 0x0                 x8: 0x0
x9: 0x0                 x10: 0x0                x11: 0x0
x12: 0x0                x13: 0x0                x14: 0x0
x15: 0x0                x16: 0x0                x17: 0x0
x18: 0x0                x19: 0x0                x20: 0x0
x21: 0x0                x22: 0x0                x23: 0x0
x24: 0x0                x25: 0x0                x26: 0x0
x27: 0x0                x28: 0x0

Loaded images:

{"ProcessBundleID":"","ProcessName":"relaunch","Culprit":"Unknown"}

</details>

**Comment by wstyres** [comment]
Fixed in ea7db525937ab862e630c16a93064811db3dc8a5.

**Comment by PoomSmart** [comment]
Fixed in beta 7c
