### ISSUE TITLE
Zebra crashes after source refresh

### ISSUE THREAD

**Issue by rdc74656** [zbrateam/Zebra#1659]
**Describe the bug**
Zebra is crashing for me but predominantly happens once sources have refreshed. 

**To Reproduce**
Make sure zebra is not running in background, open zebra, refresh sources (either automatically or manually)

**Expected behavior**
No crashing

**Screenshots**

**Device Information:** 

 - iOS Version:13.3
 - Zebra Version: 1.2 beta 7b
 - Device Type: iPhone 11 Pro 
 - Jailbreak Type: unc0ver

**Crash Log or System Log**

**Additional context**

**Comment by absidue** [comment]
Can you please remove Zenumbra if you have it installed and see if it still crashes?

**Comment by rdc74656** [comment]
Yep that appears to have worked.  Thank you but it was a handy feature to have.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
