### ISSUE TITLE
Hide packages doesn’t work anymore.

### ISSUE THREAD

**Issue by Necromantic182** [zbrateam/Zebra#1660]
**Describe the bug**
 
Hiding package updates no longer works. It did in the previous beta (1.2~beta6a) 

**To Reproduce**
 
Try to hide a package update. 

**Expected behavior**
 
I expect the package to be hidden from the update section.

**Screenshots**

**Device Information:** 

 - iOS Version: <13.3>
 - Zebra Version: <1.2~beta7b>
 - Device Type: <iPhone>
 - Jailbreak Type: <unc0ver>

**Crash Log or System Log**

Doesn’t crash. 
**Additional context**

**Comment by wstyres** [comment]
Should be fixed as of 80c33bc5992ef767f99d5fb620e5bc405d84739e.

**Comment by PoomSmart** [comment]
Fixed In beta 7c
