### ISSUE TITLE
Visual bug after using swipe actions

### ISSUE THREAD

**Issue by CanerKaraca23** [zbrateam/Zebra#1662]
**Describe the bug**

In new redesigned installed section there is a bug here, check video.

**To Reproduce**

Try deleting or reinstalling any package.

**Expected behavior**

Fix

**Screenshots**

[(Video)](https://media.discordapp.net/attachments/488424664134058044/790356863384289310/video0.mp4) 

**Device Information:**

 - iOS Version: 12.5.1
 - Zebra Version: 1.2 beta9a
 - Device Type: iPhone 5S
 - Jailbreak Type: Chimera

**Crash Log or System Log**

-

**Additional context**

-

**Comment by wstyres** [comment]
Not able to reproduce this on my end. Could it be unique to iOS 12?

**Comment by CanerKaraca23** [comment]
> Not able to reproduce this on my end. Could it be unique to iOS 12? I don't have my iOS 12 device on me at the moment to verify. Would also be helpful to know if this occurs on every cell or only if you scroll down a bit like shown in the video.

I think all my issues related to iOS 12. It occurs on every cell.

**Comment by CanerKaraca23** [comment]
I'm not having this issue on beta9a. Closed.
