### ISSUE TITLE
Cannot clear sources cache

### ISSUE THREAD

**Issue by eve0415** [zbrateam/Zebra#1663]
**Describe the bug**
As the title says, pressing `Clear Sources Cache` won't do anything.

**To Reproduce**
Press `Clear Sources Cache` at the `Reset` page

**Expected behavior**
clear sources cache

**Device Information:**
 - iOS Version: 13.5
 - Zebra Version: beta7b
 - Device Type: iPhone
 - Jailbreak Type: unc0ver

**Additional context**
Remove `zebra.db` manually

**Comment by PoomSmart** [comment]
Note: relevant code commented out

**Comment by yur1xpp** [comment]
I'm still seeing this issue with 1.2beta7d

**Comment by PoomSmart** [comment]
Re-implemented in #1705
