### ISSUE TITLE
Cannot reinstall any package

### ISSUE THREAD

**Issue by eve0415** [zbrateam/Zebra#1666]
**Describe the bug**
Zebra is saying `Could not find a download URL for PACKAGENAME (BUNDLE IDENTIFIER)`

**To Reproduce**
Try to reinstall any package

**Expected behavior**
Download and reinstall

**Device Information:**
 - iOS Version: 13.5
 - Zebra Version: beta7b
 - Device Type: iPhone
 - Jailbreak Type: unc0ver

**Comment by wstyres** [comment]
This should be fixed as of 9addb74919497abe27f98ef811668c14df1be8cc.

**Comment by eve0415** [comment]
Fixed in beta7c. Thank you. Closing

**Comment by noahmaranesi** [comment]
Is this glitch happening again on `Zebra 1.2~beta8a`? It’s showing for me on the same setup.

**Comment by DarkSideSumthin** [comment]
Having this happen again with Zebra 1.2~beta8a

**Comment by noahmaranesi** [comment]
@eve0415 @wstyres could we get another additional confirmation?

**Comment by eve0415** [comment]
Yeah, it is happening again. Probably, #1744 should fix this in next update
