### ISSUE TITLE
Zebra 1.2-betas7a

### ISSUE THREAD

**Issue by drkey57** [zbrateam/Zebra#1669]
new version of zebra 1.2-betas7a not work on ios 14.2

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by wstyres** [comment]
Please fill out the entire issue template when filing an issue. Otherwise we do not know what is wrong and cannot resolve your issue.
