### ISSUE TITLE
Failed database migration

### ISSUE THREAD

**Issue by drkey57** [zbrateam/Zebra#1672]
After updating from zebra 1.2-beta6a to version 1.2-beta7a, all surce list, update and all installed tracks are lost but only in the zebra application zebra does not refresh,
Once start cydia and reinstall zebra but in the lower version 1.2-beta6a, zebra application works well.

*Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by wstyres** [comment]
I've just released version 1.2~beta7d. Please update to that version and give it a try. If the issue is still occurring. Please delete your database located at `/var/mobile/Library/Application Support/xyz.willy.zebra/zebra.db` and try opening Zebra again.

**Comment by drkey57** [comment]
Hello, I did the update but it does not install the old jet version update again
[cid:1E23E91A-0A25-4DEA-841E-9D8E3E18E473-L0-001]

Mr.Sc. Nuri Bahtijari

On Dec 31, 2020, at 04:42, Wilson Styres <notifications@github.com> wrote:

﻿

I've just released version 1.2~beta7d. Please update to that version and give it a try. If the issue is still occurring. Please delete your database located at /var/mobile/Library/Application Support/xyz.willy.zebra/zebra.db and try opening Zebra again.

**Comment by wstyres** [comment]
Please try removing the file located at `/var/mobile/Library/Application Support/xyz.willy.zebra/zebra.db` and reopening Zebra.

**Comment by drkey57** [comment]
Hello, I wanted to inform you that the zebra does not work well,todayin zebra refresh icon cache and to my surprise lost checkra1n icone how can i get it back

Mr.Sc. Nuri Bahtijari

On Jan 1, 2021, at 04:00, Wilson Styres <notifications@github.com> wrote:

﻿

Please try removing the file located at /var/mobile/Library/Application Support/xyz.willy.zebra/zebra.db and reopening Zebra.

**Comment by wstyres** [comment]
If database migration fails you can use "Clear Sources Cache" in Zebra's settings in order to reset it.
