### ISSUE TITLE
CTD and no new packages shown

### ISSUE THREAD

**Issue by rdc74656** [zbrateam/Zebra#1674]
**Describe the bug**

**Device Information:** 

 - iOS Version: <13.3
 - Zebra Version: 1.2beta7b
 - Device Type: iPhone
 - Jailbreak Type: Unc0ver

**Crash Log or System Log**

**Additional context**

**Comment by wstyres** [comment]
Please complete the entire issue template so that we can better understand your issue. We cannot resolve your issue unless you provide us with details.

**Comment by rdc74656** [comment]
What else can I provide? Installed list is empty changes tab doesn’t show any packages at all.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wstyres** [comment]
Please read the following note that was in the changelog:

<img width="1009" alt="Screen Shot 2020-12-24 at 5 29 22 PM" src="https://user-images.githubusercontent.com/19736790/103107567-ab74a680-460d-11eb-8ca6-8b8a2c4daf78.png">

**Comment by rdc74656** [comment]
That still doesn’t help and wasn’t an issue with the previous beta build.  In the picture is what I’m seeing on changes tab.  Upgrades still show under installed.  If there’s  anything I can do to correct this then please tell me.[Image.jpeg]

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
