### ISSUE TITLE
Installed Tab Sort order not saved 

### ISSUE THREAD

**Issue by respiredev** [zbrateam/Zebra#1675]
**Describe the bug**
_Installed_ tab does not remember sort order preference

**To Reproduce**
Set sort order preference. Kill Zebra. Go agane

**Expected behavior**
Remember which sort order was last selected.

**Screenshots**
no

**Device Information:** 

 - iOS Version: **13.5.1**
 - Zebra Version: **1.2-beta7c**
 - Device Type: **iPhone 8+**
 - Jailbreak Type: **odysseyra1n**

**Crash Log or System Log**
negative

**Additional context**
no thanks

**Comment by PoomSmart** [comment]
Fixed as of 4fe598d73fedb375c7a839591e60dc7c50a49066

**Comment by PoomSmart** [comment]
Fixed in beta~7d
