### ISSUE TITLE
Zebra does not respect user's display setting when opened

### ISSUE THREAD

**Issue by eve0415** [zbrateam/Zebra#1676]
**Describe the bug**
Zebra does not apply user settings when opening. It uses system appearance instead

**To Reproduce**
1. Turn off `Use System Appearance`
2. If you are using in black mode normally, switch to `light` and vice versa.
3. Close Zebra and re-open.
4. You see that Zebra does not respect user's setting.
5. Go to `Display` option and see the setting is perfectly fine but the appearance is not behaving as it is told to.

**Expected behavior**
Respect user's setting.

**Device Information:**
 - iOS Version: 13.5
 - Zebra Version: beta7c
 - Device Type: iPhone
 - Jailbreak Type: unc0ver

**Comment by PoomSmart** [comment]
Fixed in https://github.com/zbrateam/Zebra/pull/1690

**Comment by wstyres** [comment]
Resolved in 2.0 alpha.
