### ISSUE TITLE
Uicache not running properly

### ISSUE THREAD

**Issue by Oliverkiller** [zbrateam/Zebra#1678]
**Describe the bug**
uicache doesn't run most of the time after packages installation is done 

**To Reproduce**
 Open Zebra and try to install a package that installs an app with it 

**Expected behavior**
 The icon to appear in Home Screen after package is installed

**Screenshots**

**Device Information:** 

 - iOS Version: <iOS 14>
 - Zebra Version: <1.1.15>
 - Device Type: <iPhone 6s>
 - Jailbreak Type: < Odysseyra1n >

**Crash Log or System Log**

**Additional context**
 this issuse was also in 1.1.13

**Comment by wstyres** [comment]
This bug has been fixed in the 1.2 betas so I will close the issue.
