### ISSUE TITLE
Zebra crashes when going to the Sources tab

### ISSUE THREAD

**Issue by UNSCJohn-117** [zbrateam/Zebra#1679]
**Describe the bug**

Zebra crashes on the Sources page

**To Reproduce**

1. Open Zebra
2. Go to Sources

**Expected behavior**

I should see my repos

**Screenshots**

**Device Information:** 

 - iOS Version: 13.5.1
 - Zebra Version: 1.2 beta7c
 - Device Type: iPhone 7+
 - Jailbreak Type: Checkra1n

**Crash Log or System Log**

https://www.icloud.com/iclouddrive/0C2sACALa2lKSkEZU2KnAzDSw#text

**Additional context**

**Comment by eve0415** [comment]
Please remove `Zenumbra` and all other tweaks that related to Zebra before reporting.

**Comment by wstyres** [comment]
This issue is caused by Zenumbra, it is not updated for the latest beta version of Zebra just yet. I would suggest contacting the developer of Zenumbra for a fix.
