### ISSUE TITLE
https://getzbra.com/repo/

### ISSUE THREAD

**Issue by thnian0** [zbrateam/Zebra#1685]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by absidue** [comment]
Please stop spamming.
