### ISSUE TITLE
Tweak depiction won't load from Packix

### ISSUE THREAD

**Issue by yur1xpp** [zbrateam/Zebra#1695]
**Describe the bug**
Tweak depiction from Packix repo won't load in the latest beta. All other repo's depictions seems to load fine. Specifically, this issue seems to happens on the Packix package listed in "Installed" tab, and conditionally in "Search" tab. Refer the comment for more info: https://github.com/zbrateam/Zebra/issues/1695#issuecomment-752880542

**To Reproduce**
Open any tweak depiction from Packix.

**Expected behavior**
Load normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/34767893/103399680-27766d80-4b7d-11eb-8d4b-3177c1e43ebd.png)

**Device Information:** 

 - iOS Version: 13.5
 - Zebra Version: 1.2beta7d
 - Device Type: iPhone
 - Jailbreak Type: checkra1n

**Crash Log or System Log**
-

**Additional context**
-

**Comment by eve0415** [comment]
Cannot produce on my device
![image](https://user-images.githubusercontent.com/40632436/103400069-1894b880-4b87-11eb-9dc0-b1a65604a0a1.png)

**Comment by yur1xpp** [comment]
I did try to investigate more on it, and it seems when you open it through the "Installed" tab, this issue happens. And whenever you use the "Search" tab, it'll return two result, I suspect one is from the "Installed", another is from the repo itself (not sure how to word it). One of these will have this issue:

https://user-images.githubusercontent.com/34767893/103400612-b20c9c00-4b80-11eb-9bdd-6576820fa393.mov

**Comment by eve0415** [comment]
Yeah, you're right. It only happens only on `Package` tab and from Packix

**Comment by absidue** [comment]
it's not only packix and it affects the search tab as well.

**Comment by wstyres** [comment]
This is likely still related to #1667 and the depictions are missing for certain packages so they can never load.

**Comment by wstyres** [comment]
Going to close this in favor of #1667. I believe they're the same issue and when that issue is resolve we can revisit if this is a separate bug or not.
