### ISSUE TITLE
Icon swipe action style not respecting setting

### ISSUE THREAD

**Issue by CanerKaraca23** [zbrateam/Zebra#1699]
**Describe the bug**
Icon slide animations setting isn't working.

**To Reproduce**
Turn on icon slide animations, go to changes tab or installed tab then slide.

**Screenshots**
https://media.discordapp.net/attachments/572784833714192395/794447931356348438/video0.mp4

**Device Information:**

- iOS Version: iOS 12.5.1
 - Zebra Version: 1.2 beta9a
 - Device: iPhone 5s
 - Jailbreak Type: Chimera

**Comment by wstyres** [comment]
Are you referring to the swipe action style in settings?

**Comment by CanerKaraca23** [comment]
> Are you referring to the swipe action style in settings?

Yes, here the video:
https://media.discordapp.net/attachments/572784833714192395/794447931356348438/video0.mp4

**Comment by kirb** [comment]
Is this still happening for you with the latest version of Zebra?

**Comment by CanerKaraca23** [comment]
> Is this still happening for you with the latest version of Zebra?

I don't use iPhone anymore, my iPhone 5s is broken. I'm sorry. If you have any iOS 12 device, you can test.

**Comment by iAdam1n** [comment]
This appears to have been fixed.
