### ISSUE TITLE
No 'live' search in filtering author settings

### ISSUE THREAD

**Issue by eve0415** [zbrateam/Zebra#1701]
**Describe the bug**
Trying to search for author to filter out for not showing in changes tab, it doesn't live search. I have to press search to get search result every time.

**To Reproduce**
Type in something, wait and nothing happens
Press search to have a result

**Expected behavior**
Live search

**Device Information:**
 - iOS Version: 13.5
 - Zebra Version: beta7d
 - Device Type: iPhone
 - Jailbreak Type: unc0ver

**Comment by PoomSmart** [comment]
Fixed in https://github.com/zbrateam/Zebra/pull/1703
