### ISSUE TITLE
Bumpers don't work 

### ISSUE THREAD

**Issue by kaalq52** [zbrateam/Zebra#1708]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by kaalq52** [comment]
Ios14.2

**Comment by wstyres** [comment]
Please fill out the entire issue template when filing an issue. Without extra details and an explanation of the problem, we do not know what a "bumper" is or what the expected behavior is.
