### ISSUE TITLE
“Share Package” show empty sharing view

### ISSUE THREAD

**Issue by Ernest0-Production** [zbrateam/Zebra#1713]
![image](https://user-images.githubusercontent.com/19843524/104090175-c8ec7600-5285-11eb-830d-5013eedb84a9.png)

**Device Information:**
iPhone X, iOS 13.2.3, checkrain

 - Zebra Version: 1.2 beta 8

**Comment by showmak** [comment]
I have the same issue on iPhoen X iOS 14.3

**Comment by showmak** [comment]
Was this solved in beta9a? Because I have the same issue on my iPhone X and 2018 iPad Pro

**Comment by wstyres** [comment]
Hi! Thanks for your issue report. Unfortunately we do not support the 1.2 beta versions anymore and this issue will be closed. You can either downgrade to the latest stable version (1.1.18) or install the Zebra 2.0 Alpha and see if your issue still persists. If the issue does still persist, please file a new issue.
