### ISSUE TITLE
Zebra shows oldest version of Safari Plus as the latest

### ISSUE THREAD

**Issue by opa334** [zbrateam/Zebra#1719]
**Describe the bug**

The oldest version (1.6.6) of Safari Plus on my repo is shown as the latest version

**To Reproduce**

1. Add https://opa334.github.io
2. Uninstall Safari Plus if already installed
3. Navigate to the Safari Plus package
4. Tap "Get"
5. 1.6.6 is shown as the latest version

**Expected behavior**

Zebra should show the latest version (at this moment 1.7.14) as the latest version, just like Cydia does

**Screenshots**

![8BB71A28-55A4-46D7-9EF3-2646CFCF809F](https://user-images.githubusercontent.com/18235760/104124205-bd658180-534f-11eb-8de9-d7aaac4e233f.png)
![7AA5C165-EA32-470A-AC3A-F07E8B7D2734](https://user-images.githubusercontent.com/18235760/104124321-82b01900-5350-11eb-921a-53da91c68a0b.png)

**Device Information:** 

 - iOS Version: 13.7
 - Zebra Version: 1.2~beta8a
 - Device Type: iPhone
 - Jailbreak Type: checkra1n

**Comment by wstyres** [comment]
In the screenshot you showed of Zebra, there are 1.7 versions in that list if you scroll down. Can you scroll down and confirm if 1.7.14 is present? It looks like the version numbers are just sorted in ascending order instead of descending order.

**Comment by opa334** [comment]
yes, 1.7.14 is present when scrolling down

**Comment by opa334** [comment]
I somehow can't reproduce this on my XS on 13.5 with just my repo and bigboss added :/

**Comment by opa334** [comment]
fixed after pressing "reset all settings and sources", still weird tho (just resetting sources was not enough)
