### ISSUE TITLE
Error when installing package

### ISSUE THREAD

**Issue by NO111ONE** [zbrateam/Zebra#1727]
**Describe the bug**
Attempting to install a package makes an error: firmware(>7.0)

**To Reproduce**
1. Add repository: http://marie.lol/ios
2. Install package Sigma Chi iOS, using iOS 13.7 on iPhone 11

**Expected behavior**
Package installed - code injected into an app

**Screenshots**
 

https://cdn.discordapp.com/attachments/734423908345839700/800091518437425242/image0.png

**Device Information:** 

 - iOS Version: 13.7
 - Zebra Version: 
1.1.15 - Device Type: iPhone
 - Jailbreak Type: Odyssey

**Crash Log or System Log**
firmware(>7.0)
**Additional context**
N/A

**Comment by wstyres** [comment]
See the comments in #1061 for more about this issue. More specifically https://github.com/zbrateam/Zebra/issues/1061#issuecomment-612115297. I would suggest asking the repository maintainer to update their `Depends` field from `firmware (> 7.0)` to `firmware (>> 7.0)`.
