### ISSUE TITLE
Crashes like hell

### ISSUE THREAD

**Issue by OFLNT** [zbrateam/Zebra#1728]
**Describe the bug**
 when i go to the Sources section it crashes immediately also when i want to update tweaks too

**To Reproduce**

Couldn’t find out away
**Expected behavior**

As usual 
**Screenshots**

**Device Information:** 

 - iOS Version: <13.5>
 - Zebra Version: <1.2~beta8a>
 - Device Type: iPhone Xr <iPhone Xr>
 - Jailbreak Type: unc0ver <unc0ver >

**Crash Log or System Log**
 i dont have

**Additional context**
 please fix it and if wanted to contact thats my email : abod177r@gmail.com

**Comment by wstyres** [comment]
Please attach a crash log, without it we cannot resolve the issue.
