### ISSUE TITLE
Zebra doesn't load

### ISSUE THREAD

**Issue by OGslimeyBONEz** [zbrateam/Zebra#1729]
Zebra is retaining all my wish list items, but not showing them in my wish list. 
Also the application has failed to load the changelog

**Expected behavior**
For the app to load. Lol😂

**Device Information:** 

 - iOS Version: <IOS 13.5>
 - Zebra Version: <1.1.14>
 - Device Type: <iPhone XR>
 - Jailbreak Type: <unc0ver>

**Crash Log or System Log**

**Additional context**

**Comment by wstyres** [comment]
Could you provide more information about this issue? It isn't clear what is happening based on your descriptions.

**Comment by bwall3r** [comment]
I am currently having a similar issue and will try to provide detail that pertains to this.
- when i go to wish list on the home tab no items appear in the list.
- if i go to the sources tab and go into a source and look through the available tweaks any tweaks that were in my wish list have a little star beside their name.
- going to the tweak page and clicking the 3 dots gives me the option to it gives me the option to remove from wish list.
- playing around with that option does nothing, refreshing the sources removes the star or adds it back depending on whether i asked to remove or add to wish list.

I have removed the zebra.db file a couple of times and relaunched as i thought i was having issues with the stores on the home page only to see under the issues that it is going to be changed.
