### ISSUE TITLE
Zebra will often crash when refreshing or searching

### ISSUE THREAD

**Issue by altereo** [zbrateam/Zebra#1731]
**Describe the bug**
Upon refreshing or attempting to search for a tweak, Zebra will sometimes crash. This usually does not create a crash report in Cr4shed, though sometimes it will.

**To Reproduce**
Attempt to refresh sources/search for a tweak.

**Expected behavior**
The sources should finish refreshing and the changes should be shown under the changes tab.

**Device Information:** 

 - iOS Version: 14.3
 - Zebra Version: 1.2~beta8a
 - Device Type: iPhone
 - Jailbreak Type: checkra1n

**Crash Log or System Log**
[https://pastebin.com/60xXgiX4](https://pastebin.com/60xXgiX4)
Note: As the crash log isn't always generated, this may be the result of a different issue all together.

**Additional context**
Currently I have about ~60 sources in Zebra. The problem existed in the past, but suddenly got significantly more frequent. I have tried disabling tweak injection, with no change in behaviour.

**Comment by PoomSmart** [comment]
Crash highlight:
```
Exception type: NSInternalInconsistencyException
Reason: attempt to delete row 0 from section 0 which only contains 0 rows before the update
```

**Comment by wstyres** [comment]
Hi! Thanks for your issue report. Unfortunately we do not support the 1.2 beta versions anymore and this issue will be closed. You can either downgrade to the latest stable version (1.1.18) or install the Zebra 2.0 Alpha and see if your issue still persists. If the issue does still persist, please file a new issue.
