### ISSUE TITLE
“No Storefronts found”, crashing

### ISSUE THREAD

**Issue by gerbil-snot** [zbrateam/Zebra#1732]
**Describe the bug**
 When trying to access the Stores section, the page only says "No Storefronts found" sources load fine. When attempting to swipe to upgrade on tweaks from missing storefronts, the app crashes

**To Reproduce**
 Open Stores section, see error. Swipe to upgrade on a tweak on the Installed tab, app crashes. 

**Expected behavior**
 Store fronts should appear and be accessible to sign in. App should not crash when attempting to upgrade.

**Screenshots**

![image](https://user-images.githubusercontent.com/29874563/105641037-8b701700-5e47-11eb-91ca-30128d4944ef.gif)

**Device Information:** 
 - iOS Version: 13.5
 - Zebra Version: 1.2~beta8a
 - Device Type: iPhone Xs Max
 - Jailbreak Type: unc0ver

**Crash Log or System Log**
 https://pastebin.com/AJcVjqd5

**Additional context**
 None

**Comment by wstyres** [comment]
The stores tab is not meant to exist anymore and will be removed in an upcoming beta. The replacement for it is going to the sources tab and using filters to select stores.

**Comment by gerbil-snot** [comment]
What about updating tweaks and such? Is there a fix? Currently Zebra is unusable. I can install or update anything.
