### ISSUE TITLE
No Storefronts Available

### ISSUE THREAD

**Issue by xxiivv1** [zbrateam/Zebra#1734]
**Describe the bug**
Stores don't show up in the stores tab, tried clearing store cache multiple times

**To Reproduce**
Add packix or dynastic, go to stores, clear cache, go to stores again

**Expected behavior**
Show stores and purchased items

**Device Information:** 

 - iOS Version: 13.5
 - Zebra Version: Latest(1.2 beta 8a)
 - Device Type: iPhone XS Max
 - Jailbreak Type: Odyssey
 
 Additional information:
I tried downgrading to version 1.1.14 but stores would say I didn't purchased anything

**Comment by wstyres** [comment]
The stores tab is not meant to exist anymore and will be removed in an upcoming beta. The replacement for it is going to the sources tab and using filters to select stores.
