### ISSUE TITLE
Crash upon launch (nanov2_allocate_from_block)

### ISSUE THREAD

**Issue by SlightlyPeckish** [zbrateam/Zebra#1735]
**Describe the bug**
App crashes upon launch

**To Reproduce**
It happens every time I open it I don’t know why

**Expected behavior**
Open the app it loads for a couple seconds then closes 

**Screenshots**

**Device Information:** 

 - iOS Version: 13.5
 - Zebra Version: 1.2~beta8a
 - Device Type: iPhone XR 
 - Jailbreak Type: unc0ver 

**Crash Log or System Log**
https://pastebin.com/a8Tepugt

**Additional context**

**Comment by wstyres** [comment]
Hi! Thanks for your issue report. Unfortunately we do not support the 1.2 beta versions anymore and this issue will be closed. You can either downgrade to the latest stable version (1.1.18) or install the Zebra 2.0 Alpha and see if your issue still persists. If the issue does still persist, please file a new issue.
