### ISSUE TITLE
Please 

### ISSUE THREAD

**Issue by crazy6m** [zbrateam/Zebra#1737]
All resources are without packages and the change list is empty?  xs max ios13.5 jailbreak unc0ver.
![7EE26B89-7002-4590-BC49-7FD87AFDDE1E](https://user-images.githubusercontent.com/74124648/106011647-b9658d80-60cb-11eb-8150-adf7d30067ad.png)
![369DF6F5-CA52-4F6B-B2A4-949340A4C9CD](https://user-images.githubusercontent.com/74124648/106011660-bcf91480-60cb-11eb-863e-1250f8115f7b.png)
![387C12B3-0F93-493A-B344-84FA497A2417](https://user-images.githubusercontent.com/74124648/106011672-bec2d800-60cb-11eb-8161-da5015cfde1d.png)

**Comment by wstyres** [comment]
Please try resetting your source cache in Zebra's settings and filing a proper bug report if the issue continues.
