### ISSUE TITLE
Accounts don't reflect purchased Items..?

### ISSUE THREAD

**Issue by souporshawn** [zbrateam/Zebra#1740]
**Describe the bug**

Not much to explain here, Accounts that support login (Packix, Twixed, Etc), although I can successfully login, it just doesn’t reflect purchased Items..?
**To Reproduce**

![297C3B64-4BA8-4ACD-88A0-7D93D3C49A4B](https://user-images.githubusercontent.com/17053827/106364236-d4621880-62ea-11eb-8e21-73231618ae04.jpeg)
![70782BF7-9525-4069-A91D-57412AB5910E](https://user-images.githubusercontent.com/17053827/106364237-d6c47280-62ea-11eb-8208-3c5c8f1d73b4.jpeg)
![85850E0E-EBBD-43A1-B313-E50F68F0C855](https://user-images.githubusercontent.com/17053827/106364239-d75d0900-62ea-11eb-832d-e19c5769792b.jpeg)

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by wstyres** [comment]
This is a known issue and has already been resolved. It will be fixed in an upcoming beta.
