### ISSUE TITLE
Donot open files.deb

### ISSUE THREAD

**Issue by drmody1** [zbrateam/Zebra#1747]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by progamer562** [comment]
you need to fix this otherwise we cant help you its all blank
