### ISSUE TITLE
No Packages displayed after reinstall

### ISSUE THREAD

**Issue by Ryutso** [zbrateam/Zebra#1750]
**Describe the bug**
No Packages or Changes shown despite repos being listed.

**To Reproduce**
1. Uninstall Zebra
2. Reinstall Zebra
3. Go to “Changes” or “Packages”

**Expected behavior**
I should see a list of packages available to install or packages I have installed
**Device Information:** 

 - iOS Version:
 13.5
 - Zebra Version: 
 1.1.5
 - Device Type: iPhone XS Max
 - Jailbreak Type: unc0ver
 

**Screenshots**
![07F9C389-6285-49BE-AE07-F4DAD6D1CD4E](https://user-images.githubusercontent.com/57740896/108641046-1d7d3680-746b-11eb-8a90-ec10809d4968.png)
![3C83CB41-9CE0-4E52-ABAE-67FC29BF98CB](https://user-images.githubusercontent.com/57740896/108641048-20782700-746b-11eb-817c-6c39b52ff7d8.png)
![76DD897F-A06B-4F52-81B0-20DD92DDD367](https://user-images.githubusercontent.com/57740896/108641049-2110bd80-746b-11eb-9c7a-22fa5b65fbd9.png)

**Additional context**
Zebra wasn’t able to “find a URL” for any tweaks I wanted to update despite me having an internet connection and being able to see the depiction, so I deleted Zebra and redownloaded it through Cydia. The new install exhibits the problem.

**Comment by Deja-Wu** [comment]
Have you tried resetting the “Sources cache” under Zebras settings? This redownloads the package list for all of your added sources.
