### ISSUE TITLE
installed packages appear twice in favorites section

### ISSUE THREAD

**Issue by NotVeryGood** [zbrateam/Zebra#1754]
**Describe the bug**
installed packages appear twice in a row in the favorites section. 

**To Reproduce**
simply install a package in your favorites section and respring. alternatively, you can install a package and add it to your favorites after and the bug will still occur.

**Expected behavior**
it should show once.

**Screenshots**
![9597A431-783F-46E9-9438-1CA2BABACFFE](https://user-images.githubusercontent.com/18710116/109335199-96d3ab00-7816-11eb-845f-bcf6c7607ec5.png)

**Device Information:**

 - iOS Version: 13.5
 - Zebra Version: 1.2~beta9a
 - Device Type: iPhone SE 2020/Gen 2
 - Jailbreak Type: unc0ver v5.3.1

**Crash Log or System Log**
N/A

**Additional context**
interestingly, adding the "UIKit Tools" package to my favorites added it THREE times in a row while adding the "Essential" package did not trigger the bug (both packages were already installed ofc). possibly something to do with packages on multiple sources?

**Comment by wstyres** [comment]
Hi! Thanks for your issue report. Unfortunately we do not support the 1.2 beta versions anymore and this issue will be closed. You can either downgrade to the latest stable version (1.1.18) or install the Zebra 2.0 Alpha and see if your issue still persists. If the issue does still persist, please file a new issue.
