### ISSUE TITLE
iOS 14.2 iPhone 12 pro max crashing/tweaks not installing after clicking respring

### ISSUE THREAD

**Issue by thelazyitguy** [zbrateam/Zebra#1755]
**Describe the bug**

App crashes while switching between tabs at bottom. Doesn't happen all the time. Also crashes if I go into a repo from sources/my account/tweak/ click install.
**To Reproduce**

Start moving between tabs. 
**Expected behavior**

Not to crash
**Screenshots**

**Device Information:** 

 - iOS Version: iOS 14.2
 - Zebra Version: Zebra 1.2 beta9a
 - Device Type: <INSERT-HERE> iPhone 12 Pro Max
 - Jailbreak Type: unc0ver

**Crash Log or System Log**
 can't get a crash log as none of the crash reporter apps are currently working on iOS 14.2 A14

**Additional context**

**Comment by wstyres** [comment]
Hi! Thanks for your issue report. Unfortunately we do not support the 1.2 beta versions anymore and this issue will be closed. You can either downgrade to the latest stable version (1.1.18) or install the Zebra 2.0 Alpha and see if your issue still persists. If the issue does still persist, please file a new issue.
