### ISSUE TITLE
Zebra Beta - Crash when opening invalid repos

### ISSUE THREAD

**Issue by DumbGameMaker** [zbrateam/Zebra#1757]
**Describe the bug**

When trying to open an invalid repository (one that cannot be opened because a file is missing or something), instead of throwing an error, zebra just crashes.

**To Reproduce**

1) find a broken repository (bigboss for me)
2) try to open it (only works if the repo was previously added)
3) crash

**Expected behavior**

Zebra should throw an error in the form of a banner or popup

**Screenshots**

**Device Information:** 

 - iOS Version: 14.3
 - Zebra Version: 1.2~beta9a
 - Device Type: iPhone XR
 - Jailbreak Type: Unc0ver 6.0.1

**Crash Log or System Log**

**Additional context**

bigboss doesn't work on my phone for some reason

**Comment by PoomSmart** [comment]
Will be fixed in https://github.com/zbrateam/Zebra/pull/1758
