### ISSUE TITLE
Apps don’t show up when removing other apps

### ISSUE THREAD

**Issue by nab138** [zbrateam/Zebra#1759]
**Bug description**
When uninstalling an app and installing another app the app you are trying to install does not appear.

**To Reproduce**
Install any app from zebra. Then tap remove but do not confirm. Choose a different app. Hit install and confirm to remove the the app and install the other one. The new app will not appear until it is reinstalled.

**Expected behavior**
The first app should’ve been removed (which it was) and the second app should have appeared on the Home Screen
**Device Information:** 

 - iOS Version: 14.4
 - Zebra Version: 1.1.15
 - Device Type: IPhone SE (first gen)
 - Jailbreak Type: checkra1n

**Additional context**
 tried it with a few different apps so it is not an app specific problem. Problem not reproducible in cydia. Works when I remove the app then install the new one in separate operations.

**Comment by wstyres** [comment]
Resolved in 2.0 alpha.
