### ISSUE TITLE
Add a feature to show repos that are down

### ISSUE THREAD

**Issue by thekio1984** [zbrateam/Zebra#1764]
Probably not the place, but some kind of indicator to show which repo isnt loading, like cydia's spinner, sometimes i have updates that wont show because other repos are timing out or are just down & i cant even temporarily remove that repo as it doesnt show or say what repo is down, it just stays refreshing. Something like a '!' on the downed repo rather than sitting there for ages waiting for it to never update (well until downed repo is back up lol)

**Comment by RPwnage** [comment]
You mean like a small read "!" or some other indicator badge, showing that the repo endpoint is unreachable?

**Comment by thekio1984** [comment]
Yhyh, something exactly like that, currently theres no way to tell what repo is timing out until it finishes refreshing, which can sometimes take a while, if repos had indicators, if/when a repo is down, the user could just remove that repo temporarily so that using other repos wont take as long to refresh, i used to do it all the time with cydia, id just look to see what repo had the spinner (ie the repo with issues), delete then re-add it when back up....

like if a repo takes longer that 30 seconds to refresh, it gets marked "!" or anything else, just some kinda indicator to say hey, this might not be right...👍

**Comment by RPwnage** [comment]
I'll try to work this out!

**Comment by thekio1984** [comment]
Thanks 🙏

**Comment by wstyres** [comment]
Resolved in 2.0 alpha.
