### ISSUE TITLE
Zebra 1.2~beta9a crashes on iPad7,3 when tapping “Update All” button

### ISSUE THREAD

**Issue by hero3210** [zbrateam/Zebra#1765]
**Describe the bug**

Zebra 1.2~beta9a crashes on iPad7,3 when tapping “Update All” button

**To Reproduce**

- Install Zebra 1.2~beta9a on iPad7.3 (maybe other devices also) on iOS 13.3
- go to “Packages” tab
- tap “Update All” on the top (if you have package updates)
- zebra will crash

**Expected behavior**

Zebra should not crash
The queue screen should pop up

**Screenshots**

**Device Information:** 

 - iOS Version: <iOS 13.3>
 - Zebra Version: <1.2\~beta9a>
 - Device Type: <iPad7,3>
 - Jailbreak Type: <Odyssey>

**Crash Log or System Log**

[Zebra update all crash.txt](https://github.com/zbrateam/Zebra/files/6115826/Zebra.update.all.crash.txt)

**Additional context**

**Comment by wstyres** [comment]
Hi! Thanks for your issue report. Unfortunately we do not support the 1.2 beta versions anymore and this issue will be closed. You can either downgrade to the latest stable version (1.1.18) or install the Zebra 2.0 Alpha and see if your issue still persists. If the issue does still persist, please file a new issue.
