### ISSUE TITLE
Jail break crash 

### ISSUE THREAD

**Issue by jarlols** [zbrateam/Zebra#1766]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by absidue** [comment]
Please report jailbreak crashes to the jailbreak developers directly, they won't see it here.
