### ISSUE TITLE
Packages don’t show on zebra.

### ISSUE THREAD

**Issue by maysiki** [zbrateam/Zebra#1769]
**Describe the bug**
Packages do not show on either Changes or Packages after Jailbreaking with Unc0ver.

**To Reproduce**
Jailbreak with unc0ver on 14.3.
Install Zebra 1.1.15.
Open Zebra.

**Expected behavior**
Be able to see packages.

**Screenshots**
![D09C593A-D107-4E57-A7EB-7AEC5A75A845](https://user-images.githubusercontent.com/57982669/110936677-527dfa00-8342-11eb-93e3-fbe21c6f2e22.png)
![2BD6C85F-BD5D-4519-B6E4-9EF05A00AB94](https://user-images.githubusercontent.com/57982669/110936680-53af2700-8342-11eb-9ad6-c70dac2700a2.png)

**Device Information:** 

 - iOS Version: <14.3>
 - Zebra Version: <1.1.15>
 - Device Type: <iPhone 11 Pro Max>
 - Jailbreak Type: <unc0ver>

**Crash Log or System Log**
N/A

**Additional context**
I do not have any tweaks installed apart from Filza and Batchomatic.

**Comment by kurt1277** [comment]
Having same issue. Cannot find a way to fix. Reinstalled, removed and also used iCleaner then installed again. No luck.

**Comment by wstyres** [comment]
Resolved in 2.0 alpha.
