### ISSUE TITLE
Incorrect message when installing a .deb that conflicts with an installed package

### ISSUE THREAD

**Issue by nyuszika7h** [zbrateam/Zebra#1779]
**Describe the bug**
When installing a `.deb` that conflicts with an already installed package, the error message that's shown is incorrect.

**To Reproduce**
1. Install `com.example.package1` (either from a repo or a `.deb`)
2. Install `com.example.package2`, which has `Conflicts: com.example.package2`, from a `.deb`

**Expected behavior**
It should say: "package1 must be removed because it conflicts with package2".

**Actual behavior**
It says: "package1 must be removed because it depends on package2" (which is false).

**Screenshots**
![Screenshot](https://femto.pw/5zwi)

**Device Information:** 

 - iOS Version: 14.3
 - Zebra Version: 1.1.15
 - Device Type: iPhone X
 - Jailbreak Type: unc0ver

**Comment by wstyres** [comment]
Resolved in 2.0 alpha.
