### ISSUE TITLE
Maintainer field in packages is ignored

### ISSUE THREAD

**Issue by nyuszika7h** [zbrateam/Zebra#1780]
**Describe the bug**
Zebra ignores the `Maintainer` field in packages, and only uses `Author`, even if the latter is missing.

`Author` is not a required field, in fact it is a nonstandard field introduced by Cydia. It is not listed in the [`deb-control` manpage](https://manpages.debian.org/testing/dpkg-dev/deb-control.5.en.html).

**To Reproduce**

**Expected behavior**
Zebra should show the `Maintainer` field if the `Author` field is missing. In fact, `Maintainer` should probably be always prioritized if present, as generally users should be bothering the person who packaged the software for iOS rather than the person who originally made it, if they're different, as the issue they're encountering may be iOS-specific. Perhaps show the maintainer first, and then the author below (if different from maintainer).

**Screenshots**
With Maintainer field:
![Screenshot 1](https://femto.pw/hgwr)

With Maintainer and Author field (shows the latter and ignores the former, even if different):
![Screenshot 2](https://femto.pw/yrax)

**Device Information:** 

 - iOS Version: 14.3
 - Zebra Version: 1.1.15
 - Device Type: iPhone X
 - Jailbreak Type: unc0ver

**Comment by wstyres** [comment]
Resolved in 2.0 alpha.
