### ISSUE TITLE
Twickd Repo doesn’t show in the Store section 

### ISSUE THREAD

**Issue by iB1QeR** [zbrateam/Zebra#1781]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by iB1QeR** [comment]
I can’t login to Twickd Repo to download my Paid Packages

**Comment by RPwnage** [comment]
Because the repo was down. Nothing zebra related.

**Comment by iB1QeR** [comment]
> Because the repo was down. Nothing zebra related.

I checked after the Repo is back up I removed the Repo when it was down
