### ISSUE TITLE
Wrong depiction shown for some tweaks

### ISSUE THREAD

**Issue by AmazingELF74** [zbrateam/Zebra#1784]
**Describe the bug**
Wrong depiction loads for tweaks until reload off app. Problem persists when backing out of tweak depiction, coming back whoever that tweak is next selected anywhere.

**To Reproduce**
Select a tweak from the search menu

**Expected behavior**
The tweak’s depiction should pod below the title

**Screenshots**
![E1DBCB85-C7C0-467D-A7BE-14D45116E91E](https://user-images.githubusercontent.com/22646730/112702658-9f95bc00-8e6a-11eb-8dd5-997cf0864ed4.png)

**Device Information:** 

 - iOS Version: <14.3RC1>
 - Zebra Version: <1.2~beta9a>
 - Device Type: <iPhone>
 - Jailbreak Type: <unc0ver>

**Crash Log or System Log**
None Available

**Additional context**
This does not happen frequently but persists whenever it does

**Comment by wstyres** [comment]
Hi! Thanks for your issue report. Unfortunately we do not support the 1.2 beta versions anymore and this issue will be closed. You can either downgrade to the latest stable version (1.1.18) or install the Zebra 2.0 Alpha and see if your issue still persists. If the issue does still persist, please file a new issue.
