### ISSUE TITLE
Batchomatic Incompatibility since v1.1.10

### ISSUE THREAD

**Issue by harshsingh7** [zbrateam/Zebra#1785]
**Describe the bug**
Tweak Batchomatic (used to back/restore tweaks and Settings) doesn’t work after version 1.1.10 of Zebra

**To Reproduce**
Have Batchomatic installed and downgrade Zebra to version < 1.1.10 and works as expected but after updating, the “steering wheel “ doesn’t show up

**Expected behavior**
When In the search tab, a “Steering wheel” should show up near the Title which opens up all Batchomatic options

**Device Information:**
 - iOS Version: 14.1
 - Zebra Version: 1.1.15
 - Device Type: iPhone 12 Pro Max
 - Jailbreak Type: unc0ver

**Additional context**
Tried contacting the developer for Batchomatic, said it’s something wrong with Zebra itself

**Comment by absidue** [comment]
Please ask the batchomatic developers to upgrade the tweak.

Personally I would not use batchomatic, as you should really be installing your packages, especially your tweaks, one by one or in small groups so you can check which ones work on your iOS version and jailbreak.
