### ISSUE TITLE
there’s only bigboss tweaks in changes section.

### ISSUE THREAD

**Issue by KurdishBoy93** [zbrateam/Zebra#1793]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by DumbGameMaker** [comment]
Please fill out the template. On 3/29, there were a lot of updates to bigboss tweaks. However, when I scroll down there are updates to Twickd and Dynastic as well. Also, at the top there are packix updates; you might not have seen them as they were made after you reported this issue.

**Comment by absidue** [comment]
@KurdishBoy93 can you please check if this is still happening?
