### ISSUE TITLE
Zebra either shows minimal, duplicate, or tweaks that aren’t even installed

### ISSUE THREAD

**Issue by sturdycactus** [zbrateam/Zebra#1795]
**Describe the bug**
 Upon opening zebra today, initially the installed list showed a massive list of tweaks that show as installed, but would not remove nor would they show in Cydia. I rebooted and re-jailbroke and then Zebra showed only 5-6 tweaks. Then I refreshed a couple times, and it seems to have the complete tweak list, but everything is duplicated in the list 5+ times per tweak. Also, the “featured” banner that is normally within the app does not show

**To Reproduce**
 Open zebra, see the issue? I can send a video or screenshot if needed

**Expected behavior**
 For now I will use Cydia until I see zebra is working normally

**Screenshots**

**Device Information:** 

 - iOS Version: <14.0.1>
 - Zebra Version: <Within app, cannot check at this time>
 - Device Type: <iPhone 11>
 - Jailbreak Type: unc0ver

**Crash Log or System Log**

**Additional context**

**Comment by wstyres** [comment]
Resolved in 2.0 beta

**Comment by sturdycactus** [comment]
What repo is this on? getzbra.com/repo/ shows 1.1.18 as the latest

Or download directly from GitHub and install with Filza?
