### ISSUE TITLE
Errors while installing packages

### ISSUE THREAD

**Issue by rctfan929** [zbrateam/Zebra#1802]
I get the errors in the screenshot below while trying to install tweaks.

Screenshots
![A46399D2-D97A-4DB0-9586-61215F1237AD](https://user-images.githubusercontent.com/46878212/114126765-0f726080-98c7-11eb-9a5a-a66efbd57018.png)

Device Information:
 - iOS Version: 14.2
 - Zebra Version: 1.2~beta9a
 - Device Type: iPhone 12 mini
 - Jailbreak Type: Taurine 1.0.2

**Comment by wstyres** [comment]
Hi! Thanks for your issue report. Unfortunately we do not support the 1.2 beta versions anymore and this issue will be closed. You can either downgrade to the latest stable version (1.1.18) or install the Zebra 2.0 Alpha and see if your issue still persists. If the issue does still persist, please file a new issue.
