### ISSUE TITLE
No tweaks in repos

### ISSUE THREAD

**Issue by bajastar** [zbrateam/Zebra#1810]
**Describe the bug**

All repos has cero tweaks same in stores where I bay tweaks
**To Reproduce**

Install zebra from cydia or installer an imports all repos but de repos don't have any tweaks
**Expected behavior**

See any tweak
**Screenshots**

![image](https://user-images.githubusercontent.com/56235564/114593524-6b334580-9c49-11eb-95ab-b00e3a429c93.png)

![image](https://user-images.githubusercontent.com/56235564/114593437-58b90c00-9c49-11eb-9aca-54a98d74de6f.png)
![Cargando 114593547...]
**Device Information:** 

 - iOS Version: <14.3>
 - Zebra Version: <1.1.1.15>
 - Device Type: <iPhone XR 32GB>
 - Jailbreak Type: unc0ver

**Crash Log or System Log**

**Additional context**

**Comment by wstyres** [comment]
Resolved in the 2.0 alpha.
