### ISSUE TITLE
Procursus Apt v2.3.1 - Repository is broken: Package has no size information

### ISSUE THREAD

**Issue by tateu** [zbrateam/Zebra#1812]
iPhone XSMax, iOS 14.3, Taurine v1.03

An update to Apt v2.3.1, libapt-pkg6.0 v2.3.1 and dpkg v1.20.9 on 2021-04-14 has broken Package reinstall in Zebra. Package reinstall still works in Sileo.

Upon reinstall, the package downloads but then there is an error while installing that says:

Repository is broken: Package X has no size information.

Downloading back to Apt v2.3.0, libapt-pkg6.0 v2.3.0 and dpkg v1.20.7.1 fixes the issue

**Comment by wstyres** [comment]
Do you know which repository and pakeha ethics error is coming from? Would be helpful in tracking down the issue.

**Comment by tateu** [comment]
All repositories, all packages. I've tried BigBoss -> AppList, Odyssey Repo -> libhooker Configurator, Chariz -> NewTerm2, etc.

Yes, it is definitely from the 2.3.1 apt update.

**Comment by wstyres** [comment]
Fixed in f0b4bfc. Will be released in 1.1.18 in a few moments and I'll push a fix for the beta soon.

**Comment by wstyres** [comment]
Should be fixed in 1.1.18 now.

**Comment by tateu** [comment]
Confirmed. Working correctly in 1.1.18. Thanks for the quick fix.
