### ISSUE TITLE
Not queuing deb from external source

### ISSUE THREAD

**Issue by rdc74656** [zbrateam/Zebra#1816]
**Describe the bug**
Zebra is not adding a deb file that has been selected externally and asked to “open in zebra”. Zebra does open but does not add the package to queue to be installed.

**To Reproduce**
Download a deb eg from discord, save to Filza (optional) then select to open in zebra.

**Expected behavior**
Package to be added to zebra queue or at least show package depiction to then be able to add to queue.

**Screenshots**

**Device Information:** 
 - iOS Version:  14.3
 - Zebra Version: 1.2 beta 9a
 - Device Type:iPhone 11 pro
 - Jailbreak Type:unc0ver

**Crash Log or System Log**
N/A

**Additional context**
N/A

**Comment by wstyres** [comment]
Hi! Thanks for your issue report. Unfortunately we do not support the 1.2 beta versions anymore and this issue will be closed. You can either downgrade to the latest stable version (1.1.18) or install the Zebra 2.0 Alpha and see if your issue still persists. If the issue does still persist, please file a new issue.
