### ISSUE TITLE
Zebra crashing when refreshing sources

### ISSUE THREAD

**Issue by twiebie** [zbrateam/Zebra#1819]
When I Open Zebra and change the tab (while refreshing sources), Zebra crashes.

**Comment by wstyres** [comment]
Hi! Thanks for your issue report. Unfortunately we do not support the 1.2 beta versions anymore and this issue will be closed. You can either downgrade to the latest stable version (1.1.18) or install the Zebra 2.0 Alpha and see if your issue still persists. If the issue does still persist, please file a new issue.
