### ISSUE TITLE
Search not working proper 

### ISSUE THREAD

**Issue by twiebie** [zbrateam/Zebra#1820]
When I execute a search, sometimes no or not all results are shown.
Selecting the search textbox and executing the search again, will Return More/different results.

Attached screenshots are describing the issue.
No sources were changed and the repos were updated just befor.

![1DEFF604-7BF8-43C0-8239-E26ABB8FD63F](https://user-images.githubusercontent.com/57875728/115577530-cc4fbe80-a2c4-11eb-9e8b-cd3504bf4582.png)
![BB7C4D10-7B84-4196-BD2D-F72C6DBC2FC1](https://user-images.githubusercontent.com/57875728/115577543-ceb21880-a2c4-11eb-97eb-ca38c6c1f727.png)

**Comment by wstyres** [comment]
Hi! Thanks for your issue report. Unfortunately we do not support the 1.2 beta versions anymore and this issue will be closed. You can either downgrade to the latest stable version (1.1.18) or install the Zebra 2.0 Alpha and see if your issue still persists. If the issue does still persist, please file a new issue.
