### ISSUE TITLE
Version sorting not working properly

### ISSUE THREAD

**Issue by Xpl0itU** [zbrateam/Zebra#1821]
**Describe the bug**
When installing a package with multiple versions available, zebra will always show the earliest version as the latest

**To Reproduce**
Go to a package with multiple versions
Click on get

**Expected behavior**
The latest package gets shown as the latest

**Screenshots**
![8002F6B1-1A8C-4287-8FCE-AECEADEF4E38](https://user-images.githubusercontent.com/24777100/115722317-2a40dc80-a37f-11eb-9eb0-11e5e4c94799.png)

**Device Information:**
 - iOS Version: 14.3
 - Zebra Version: 1.2~beta9a
 - Device Type: iPhone
 - Jailbreak Type: Taurine

**Crash Log or System Log**

**Additional context**
I also expect the version selection screen to sort from newest to oldest, not the other way around, like it does now

**Comment by wstyres** [comment]
Hi! Thanks for your issue report. Unfortunately we do not support the 1.2 beta versions anymore and this issue will be closed. You can either downgrade to the latest stable version (1.1.18) or install the Zebra 2.0 Alpha and see if your issue still persists. If the issue does still persist, please file a new issue.
