### ISSUE TITLE
Dependencies issues with substitute 

### ISSUE THREAD

**Issue by Oliverkiller** [zbrateam/Zebra#1822]
**Describe the bug**

When u queue substitute it queues Cydia Substrate as a dependency but if installed from another store updating it doesn’t affect anything 
**To Reproduce**

Try to queue Substitute 
**Expected behavior**

Only to queue safe mode as a dependency 
**Screenshots**

https://ibb.co/fSMjdTb

**Device Information:** 

 - iOS Version: <14.4.1>
 - Zebra Version: <1.1.18>
 - Device Type: <iPhone 6s>
 - Jailbreak Type: < Checkra1n >

**Crash Log or System Log**

**Additional context**

**Comment by Oliverkiller** [comment]
Edit: The jailbreak type didn’t show up so I updated it to show

**Comment by wstyres** [comment]
If you are running checkra1n is substitute supposed to be installed? I was under the impression that substrate was to be used on checkra1n instead of substitute but I could be wrong.

**Comment by Oliverkiller** [comment]
> If you are running checkra1n is substitute supposed to be installed? I was under the impression that substrate was to be used on checkra1n instead of substitute but I could be wrong.

Installing Either substitute or substrate is optional but I prefer substitute as it’s faster but yes substrate is the one mainly used with Checkra1n

**Comment by Oliverkiller** [comment]
Oh nice
