### ISSUE TITLE
ple change my repo 

### ISSUE THREAD

**Issue by dajibaxiao** [zbrateam/Zebra#1836]
Please change zebra repo list 
Delete old repo http://geekpwn.asuscomm.com:8848/repo

Add new repo http://geekpwn.F3322.net:8848/repo/

thanks developer
![367F62FD-401D-4A2E-99CD-95B514905659](https://user-images.githubusercontent.com/2666997/119034928-9431bd80-b9e1-11eb-8e0e-4624f974041f.png)

**Comment by absidue** [comment]
Hey @dajibaxiao,

That list is **not** part Zebra, it looks like something added by the CyDown tweak, please contact the developer of the tweak instead, as we have no control over the tweak and that list.

**Comment by dajibaxiao** [comment]
> Hey @dajibaxiao,
> 
> That list is **not** included in the official Zebra distributions, it looks like something added by the CyDown tweak, please contact the developer of the tweak instead, as we have no control over the tweak or the list.

Thank you for your contribution to jailbreak,i got it.
