### ISSUE TITLE
Error occurred 

### ISSUE THREAD

**Issue by Dizzle9** [zbrateam/Zebra#1837]
![image](https://user-images.githubusercontent.com/77421942/119106475-656d1480-b9ec-11eb-83c1-ae6c47ec1c65.jpg)
**Describe the bug**
 not sure get thale attached error message when start up

**To Reproduce**

I can’t find the file sorry bit new to jailbreaking
**Expected behavior**
 just figured you’d like the report as I’m sure others have met same issues 

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE> 14.6
 - Zebra Version: <INSERT-HERE>I 1.1.18
 - Device Type: <INSERT-HERE>iPhone 6s
 - Jailbreak Type: <INSERT-HERE> Checkra1n 

**Crash Log or System Log**

**Additional context**

**Comment by wstyres** [comment]
Please reinstall Zebra. If this does not resolve your issue then please verify the permissions of the file located at `/usr/libexec/zebra/supersling` and make sure they are set to 6755.
