### ISSUE TITLE
Lag when scrolling through sources list

### ISSUE THREAD

**Issue by cydia4kurd** [zbrateam/Zebra#1840]
**Describe the bug** scrolls lagging in source section

**Screenshots**

https://user-images.githubusercontent.com/69204257/119495651-4b745e80-bd6b-11eb-8d09-ceb42e6ee458.MOV

**Device Information:**
 - iOS Version: 14.4 
 - Zebra Version: 1.1.18
 - Device Type: iphone x global
 - Jailbreak Type: checkra1n

**Comment by wstyres** [comment]
This looks like it could be a tweak issue rather than a Zebra one. Could you remove any tweaks from Zebra and try again?

**Comment by Kyogre** [comment]
I saw that this bug appears if you enabled "Count Source Packages" option in Cydown tweak.
