### ISSUE TITLE
Interface style related crashes

### ISSUE THREAD

**Issue by CanerKaraca23** [zbrateam/Zebra#1845]
**Describe the bug**

Zebra Alpha isn't opening/crashing

**Device Information:**

 - iOS Version: iOS 12.5.1
 - Zebra Version: alpha-1b
 - Device: iPhone 5s
 - Jailbreak Type: Chimera

**Crash Log or System Log**

https://pastebin.com/q4g5YEeW

**Comment by CanerKaraca23** [comment]
issue template sucks i will edit myself

**Comment by wstyres** [comment]
Look like this is just iOS 12 exclusive and I forgot to make it so that iOS 13 and up code doesn't run. Things like this are likely littered everywhere so I'll try to fix as many as possible and push another beta.

**Comment by CanerKaraca23** [comment]
> Look like this is just iOS 12 exclusive and I forgot to make it so that iOS 13 and up code doesn't run. Things like this are likely littered everywhere so I'll try to fix as many as possible and push another beta.

Thank you.

**Comment by wstyres** [comment]
The crash you reported here is fixed in ec07376b3cef117437e6524e6ae54f113e6c508f. I've also fixed a few other iOS 12 related crashes so hopefully that will be resolved in the next beta.

**Comment by wstyres** [comment]
Try out alpha1c

**Comment by CanerKaraca23** [comment]
Zebra opened now but crashes after like 5 seconds.

https://pastebin.com/um874F2i

**Comment by wstyres** [comment]
Should be fixed now in beta1d

**Comment by CanerKaraca23** [comment]
Yes, it fixed but there is another crash after first repo refresh and Zebra isn't opening now. I tried removing zebra.db.

https://pastebin.com/yWG4ZmpB

**Comment by wstyres** [comment]
zebra.db doesn't exist anymore and that crash is not longer related to this issue. Please file a new issue with another description with steps to reproduce.
