### ISSUE TITLE
Crash While Opening Zebra Alpha

### ISSUE THREAD

**Issue by CanerKaraca23** [zbrateam/Zebra#1848]
**Describe the bug**
Zebra crashes when i open it.

**To Reproduce**
Just open Zebra.

**Video**
https://media.discordapp.net/attachments/570634688813858820/847244448643678208/video0.mp4

**Device Information:**
 - iOS Version: 12.5.1
 - Zebra Version: alpha1d
 - Device: iPhone 5s
 - Jailbreak Type: Chimera

**Crash Log or System Log**
https://pastebin.com/yWG4ZmpB

**Comment by wstyres** [comment]
Could you zip the contents of `/etc/apt/sources.list.d/` and upload it here?

**Comment by CanerKaraca23** [comment]
> Could you zip the contents of `/etc/apt/sources.list.d/` and upload it here?

https://gofile.io/d/TiItft

**Comment by wstyres** [comment]
Possible fix in c7b797a32b5c7858c36f991fe467a252bb7cac5d. Wait for the next beta to see if it is resolved.

**Comment by CanerKaraca23** [comment]
Still getting crash.
New log: https://pastebin.com/NFUPhGit

**Comment by wstyres** [comment]
Should be fixed as of 370f4349851480f50c5e127a631c6923be5513fb now.

**Comment by vitalik2187836** [comment]
Still crashes for me on alpha 3.

**Comment by rosegayming** [comment]
Also on Alpha 3, getting the same issue
https://hastebin.com/erugatohij.typescript

**Comment by CanerKaraca23** [comment]
My issue fixed on alpha3. Issue can be closed but others having some issues.

**Comment by wstyres** [comment]
Completely reworked the system that was causing the problem in zbrateam/Plains@ f49b3756a6021779b1931cf5c178caafa9bd8644. Let me know if the crash still persists in alpha3b.

**Comment by vitalik2187836** [comment]
Startup crash fixed in 3b for me but now there is infinite loading in installed packages section (if i remember correctly i haven’t had this bug in the first version).

**Comment by wstyres** [comment]
@vitalik2187836 Please open a new issue with a crash log.
