### ISSUE TITLE
HTTP:/ not found

### ISSUE THREAD

**Issue by Capone5812** [zbrateam/Zebra#1849]
**Describe the bug**

every time i try to download zebra on cydia it says HTTP:/ 1.4 or sum number and it says return to cydia and no app is installed
**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: 14.3
 - Zebra Version: idk
 - Device Type: iphone 11 pro max
 - Jailbreak Type: unc0ver 

**Crash Log or System Log**

**Additional context**

**Comment by wstyres** [comment]
Have you tried refreshing your sources? This is a Cydia issue not a Zebra one.
