### ISSUE TITLE
After updating to 1.1.19 Zebra freezes.

### ISSUE THREAD

**Issue by JuniorJailbreaker** [zbrateam/Zebra#1850]
**Describe the bug**
After updating to Zebra version 1.1.19, Zebra freezes upon opening the app. Downgrading doesn't seem to fix the problem and running iCleaner doesn't either. I also removed the package manager via Cydia and reinstalled and issue occurs again. I even restored restored rootfs and the problem still occurs after rejailbreaking and installing Zebra once more. This has deemed Zebra unusable for me.
**To Reproduce**
As the problem hasn't gone away yet and is still occurring, I can't reproduce this issue

**Device Information:** 

 - iOS Version: iOS 14.3
 - Zebra Version: 1.1.19
 - Device Type: iPhone 11
 - Jailbreak Type: Unc0ver

**Crash Log or System Log**
Unfortunately, due to the fact that Zebra doesn't crash I cannot supply a crash log.

**Additional context**

**Comment by eve0415** [comment]
Hello, did you ever remove the database at `/var/mobile/Library/Application Support/xyz.willy.Zebra` ?

**Comment by JuniorJailbreaker** [comment]
Thank you so much, this worked!> Hello, did you ever remove the database at `/var/mobile/Library/Application Support/xyz.willy.Zebra` ?
