### ISSUE TITLE
All repos are empty and don’t updating

### ISSUE THREAD

**Issue by ilyastray777** [zbrateam/Zebra#1857]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by wstyres** [comment]
Please fill out the issue template to provide more information.
