### ISSUE TITLE
Does not finish refreshing sources

### ISSUE THREAD

**Issue by eve0415** [zbrateam/Zebra#1860]
**Describe the bug**
Zebra-Alpha does not finish refreshing sources forever. 

**To Reproduce**
Open Zebra

**Expected behavior**
Finish refreshing sources.

**Device Information:** 
 - iOS Version: 14.3
 - Zebra Version: alpha1a ~ alpha3b
 - Device Type: iPhone
 - Jailbreak Type: Taurine

**Comment by wstyres** [comment]
Could you provide a source list?

**Comment by eve0415** [comment]
[sources.list.zip](https://github.com/zbrateam/Zebra/files/6605290/sources.list.zip)

**Comment by kirb** [comment]
Thanks for reporting! I’m going to merge this into #1965 because I think it’s the same issue.
