### ISSUE TITLE
Don’t loading repos’s packages

### ISSUE THREAD

**Issue by ilyastray777** [zbrateam/Zebra#1862]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by absidue** [comment]
Please fill in the whole template
