### ISSUE TITLE
Packages aren’t loading at all!

### ISSUE THREAD

**Issue by 6adawy** [zbrateam/Zebra#1872]
**Describe the bug**
packages aren’t loading in sources or in installed packages page or changes page. 

**To Reproduce**
Uninstalled zebra v 1.18 through Silio and installed v1.19 through silio. 

**Expected behavior**
A clean install of zebra

**Screenshots**

https://user-images.githubusercontent.com/84728359/123343392-ae4e4680-d51f-11eb-9fbe-acf65f81b2a6.mov

**Device Information:** 

 - iOS Version: <14.3>
 - Zebra Version: <1.19>
 - Device Type: <iPhone>
 - Jailbreak Type:<unc0ver>

**Crash Log or System Log**
App is not crashing

**Additional context**

**Comment by PoomSmart** [comment]
Go to Settings > Reset > Clear Sources Cache
