### ISSUE TITLE
JSON Serialization Error -1

### ISSUE THREAD

**Issue by JellyPeixe** [zbrateam/Zebra#1875]
**Describe the bug**
When trying to login to a store, I'm unable to do so and get an error. Buying a package is broken because of this issue too. This happens to all sources after a period of time but is fixed by doing a login into the account. The same method sometimes doesn't work and I'm presented with the error constantly
**To Reproduce**
1) Try to login to a store (ex: Geometric Store)
2) The web browser page opens rapidly and then closes, showing the error

**Expected behavior**
When tapping to buy a tweak be able to login and when trying to open a store account page, gain access of the account information. 

**Screenshots**
![image](https://user-images.githubusercontent.com/54193604/123480388-ad2d2000-d5d8-11eb-9b20-99ef14eb3787.jpeg)
**Device Information:** 

 - iOS Version: 14.3
 - Zebra Version: 1.1.19
 - Device Type: iPhone
 - Jailbreak Type: unc0ver

**Crash Log or System Log**

**Additional context**

**Comment by absidue** [comment]
In Zebra's settings please tap Clear Web Cache inside of the Reset menu and see if that fixes the issue.

**Comment by JellyPeixe** [comment]
> In Zebra's settings please tap Clear Web Cache inside of the Reset menu and see if that fixes the issue.

It sure did solve the issue! This problem is pretty common to me, I don't know if there's a way to fully fix it rather than repairing it every time it happens. But still, thanks for the quick answer!

**Comment by kirb** [comment]
Might have already been fixed by now, if not then 1.1.27 may do so. Feel free to reopen or make a new issue if you still have issues.
