### ISSUE TITLE
Change / page

### ISSUE THREAD

**Issue by hcm77** [zbrateam/Zebra#1891]
**Describe the bug**
 page changes doesn’t appear,
I can’t see any news from the JB community on the change page.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by absidue** [comment]
Are you only missing the reddit news or is something else missing as well on the changes tab?

**Comment by hcm77** [comment]
Hi boss
I’m missing just the Reddit news.

Thanks for your kind reply

**Comment by absidue** [comment]
Duplicate of #1881
