### ISSUE TITLE
ZEBRA UPDATE

### ISSUE THREAD

**Issue by jayaclysm** [zbrateam/Zebra#1897]
Having issues updated zebra, every time I go to update it gives me an error. I will attach a picture of what I mean. Please help & fix this🙏🏼.
![53905943-9EED-4FFC-B76E-FDB4C2D06C86](https://user-images.githubusercontent.com/87577638/126042780-881f2bc9-4fab-4738-84a9-8c7bf597503b.png)

**Comment by itsjohnnyongithub** [comment]
Same issue I’m stuck on 1.1.15

**Comment by itsjohnnyongithub** [comment]
> Same issue I’m stuck on 1.1.15

Actually, updating with Filza works!
