### ISSUE TITLE
Downgrade Issue...

### ISSUE THREAD

**Issue by HypocritePro** [zbrateam/Zebra#1898]
**Describe the bug**
Having to downgrade from the 1.2 Beta to latest 1.1.21 on iOS 14.3 using Unc0ver 6.2.0

**To Reproduce**
I was on version 1.2 Beta, before it was pulled back and released as 2.0 Alpha. But being on Unc0ver (6.2) and iOS 14.3, I have gutted/removed Zebra, then rolled back and reinstalled the latest 1.1.21, but no matter what I try I can not get it to work as it says there is 96 packages to update now (which are already all up to date), it wishes to fully remove Cydia and a bunch of Core files (like all APT and Core Utilities). Of course I can not install the new 2.0 Alpha as it is Libapt-pkg6.0 dependant (and not Unc0ver compatible from what I understand), so now I am left with a very useless/dangerous version of Zebra that wishes to absolutely destroy the stability of my iOS and jailbreaking potential. Any ideas how I could best resolve this issue and start from scratch (without Zebra trying to 'update' 96 packages, which are all already up to date, and confirmed to be up to date in Cydia)?

**Expected behavior**
Not trying to reinstall packages that are up to date already & gut Cydia from my device with the removal of Core packages. Removing Zebra entirely and utilizing iCleaner Pro does not help and the problem persists with each attempt to reinstall Zebra and use it (with Zebra demanding the packages to be updated & others removed).

**Screenshots**
[Some Screenshots](https://www.dropbox.com/sh/m3jip2wzyg3ihom/AADOqcSaH6VbtiISL7G4IWi0a?dl=0)

**Device Information:** 

 - iOS Version: 14.3
 - Zebra Version: Formerly 1.2 Beta, now 1.1.21
 - Device Type: iPhone 11 Pro Max
 - Jailbreak Type: Unc0ver 6.2.0

**Comment by absidue** [comment]
You have added the Procursus repo which is incompatible with unc0ver, remove the repo and refresh your sources.

**Comment by HypocritePro** [comment]
Awesome! Thank you for the quick fix @absidue
