### ISSUE TITLE
Zebra not fetching new updates for tweak but cydia does

### ISSUE THREAD

**Issue by Salkio** [zbrateam/Zebra#1902]
**Describe the bug**
Zebra not fetching updates for tweaks. Cydia lists the new updates but they don’t show in Zebra. Sources do exist in zebra for the tweak that needs updating. 

**To Reproduce**
Wait for tweak update to appear on cydia then go onto Zebra to search for updates and will notice no updates showing. 

**Expected behavior**
Zebra fetching new updates as cydia does 

**Device Information:**
iPhone X 14.3 Unc0ver v6.0.2
Zebra latest version

**Comment by absidue** [comment]
Have you refreshed your sources and waited for the refresh to complete before searching?

**Comment by Salkio** [comment]
Yea of course. I wait and it does finish refresh.

**Comment by hero3210** [comment]
This happens to me sometimes. To fix it I just go to: Zebra settings > Reset > Clear Sources Cache. 

This seems to fix this issue for me.

**Comment by Salkio** [comment]
Think this may have worked.
