### ISSUE TITLE
When upgrading this tweak, Zebra falsely detects a conflict where there isn’t any

### ISSUE THREAD

**Issue by Proaxel** [zbrateam/Zebra#1924]
**Describe the bug**

I was trying to upgrade Reprovision Reborn, however Zebra refuses because it detects this conflict: 
![97982F57-CEC3-4FCE-B81E-E9D1735EAF68](https://user-images.githubusercontent.com/9545347/137790406-814073d9-96c2-45a7-93a0-bad312d64cd3.png)

I do not have any other versions of Reprovision installed. 

A helpful user from the Jailbreak Discord said to try Cydia instead and sure enough it worked fine. Cydia did not detect any conflict and it installs the upgrade successfully.
 
![76765424-45FD-450E-B2FE-A71B4A6BE49E](https://user-images.githubusercontent.com/9545347/137790653-1289a82f-42d3-4025-820f-a24252274c59.png)

**To Reproduce**

The tweak is Reprovision Reborn from the Packix repo. 

The version I had installed is “0.7.0-release” while the new version is “0.8.2-release”.

**Expected behavior**

Zebra should not detect any conflict and allow the upgrade to be installed.

**Device Information:** 

 - iOS Version: <iOS 14.5>
 - Zebra Version: <1.1.21>
 - Device Type: <iPhone 7 Plus>
 - Jailbreak Type: checkra1n

**Comment by kirb** [comment]
Thanks for reporting! I’m merging this into #1971 to consolidate all the dependency issues we’ve received.
