### ISSUE TITLE
Tired of getting this crash every day :/

### ISSUE THREAD

**Issue by Luki120** [zbrateam/Zebra#1931]
**Describe the bug**

- Sometimes it crashes on launch if the app is closed. Pretty regularly, almost every day.

**To Reproduce**

- I don't really know, it just happens very randomly, but the app needs to be closed first for it to crash.

**Expected behavior**

- Not to crash.

**Screenshots**

-

**Device Information:** 

 - iOS Version: 14.3
 - Zebra Version: 1.1.21
 - Device Type: iPhone
 - Jailbreak Type: unc0ver

**Crash Log or System Log**

https://pastebin.com/Z5iKAkrX it always the same crash

**Additional context**

-

**Comment by iAdam1n** [comment]
Please try with 1.1.25.

**Comment by Luki120** [comment]
Will do once I can be jailbroken with u0 again, I was going to close myself due to that, I had forgotten about it. What's the commit that fixed or attempts to fix this? Thanks for replying anyways.

**Comment by iAdam1n** [comment]
I don’t actually know but not heard that issue in recent versions.
