### ISSUE TITLE
No tweaks  I downloaded some tweaks but they dont show in settings

### ISSUE THREAD

**Issue by ByYourname1994** [zbrateam/Zebra#1935]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <14.4>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <11Pro Max>
 - Jailbreak Type: <Uncover 7.02>

**Crash Log or System Log**

**Additional context**

**Comment by iAdam1n** [comment]
That’s down to the individual packages, nothing to do with Zebra.
