### ISSUE TITLE
No tweaks

### ISSUE THREAD

**Issue by idieldroid** [zbrateam/Zebra#1938]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by iAdam1n** [comment]
Go to Settings>Reset>Clear Sources Cache.
