### ISSUE TITLE
Tweaks are not loading from Sources

### ISSUE THREAD

**Issue by d066z** [zbrateam/Zebra#1943]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

#Crashed logging system.

**Comment by iAdam1n** [comment]
Go to Settings>Reset>Clear Sources Cache.
