### ISSUE TITLE
Zebra won't build on the latest version of Theos

### ISSUE THREAD

**Issue by tale** [zbrateam/Zebra#1946]
Due to the custom build implementation defined in our Makefile, attempting to build will result in an error similar to what's outlined below. The solution for this is to migrate to `xcodeproj.mk` system built into Theos so that we can support both the latest Theos and GNU Make.

Example of an error you may encounter:
```
Zebra isn't code signed but requires entitlements. Falling back to ad hoc signing. (in target 'Zebra' from project 'Zebra')
** ARCHIVE FAILED **

make: *** [Makefile:7: all] Error 65
```

**Comment by kirb** [comment]
Got it to work as of this build: https://github.com/zbrateam/Zebra/runs/4784638751. Had to refactor Theos to not override the derived data path, unfortunately. That just seems to create problems, and there’s scarce info on why this is the case. Fortunately I don’t think it should be too big a deal. Other than that, also had to change all imports of in-project headers from `<angled>` to `"quoted"`.
