### ISSUE TITLE
Scroll not works on the pages of specific repos

### ISSUE THREAD

**Issue by Kyogre** [zbrateam/Zebra#1951]
Describe the bug:
Page won't scroll on the page of tweaks in some repos (counted 4 repos with that problem).
Example repo: https://repo.yfyf.fun/
Example tweak: https://repo.yfyf.fun/index.php?method=view&pid=88

To Reproduce
see the video

Does the issue always occur when trying to reproduce it?
Yes

Expected behavior: Scrolling works.
FYI: In Installer 5 and Sileo it works fine. In Zebra on iPad it also works fine.

Screenshots or videos
[video](https://user-images.githubusercontent.com/2260980/154946518-0de27e71-cdff-44fd-8bee-af17d806e6d8.mp4)

Device:
    Zebra version: 1.1.25
    iOS: 14.2.1
    Jailbreak: Taurine
    Device: iphone 12 mini

**Workaround 1:** open tweak page and start scrolling immediately before the page fully loaded.
**Workaround 2:** open tweak page, wait until it fully loads, scroll many times and fast until you will be pushed under the page, than scroll back to top.

**Comment by Kyogre** [comment]
same for yfyf repo. Example: https://repo.yfyf.fun/index.php?method=view&pid=88

**Comment by iAdam1n** [comment]
We won’t help with piracy issues.

**Comment by Kyogre** [comment]
it is not about piracy, don't you understand? it can happen in some other non-piracy repo, I just don't know what triggers it. If I find non-piracy repo that have that problem, shall we reopen the issue?

**Comment by Kyogre** [comment]
@iAdam1n @absidue , hello guys, can I ask, have you checked https://repo.yfyf.fun/ repo? I don't think that it is piracy repo. It is personal repo of a dev, and still it has mentioned problem.

**Comment by iAdam1n** [comment]
Does it still happen with Zebra 1.1.25?

**Comment by Kyogre** [comment]
yes, checked it about an hour ago

**Comment by iAdam1n** [comment]
I've just reopened this issue. Can you please edit the original submission to remove the piracy repo and list the one you mentioned after that?

**Comment by Kyogre** [comment]
Done. Updated description and video demo.
