### ISSUE TITLE
rwad784@gmail.com

### ISSUE THREAD

**Issue by rwad784** [zbrateam/Zebra#1959]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by elihwyma** [comment]
Very insightful, thank you :)
