### ISSUE TITLE
adding too many repos break the app?

### ISSUE THREAD

**Issue by thinkingaustin** [zbrateam/Zebra#1965]
**Describe the bug**
Whenever I add a large amount of repos to the app, it no longer downloads the content of repos and the links become red. I have to add the repos manually in order to fix this issue.

**To Reproduce**
Add a large amount of sources from a list and they won't download.
**Expected behavior**
I expected the sources to import correctly and the content to show appropriately.

**Screenshots**

 - iOS Version: <14.8>
 - Zebra Version: <1.125 stable>
 - Device Type: <iPhone>
 - Jailbreak Type: <unc0ver>

**Crash Log or System Log**
I don't have one

**Additional context**
It's only happened recently, and before adding repos was fine.

**Comment by thinkingaustin** [comment]
![IMG_3874](https://user-images.githubusercontent.com/60804954/154421940-f6c5be41-1667-4d4c-b90e-da34da43e958.PNG)

**Comment by thinkingaustin** [comment]
![IMG_3862](https://user-images.githubusercontent.com/60804954/154421964-06583ff6-c9eb-458c-af15-24b818a05890.PNG)
![IMG_3874](https://user-images.githubusercontent.com/60804954/154421971-be34458d-fd18-48e3-8b18-729a390654bd.PNG)
here are some screenshots because they didnt go into the bug report for some reason

**Comment by adhip94** [comment]
Yes, even I am facing this issue after I updated to iOS 14.8. On iOS 14.3 it was working fine.

**Comment by voidpls** [comment]
Same issue. 
iPhone 12 / iOS 14.3 / Zebra 1.1.26 / ~60 repos

**Comment by CySxL** [comment]
I have the same issue when I start fresh again. Importing 100+ repos from Cydia to Zebra.

Zebra can't handle this large amount of repos so it just adds repos partially like about 25 repos at a time. My solution is just keep adding them so the queued/waiting-for-added repos will be decreased and decreased.

iOS Version: <14.8>
Zebra Version: <1.128 stable>
Device Type: <iPhone 11 Pro Max>
Jailbreak Type: <unc0ver 8.0.2>

**Comment by iAdam1n** [comment]
Does this still happen with 1.1.30?

**Comment by CySxL** [comment]
> Does this still happen with 1.1.30?

I'll try again when I have a chance.
