### ISSUE TITLE
Shop doesn't appear on Home in iOS 10.2/iPhone 6

### ISSUE THREAD

**Issue by FuyutoH** [zbrateam/Zebra#1970]
**Describe the bug**
**Shop** doesn't appear on Home

**To Reproduce**

Install Zebra on IOS 10.2. (my case happened on iPhone 6)
**Expected behavior**

**Shop** should appear under Community Sources
**Screenshots**

![IMG_0001](https://user-images.githubusercontent.com/100841391/156549092-bbf25670-f8aa-4be5-ac54-327eea125e0f.jpg)

**Device Information:** 

 - iOS Version: 10.2 <INSERT-HERE>
 - Zebra Version: 1.1.26 <INSERT-HERE>
 - Device Type: iPhone6 (screenshot shows 7.2 but it's actually iPhone 6.) <INSERT-HERE>
 - Jailbreak Type: yalu102 through 3u Tools <INSERT-HERE>

**Crash Log or System Log**

I don't see any error message during installation as below
![IMG_0003](https://user-images.githubusercontent.com/100841391/156560257-ed8d62d7-c922-4ddb-b4c2-7dd9114fdaba.jpg)

**Additional context**

I would like to use **Carbridge Legacy (old)** from Havoc via Zebra.
The reason I need Carbridge Legacy on rather old iOS 10.2 is that it's DRM free OS. 
To install it, I need to login to Havoc and if anyone could help, it would be really appreciated.

**Comment by kirb** [comment]
Can you try the settings button &rarr; Reset &rarr; Clear Sources Cache? Also, do you see a banner asking you to log in at the top of Sources &rarr; Havoc?

**Comment by FuyutoH** [comment]
Thank you very much for your support.
I tried to reset "Clear Source Cache" as below log, but Store doesn't show up unfortunately.
![ダウンロード (18)](https://user-images.githubusercontent.com/100841391/156689845-8950b109-a6d9-4126-bcbc-c07a489c0fc4.png)
Also I cannot see any banner at the top of Sources → Havoc
![ダウンロード](https://user-images.githubusercontent.com/100841391/156689972-60602a13-eaed-4e13-8ced-15dcd963e056.png)

**Comment by awh1tedud3** [comment]
Having this same issue,

Device Information:

iOS Version: 10.2
Zebra Version: 1.1.26
Device Type: iPhone6s 
Jailbreak Type: Meridian through 3u Tools

**Comment by kirb** [comment]
Payment providers currently aren’t supported on iOS 9-10, this is partly because they rely on a Safari authentication feature added in iOS 11 (the “Zebra wants to use chariz.com to sign in” prompt), and partly because it was assumed no packages applicable to iOS 9-10 would be on a repo that uses payment providers. The story has changed due to Havoc though, so I revisited this. I was able to make them work on 9-10 using a bit of a trick (in 36a27c0). This will come in the next Zebra release (1.1.27).

**Comment by awh1tedud3** [comment]
> 

Kirb you are the best for figuring this out. I look forward to the update

**Comment by FuyutoH** [comment]
Wow! Thank you for your finding out the root cause and upcoming update😃😃😃 Great support!!

**Comment by kirb** [comment]
1.1.27 has been released now, so closing. Thanks to everyone who chimed in on this thread!
