### ISSUE TITLE
Zebra doesn't show screenshots and changelog for some tweaks' depictions

### ISSUE THREAD

**Issue by Kyogre** [zbrateam/Zebra#1972]
**To Reproduce**
Add repo https://johnzaro.github.io/cydia , then open [Orion](https://johnzaro.github.io/cydia/depiction/web/com.johnzaro.orionappstoreapps.html) page in Zebra (via Search or via Sources tab). You will see that the page opens in native Zebra layout and there are no screenshots, no tweak icon, no changelog, which are present on the [web page](https://johnzaro.github.io/cydia/depiction/web/com.johnzaro.orionappstoreapps.html) if you open it in browser.

**Expected behavior**
Ideally: Zebra opens [Orion](https://johnzaro.github.io/cydia/depiction/web/com.johnzaro.orionappstoreapps.html) page like it opens [Perfect photos](https://johnzaro.github.io/cydia/depiction/web/com.johnzaro.perfectphotos13.html) page. It is strange that the behavior for these two pages is different despite they are hosted in the same repo.
Workaround: Zebra transmits whole web page to "Package information" section.

**Screenshots**
-

**Device Information:**
 - iOS Version: 14.2.1
 - Zebra Version: 1.1.26

**Comment by kirb** [comment]
Thanks for reporting! I took a look at this package, it seems to be a mistake on the repo maintainer’s part. The package is missing a `Depiction:` field, so Zebra doesn’t know that a depiction page exists for that package. I see the same issue in Cydia as well, so going to consider this not a Zebra issue.
