### ISSUE TITLE
Zebra 1.1.27 crashes

### ISSUE THREAD

**Issue by mak135** [zbrateam/Zebra#1983]
**Describe the bug**
 zebra crash when launch. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <12.4>
 - Zebra Version: <1.1.27>
 - Device Type: < iphone x >
 - Jailbreak Type: < Chimera >

**Crash Log or System Log**

[text.txt](https://github.com/zbrateam/Zebra/files/8753838/text.txt)

**Additional context**

**Comment by kirb** [comment]
Arg, sorry. Fixed in 1.1.28 which should show up on the repo in the next few minutes.
