### ISSUE TITLE
No space left on device?

### ISSUE THREAD

**Issue by adhip94** [zbrateam/Zebra#1987]
**Describe the bug**
When I refresh my sources, I get an error for every source saying "The operation couldn't be completed. No space left on device"

**To Reproduce**
Refresh source list

**Expected behavior**
Sources should refresh properly and since there is a lot of space on this device the error is irrelevant

**Screenshots**
![image](https://user-images.githubusercontent.com/20703483/169951020-d0242d37-1803-45a9-90a9-4b202441668e.png)

**Device Information:**

 - iOS Version: iOS 14.8
 - Zebra Version: 1.1.28
 - Device Type: iPhone 8+
 - Jailbreak Type: checkra1n

**Crash Log or System Log**
No crash

**Additional context**

**Comment by iAdam1n** [comment]
This suggests that your device has no space left on the rootfs partition. To solve this you need to remove some packages. This is not a Zebra issue.

**Comment by adhip94** [comment]
But i do have a lot of space available on my device
![image](https://user-images.githubusercontent.com/20703483/170032152-348ed285-840f-4a81-9d51-796993c901b3.jpeg)
