### ISSUE TITLE
i'm

### ISSUE THREAD

**Issue by faisl887** [zbrateam/Zebra#1989]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information:** 

 - iOS Version: <INSERT-HERE>
 - Zebra Version: <INSERT-HERE>
 - Device Type: <INSERT-HERE>
 - Jailbreak Type: <INSERT-HERE>

**Crash Log or System Log**

**Additional context**

**Comment by olivertzeng** [comment]
wtf

**Comment by faisl887** [comment]
****
