### ISSUE TITLE
Queue view controller doesn't display queued packages right away

### ISSUE THREAD

**Issue by L1ghtmann** [zbrateam/Zebra#1992]
**Describe the bug**
If the queue view controller is not opened between queuing an initial package and subsequent packages, only the first package queued will be present in the view controller's view. 

**To Reproduce**
Add a package to the queue and don't open the queue view controller. Then add another package to the queue and open the queue view controller. Notice how the second of the two packages queued isn't displayed. This will be the case for all packages added after the initial one (assuming you don't open the queue before adding them).

**Expected behavior**
The queue view controller's view to update as packages are added to the queue without having to open it once beforehand. 

**Screenshots**
[Bug]
https://user-images.githubusercontent.com/67040127/173160333-7de01db1-77c9-4577-ace2-39369ca8bb92.mov

[Opening queue view controller after initial package is added exhibits normal behavior]
https://user-images.githubusercontent.com/67040127/173160366-67f03fdc-140a-471d-9b07-93dcf9481a3d.mov

**Device Information:** 
 - iOS Version: 14.3
 - Zebra Version: 1.1.28 (latest stable)
 - Device Type: iPhone
 - Jailbreak Type: Taurine

**Crash Log or System Log**
N/A

**Additional context**
Despite the view controller's view not updating properly, the queue tab bar does update correctly (see first screen recording). 

The bug does not occur if the queue is opened after adding the initial package (see second screen recording above). 

This issue was not present in [1.1.26](https://github.com/zbrateam/Zebra/commit/c9e9754672f98550fe96f5418a4b5d17ad65bccd) and appears to have begun in 1.1.27* and remains present in the latest stable release 1.1.28. I took a look at the commit history between 1.1.26 and 1.1.27* and nothing stood out. Would've dug a bit more, but I don't have a macOS install to be able to test things, unfortunately.

**Comment by elihwyma** [comment]
Fixed in: https://github.com/zbrateam/Zebra/commit/403b4ed9830f4da0b4ee09117c070f1182fb5b33
