### ISSUE TITLE
getdelta.co was labeled as unsafe repo

### ISSUE THREAD

**Issue by olivertzeng** [zbrateam/Zebra#1993]

**Comment by kirb** [comment]
Indeed, there’s something wrong with getdelta.co, the certificate expired and wasn’t renewed. Zebra is correctly reporting the error, it’s not safe for it to proceed with a certificate issue. You should let the repo maintainer know about it. 

![12B6DEE7-02A2-4305-96E3-2BB963D28F43](https://user-images.githubusercontent.com/773309/174431673-1aff5b0a-aeb8-462d-a5c9-769a31710d42.png)
