### ISSUE TITLE
Can’t search for package name using Chinese characters

### ISSUE THREAD

**Issue by CySxL** [zbrateam/Zebra#1996]
**Describe the bug**
Searching a Chinese letter via Zebra can't find any results. But packages with the letter are displayed if user search directly by developer's name.

**To Reproduce**
1. Launch Zebra and go to search tab.

2. Make sure Zebra has Bigboss repo added.

3. Search for "改" via name. Which is a Chinese letter meaning "change".

4. Zebra can't find any result for "改".

5. Change the category of search to developer's name.

6. Search for "小哥哥", which means "little brother".

7. Zebra finds the results of developer's name 小哥哥, which are "改个应用..."、"改个步数..."、"定个位..."

8. So you see the bug. The package name contains "改", but it cannot be searched by Zebra while user searches by the category of package name 

**Expected behavior**
Display the accurate search result. 

**Screenshots**

![image](https://user-images.githubusercontent.com/15531137/183902385-be8dd113-9bf2-48a5-b1b0-9563e9f09c7a.png)
![image](https://user-images.githubusercontent.com/15531137/183902355-506dd83c-a986-47ce-b336-9d6866111333.png)

**Device Information:** 

 - iOS Version: <14.8>
 - Zebra Version: <1.1.28>
 - Device Type: <iPhone 11 Pro Max>
 - Jailbreak Type: <unc0ver 8.0.2>

**Crash Log or System Log**
No crash log needed.

**Additional context**
Not sure if this helps but you can check this also : https://user-images.githubusercontent.com/15531137/183903613-e2775c25-63eb-4c77-8f07-9b35ab608efd.MOV

**Comment by kirb** [comment]
When you can, could you check if search works for you in 1.1.29? I changed a lot about how Zebra queries packages and other info from its database, and I have a feeling that should solve the problem you were having. Also note that Zebra requires at least 2 characters to perform a search. I’m not too sure why that’s the case but I’ll see if we can remove that limitation.

**Comment by CySxL** [comment]
> When you can, could you check if search works for you in 1.1.29? I changed a lot about how Zebra queries packages and other info from its database, and I have a feeling that should solve the problem you were having. Also note that Zebra requires at least 2 characters to perform a search. I’m not too sure why that’s the case but I’ll see if we can remove that limitation.

Yeah it is fixed now !! Thanks a lot !!![image](https://user-images.githubusercontent.com/15531137/207259274-eba5e6bf-f480-4f96-8a25-20e721bca279.jpeg)


Btw shall I pull a new issue/request for the at least 2 characters thing ?

**Comment by iAdam1n** [comment]
Don't worry, this will be addressed shortly with Zebra 1.1.30.
