### ISSUE TITLE
Zebra on Electra still recommends "Electra's iOS Utilities" despite the repo being dead and Electra now using Chimera bootstrap

### ISSUE THREAD

**Issue by TheMasterOfMike** [zbrateam/Zebra#1997]
**Describe the bug**
In the Community Sources tab, the repository listed in the "Utilities" category seems to be the old Electra repo (https://electrarepo64.coolstar.org), however given how Electra is setup today combined with the fact that the aforementioned repo is seemingly dead, shouldn't it logically be suggesting the Chimera Repo (https://repo.chimera.sh)

**To Reproduce**
Jailbreak a device with Electra, install Zebra, then go to the Community Sources tab

**Expected behavior**
It should be suggesting the Chimera repo

**Screenshots**
This seems like a straightforward issue, but if you guys want the screenshots I can post them.

**Device Information:** 
 - iOS Version: iOS 11.2.1
 - Zebra Version: Zebra 1.1.28
 - Device Type: iPhone 6
 - Jailbreak Type: Electra 2.0

**Crash Log or System Log**
Not relevant

**Additional context**
I noticed this after initially jailbreaking my iPhone 6 on iOS 11.2.1 that I received yesterday with Electra - went and also installed Zebra and noticed that it was suggesting the Electra repo and also would not transfer the Chimera repo from Sileo

**Comment by kirb** [comment]
Thanks, that’s definitely outdated and needs updating.

**Comment by TheMasterOfMike** [comment]
Resolved in https://github.com/zbrateam/Zebra/commit/22acf4dde143d9bdd262b24ae15f0dea20c8e004
