### ISSUE TITLE
I can't sign in repo havoc

### ISSUE THREAD

**Issue by dhd111** [zbrateam/Zebra#1999]
**Describe the bug**

I can't sign in repo havoc because it's not  appear in the store box and I can't change language 
**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/74234804/187928123-1d42c6db-c9d5-4c08-8fa9-76da2c121aa1.jpeg)
**Device Information:** 

 - iOS Version: <14.4.1>
 - Zebra Version: <1.1.28>
 - Device Type: <iPhone 11>
 - Jailbreak Type: <Unc0ver>

**Crash Log or System Log**

**Additional context**

**Comment by iAdam1n** [comment]
How did you add Havoc repo? Make sure you added it by going Community Sources>Transfer and then transfer from your original package manager.

**Comment by dhd111** [comment]
> How did you add Havoc repo? Make sure you added it by going Community Sources>Transfer and then transfer from your original package manager. 

I did 
I did everything

**Comment by iAdam1n** [comment]
Can you remove the repo and then try again with the method I said but also send a video so I can confirm that it's right? It worked fine for me last night.

**Comment by dhd111** [comment]
> Can you remove the repo and then try again with the method I said but also send a video so I can confirm that it's right? It worked fine for me last night.

https://user-images.githubusercontent.com/74234804/187964564-f316ad47-d122-4ce9-a79d-07827c330d55.MOV

**Comment by iAdam1n** [comment]
You don't happen to have CyDown installed do you?

**Comment by dhd111** [comment]
> You don't happen to have CyDown installed do you?

I deleted it and it's work again thank you

**Comment by dhd111** [comment]
> > You don't happen to have CyDown installed do you?
> 
> I deleted it and it's work again thank you 

But why is nit appear in the store box when I install Cydown ?

**Comment by absidue** [comment]
Because CyDown is a piracy tweak and part of the way it works is by breaking the entire store system in Zebra.

**Comment by dhd111** [comment]
> Because CyDown is a piracy tweak and part of the way it works is by breaking the entire store system in Zebra.

Thanks for information 
Now i delete this ? (Close issues)
