### ISSUE TITLE
dpkg error after 1.1.29 update

### ISSUE THREAD

**Issue by CySxL** [zbrateam/Zebra#2010]
**Describe the bug**

dpkg error after 1.1.29 update
**To Reproduce**

update Zebra to 1.1.29 and install/remove any package
**Expected behavior**

don't have the error
**Screenshots**

![image](https://user-images.githubusercontent.com/15531137/207261418-f92e6ba3-d7c9-491f-9017-da61af573a9f.png)

![image](https://user-images.githubusercontent.com/15531137/207261551-1b35737e-e789-4868-b3df-64f454150a6f.png)

**Device Information:** 

 - iOS Version: <14.8>
 - Zebra Version: <1.1.29>
 - Device Type: <iPhone 11 Pro Max>
 - Jailbreak Type: <unc0ver 8.0.2>

**Crash Log or System Log**

 no crash logs
**Additional context**

I don't know why I can't fix it myself on my end ![image](https://user-images.githubusercontent.com/15531137/207261956-ac68a2f1-11f9-4fdb-8923-19d0ddc052fa.jpeg)

why command not found ?

**Comment by CySxL** [comment]
Fixed it minutes later by logging as su then run `dpkg --configure -a`

But I'm pretty sure it's caused by the update (1.1.29) of Zebra as I haven't upgrade/install anything new before updating Zebra.

**Comment by CySxL** [comment]
Test again. It seems like it's the 1.1.29 Zebra doesn't like Cr4shed very much. Other packages don't have this issue as far as I know.

**Comment by CySxL** [comment]
Another one : Glow by Limneos
![image](https://user-images.githubusercontent.com/15531137/207369940-9e8a4092-6c52-4795-ae14-c3a513031f96.png)

**Comment by kirb** [comment]
Thanks, found the issue and fixed it in c9cba93, will be in 1.1.30 shortly.
