### ISSUE TITLE
Light mode UI glitches

### ISSUE THREAD

**Issue by CySxL** [zbrateam/Zebra#2011]
**Describe the bug**

Light/Dark mode elements are mixed chaotically in Home, Search, Tweak pages.

**To Reproduce**

1. Set Zebra appearance follows system's appearance
2. Kill Zebra
3. Set device in dark mode
4. Launch Zebra
5. Change system appearance to light mode via Control Center or any method
6. Check Home, Search, Tweak depictions page. Some UI appearances are broken.

**Expected behavior**

Gracefully follow the system UI appearance changing, especially from Dark mode to Light mode.

**Screenshots**

![image](https://user-images.githubusercontent.com/15531137/207264443-3e7e651e-f032-4aae-a5e9-e506103eb668.png)
![image](https://user-images.githubusercontent.com/15531137/207264456-de0edf59-e9b8-44c8-82f4-7d52ee322978.png)
![image](https://user-images.githubusercontent.com/15531137/207267936-b3d9a4d1-9c56-4b0f-bb99-2c405f86e398.png)

**Device Information:** 

 - iOS Version: <14.8>
 - Zebra Version: <1.1.29>
 - Device Type: <iPhone 11 Pro Max>
 - Jailbreak Type: <unc0ver 8.0.2>

**Crash Log or System Log**

No crash logs needed
**Additional context**

**Comment by iAdam1n** [comment]
1.1.30 will be releasing shortly so can you test again on that please? I can't reproduce this issue with it.

**Comment by CySxL** [comment]
> 1.1.30 will be releasing shortly so can you test again on that please? I can't reproduce this issue with it.

My big sorry !!! I found it's caused by Deluminator. Disabling it fixes the issue. Thanks a lot for all your help and I'm sorry 🥲

**Comment by kirb** [comment]
That‘s fine, no worries! We really appreciate you filing bugs anyway. They’ve been an immense help 🙂
