### ISSUE TITLE
Remove limit of at least 2 characters of searching.

### ISSUE THREAD

**Issue by CySxL** [zbrateam/Zebra#2012]
**Describe the bug**

you need to insert at least 2 characters (Chinese) in order to search.
**To Reproduce**

Search with only one Chinese character
**Expected behavior**

Able to search with one character
**Screenshots**

![image](https://user-images.githubusercontent.com/15531137/207368042-d393a400-11be-470a-b52e-fa521126a084.png)
![image](https://user-images.githubusercontent.com/15531137/207368752-34c7efba-19a5-4881-a17c-f88d72bf7d01.png)
**Device Information:** 

 - iOS Version: <14.8>
 - Zebra Version: <1.1.29>
 - Device Type: <iPhone>
 - Jailbreak Type: <unc0ver>

**Crash Log or System Log**

**Additional context**

**Comment by iAdam1n** [comment]
We’re aware - https://github.com/zbrateam/Zebra/issues/1996#issuecomment-1347828636

**Comment by CySxL** [comment]
> We’re aware - https://github.com/zbrateam/Zebra/issues/1996#issuecomment-1347828636

o7

**Comment by kirb** [comment]
Thanks heaps for bringing this to my attention. Zebra 1.1.30 will allow 1 character to be typed to search in languages that benefit from it, e.g. Chinese, Japanese, and Korean. As a compromise for performance reasons, this won’t be supported for Latin characters (the English alphabet and digits).

![Simulator Screen Shot - iPhone 14 Pro Max - 2022-12-17 at 16 01 42](https://user-images.githubusercontent.com/773309/208227020-0d7b1294-42d7-4404-9f3e-16e83c58ccf1.png)

**Comment by CySxL** [comment]
> Thanks heaps for bringing this to my attention. Zebra 1.1.30 will allow 1 character to be typed to search in languages that benefit from it, e.g. Chinese, Japanese, and Korean. As a compromise for performance reasons, this won’t be supported for Latin characters (the English alphabet and digits).
> 
> 
> 
> ![Simulator Screen Shot - iPhone 14 Pro Max - 2022-12-17 at 16 01 42](https://user-images.githubusercontent.com/773309/208227020-0d7b1294-42d7-4404-9f3e-16e83c58ccf1.png)

Thanks a lot !! Love all your guys hard work to make Zebra better then ever !
