### ISSUE TITLE
Queue Page not showing all tweaks (again)

### ISSUE THREAD

**Issue by 21mtd** [zbrateam/Zebra#2014]
**Describe the bug**

I checked old issues and see it happened before, queue page only show 1 tweak until it's minimized then opened again.

**To Reproduce**

1. Queue 2 or more random tweaks.
2. Open queue page and only 1 tweak is showed.
3. Minimize queue page and reopen to show all queued tweaks.

**Expected behavior**

All tweaks showed normally on the first time open queue page.

**Device Information:** 

 - iOS Version: 14.6
 - Zebra Version: 1.1.29
 - Device Type: iPhone XS
 - Jailbreak Type: unc0ver

**Additional context**

Version 1.1.26 doesn't have this problem, any version above 1.1.26 is bugged.

**Comment by kirb** [comment]
Thanks for reporting! Since it’s a duplicate I’m going to close this in favor of the original #1992 thread.
