### ISSUE TITLE
Pages not loading

### ISSUE THREAD

**Issue by moritz-t-w** [zbrateam/Zebra#2020]
iOS 16.3 iPhone X Palera1n

The package pages don't show descriptions for me

**Comment by iAdam1n** [comment]
Can you send a screenshot of the difference between Zebra and another package manager as you are referring to? As far as I'm aware, it does show the full description.

**Comment by moritz-t-w** [comment]
Clearing sources and web cache didn't work

**Comment by moritz-t-w** [comment]
![IMG_C3725202C1FC-1](https://user-images.githubusercontent.com/90388353/218337968-8f84bac9-d1cb-405e-a736-a77d8c8b087a.jpeg)

**Comment by moritz-t-w** [comment]
> Can you send a screenshot of the difference between Zebra and another package manager as you are referring to? As far as I'm aware, it does show the full description.
![IMG_1FB18E9EA2F3-1](https://user-images.githubusercontent.com/90388353/218338069-a6cff3fb-4cca-48e3-b4b2-22ab9701206b.jpeg)

**Comment by moritz-t-w** [comment]
![image](https://user-images.githubusercontent.com/90388353/218342945-c3b9cd74-a4bf-4ded-9835-132525219cb6.png)
I restored rootfs and jailbroke rootfull, still nothing

**Comment by moritz-t-w** [comment]
I am now rootful and it still doesn't display descriptions.

**Comment by iAdam1n** [comment]
Can confirm this is broken for me too. Will look into it.
