### ISSUE TITLE
Literally can’t install anything.

### ISSUE THREAD

**Issue by harisshaukat96** [zbrateam/Zebra#2022]
**Describe the bug**
whenever I try to install or update something, no errors happen in the console, but when I press done, it still says (install) or is still in the available updates list

**To Reproduce**
Try to install or update something

**Expected behavior**
For the thing to install or update

**Screenshots**

**Device Information:** 

 - iOS Version: <15.7.1>
 - Zebra Version: <1.1.29>
 - Device Type: <IPhone 7 plus>
 - Jailbreak Type: Palera1n

**Crash Log or System Log**

**Additional context**

**Comment by iAdam1n** [comment]
We're aware of this issue and are looking into it.

**Comment by harisshaukat96** [comment]
Ok

**Comment by cyntrifical** [comment]
same issue occurring on Fugu15 Max, iOS 15.3, iPhone XS. 

No issues installing with Sileo Nightly, but does exactly as OP stated and generates no crash logs

**Comment by iAdam1n** [comment]
This should now be fixed with 1.1.31.

**Comment by cemerson** [comment]
Apologies if this isn't appropriate but just FYI I was having this same issue (things would download and import but never install) but I already had Zebra 1.1.31 installed. Anyhow I *reinstalled* Zebra 1.1.31 (using Zebra) and after the respring I finally could install things again with Zebra. Yay!
