### ISSUE TITLE
[Localize]

### ISSUE THREAD

**Issue by ferdous-mahmud** [zbrateam/Zebra#2026]
I want to add language support for [Bangla](http://en.wikipedia.org/wiki/Bengali_language)
Discord username: ferdous#3068

**Credit info**
Name: Ferdous Mahmud Akash
[Twitter](https://twitter.com/ferdous_19) [Website](https://ferdous.tech)

**Comment by iAdam1n** [comment]
Feel free to submit a pull request with them added.

**Comment by ferdous-mahmud** [comment]
### No option available for Bangla on Crowdin. 
## Please add an option for Bangla.
![Crowdin](https://user-images.githubusercontent.com/62091371/222048425-c9bcb28d-31be-41ab-b211-6fcdbe949444.png)

**Comment by iAdam1n** [comment]
This is because Apple doing natively support it so we don’t either.
