### ISSUE TITLE
Unable to install tweaks

### ISSUE THREAD

**Issue by Vitamoon** [zbrateam/Zebra#2038]
**Describe the bug**
Tweaks cannot be installed. This only started happening to me after I imported the NoW4U2Kid repo and attempted to install a tweak from it. I later uninstalled Dodo and cannot even install it now even though I had it installed fine previously.

**To Reproduce**
idk

**Expected behavior**
Tweaks should install fine

**Screenshots**
![86643](https://user-images.githubusercontent.com/91440012/236266492-40e1aac1-c172-401a-8b10-9c62be3f8748.jpg)

**Device Information:**
 - iOS Version: 15.4.1
 - Zebra Version: 1.1.31
 - Device Type: iPhone 12 (13,2)
 - Jailbreak Type: Dopamine 1.0.2

**Crash Log or System Log**
see screenshot

**Additional context**
n/a

**Comment by iAdam1n** [comment]
If you remove that repo does it work?

**Comment by iAdam1n** [comment]
As this repo is illegal, we won't help with issues with it.
