### ISSUE TITLE
Zebra not working on Dopamine jailbreak

### ISSUE THREAD

**Issue by Gen3ric** [zbrateam/Zebra#2039]
**Describe the bug**
When I open Zebra and it tries to refresh the sources I get the error shown in the first image, when adding a repository I get the error shown in the second image and when manually installing a .deb file I get the image shown in the third image.

**To Reproduce**
Jailbreak using Dopamine and open Zebra.

**Expected behavior**
No errors occur during any of these actions.

**Screenshots**
![img](https://user-images.githubusercontent.com/66680981/236437054-78f3cc06-e52d-445a-a63d-f82ac8b7d52d.jpeg)
![img-2](https://user-images.githubusercontent.com/66680981/236437235-0ba92669-ffc2-4f0c-bf87-954a56e271fc.jpeg)
![img-3](https://user-images.githubusercontent.com/66680981/236437299-e2350526-97c3-44a0-8639-79ad4c6ec491.jpeg)

**Device Information:** 

 - iOS Version: 15.1
 - Zebra Version: 1.1.31
 - Device Type: iPhone XR
 - Jailbreak Type: Dopamine

**Comment by kirb** [comment]
Did you use a tool or script that does something like import stuff into Zebra, or have you manually done anything with `/var/mobile/Library/Application Support/xyz.willy.Zebra` in Filza or SSH? If so, something has messed up the permissions. From a terminal you can try:

```bash
chown -R mobile:staff /var/mobile/Library/Application\ Support/xyz.willy.Zebra
```

Or browse to that path in Filza, tap the ℹ️ on the folder, and make sure it has owner `mobile`, group `staff`. You’ll need to apply that recursively, can’t recall if Filza has something to do that for you.

**Comment by Gen3ric** [comment]
I did not do any of those things, and even removed the jailbreak entirely a couple of times and this didn't fix it. Running the command however seems to have fixed the issue, thanks!
