### ISSUE TITLE
Sync repo sources with Cydia

### ISSUE THREAD

**Issue by palxex** [zbrateam/Zebra#506]
**Is your feature request related to a problem? Please describe.**
Zebra now able to import sources from cydia, But I need export to it too - or to say, 2 way sync, better automatically, instead of manually check.

**Describe the solution you'd like**
Cydia is a must, zebra is better for daily use, I'm tired of sync them.

**Describe alternatives you've considered**
A option for whether enable the 2-way sync, not check default, for who don't like it.

**Additional context**
Cydia is a must, zebra is better for daily use, I'm tired of sync them; That makes I always try Cydia first , in order to prevent I forgot re-import sources I added in Zebra.

**Comment by PoomSmart** [comment]
I guess you can use Okapi tweak to export sources from Zebra then use Flame to batch-import sources in Cydia.

**Comment by wstyres** [comment]
Going to close this in favor of #1369
