### ISSUE TITLE
Ability to see package dependencies before adding to queue

### ISSUE THREAD

**Issue by gkeep** [zbrateam/Zebra#625]
**Describe the solution you'd like**
A tab alongside other information about the package (see image below).

**Describe alternatives you've considered**
While user can see package dependencies in queue, it would be more easy and straightforward to see them in a tab.

![deps_concept](https://user-images.githubusercontent.com/20600053/69652669-15292680-1083-11ea-930a-cf6af08c2e07.png)

**Comment by wstyres** [comment]
This could be included in the new depiction, we're still coming up with the design so we'll see what we can do.

**Comment by blanxd** [comment]
+1
this could be useful/informative indeed. What about simply listing them in a cell there, even without a separate view, and "Conflicts" as well. I love the way all the technical bits are listed in a compact manner above the depictions. (to think of it actually such Deps/Conflicts display would be borrowing from some other product, I won't encourage nor discourage the idea :) but it would be useful nevertheless)

**Comment by DrConflict** [comment]
Yeah, or having the essential repos included by default so all dependancy files can be downloaded automatically would be a good idea. Many new comers don't like the fact Zebra always whines about dependancies and doesn't install the tweak until the correct repos have been added.

**Comment by wstyres** [comment]
Implemented in a273feb049f8985ac77630c6abb57e4b1984043d.
