### ISSUE TITLE
Ability to view package depictions in browser

### ISSUE THREAD

**Issue by worldlydev** [zbrateam/Zebra#635]
**Is your feature request related to a problem? Please describe.**

Issues affecting a packages' depiction page such as #557 and #622 wouldn't be as big of an issue if there was an easy way to view the package' depiction in an in-app browser (WebViewController).

**Describe the solution you'd like**

Something along the lines of what is offered in Installer or Sileo:
![88E03309-1E6B-48EB-8B68-3201FB2CFBFD](https://user-images.githubusercontent.com/51668635/69883053-b6f28280-12d2-11ea-957c-7965f22c83c3.jpeg)
![1C66D398-21BF-4544-B954-128FF5DCCBC8](https://user-images.githubusercontent.com/51668635/69883102-f28d4c80-12d2-11ea-8817-4d91f47f1f92.jpeg)
(Sileo's UI seems to be the most practical in this case and also looks better. Has support for reader view, a refresh button, a button to open the page in Safari, and a share button.)

**Comment by Greigh** [comment]
https://apt.alfhaily.me/
Still unable to view depictions on this repo.

**Comment by worldlydev** [comment]
Possibly include it at the bottom of the package depiction page like in the app store?

![FC56497E-25CD-457D-A2A6-24956A5E6937](https://user-images.githubusercontent.com/51668635/83778879-8f1e1600-a68b-11ea-978a-7225b9270457.jpeg)
![BD1D8EAD-F690-4410-8803-D7DB75FFD13C](https://user-images.githubusercontent.com/51668635/83778894-934a3380-a68b-11ea-8a2e-0c12d4500204.jpeg)

**Comment by wstyres** [comment]
Implemented in 6fcccc146f8cd66c2573cb285d69cdd23b4263df.
