### ISSUE TITLE
[BUG] Can get around the install/removal of dependencies

### ISSUE THREAD

**Issue by eve0415** [zbrateam/Zebra#701]
**Describe the bug**
As the title says, you can get around the install/removal of dependencies doing below.
I don’t think anyone will do this though because DPKG or APT will remove it automatically when you don’t have any other package that depends or doesn’t install at all.

Like anemone, snowboard, iThemer is almost the same package so that tweak manager makes these dependencies, while anemone, snowboard, iThemer would conflict each other. Anemone cannot be used with substrate but Zebra will install them. When or after Zebra try/had install anemone, or you don’t want to use anemone but use it with snowboard or iThemer, you can go around by following below.

**To Reproduce**
[Removing]
1. remove dependency package in order to queue the main package to be removed
2. queue re-install for the main package
3. go to queue tab and remove the main package from the queue 

[Installing]
This is an example.
1. Make sure you don’t have anemone, snowboard or iTheme installed.
2. Try to Install AppleRings & iPhoneX Respring Themes
3. Open queue to find anemone are trying to be installed automatically.
4. Try to install snowboard and iThemer which it will conflict when installing
(Zebra doesn’t say it conflicts with each other when in queue)
5. Try to install anemone manually. It is marked as install automatically but doing it manually will make you remove from the queue.
6. Finally open queue and remove anemone from queue

**Expected behavior**
[Suggestion]
This is an example for theme
Make user to choose anemone, snowboard or iThemer. For example, when anemone got queued but want to use snowboard instead, you can queue snowboard manually and remove anemone from queue automatically.
[Bug]
As I mentioned on the last issue about iCleaner queue up as remove automatically when removing APT 0.7 Transitional andAPT 1.4 Transitional installed. You can make “APT 0.7 Transitional” removed only by doing these steps.
1. Make sure you have iCleaner Pro, APT 0.7 Transitional & APT 1.4 Transitional.
2. Try to remove APT 0.7 Transitional
3. Go to queue to see iCleaner Pro being removed as well
4. Try to re-install iCleaner Pro
5. Remove iCleaner Pro from queue

**Screenshots**

I’ll take videos of the screen and post it on discord if you need

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 12.4
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: beta up to rc1 rc3
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: unc0ver

**Additional context**
Its difficult to tell issues using English. If you can’t understand what I meant please tell me.

**Comment by wstyres** [comment]
Resolved in 2.0 alpha.
