### ISSUE TITLE
The popup for noticing conflicts  show us different package.

### ISSUE THREAD

**Issue by eve0415** [zbrateam/Zebra#734]
**Describe the bug**
When you have conflicts packages inside the queue or already installed, the conflict message tells us different package.

**To Reproduce**
Queue two packages or more that conflicts each other.

**Expected behavior**
Show the right one.

**Screenshots**
![E19D1C85-BC0F-48DC-A96C-C2CDA71979EF](https://user-images.githubusercontent.com/40632436/71328476-23237780-255b-11ea-91f2-4351c7220d58.png)
![8ADF682E-70A5-49CA-8BBA-1B865AB2FBB2](https://user-images.githubusercontent.com/40632436/71328478-23237780-255b-11ea-9439-ff54131aaba1.png)
![70126B9E-CA50-498E-BB34-BD46FBB11A49](https://user-images.githubusercontent.com/40632436/71328479-23bc0e00-255b-11ea-9ac2-db1c01ba06e2.png)

**Device Information (please complete the following information):**
 - iOS Version: 12.4
 - Zebra Version: RC3
 - Device Type: unc0ver

**Additional context**
I would like to have package name instead of package id.

**Comment by wstyres** [comment]
This is intended, those are virtual packages provided by iThemer. This is how Cydia will display the issues too but in the future it will show the correct package name.

**Comment by wstyres** [comment]
Resolved in 2.0 alpha
