### ISSUE TITLE
Update the conflict in queue when changed

### ISSUE THREAD

**Issue by eve0415** [zbrateam/Zebra#753]
**Describe the bug**
When there are conflicting packages in queue, Zebra will tell us what package conflicts. When the user remove the first package from the queue, still, the second package says it conflicts. And the third package also.

**To Reproduce**
ex.
1. queue snowboard
2. queue ithemer
(3. queue anemone)
4. remove snowboard from queue
ithemer and/or anemone are both red and will say it conflicts

**Expected behavior**
Update the information of conflicts when removing package from queue

**Screenshots**
https://cdn.discordapp.com/attachments/572784833714192395/660707315766526024/RPReplay.mp4

**Device Information (please complete the following information):**
 - iOS Version : 12.4
 - Zebra Version : rc4
 - Device Type: iPhone
 - Jailbreak Type : unc0ver

**Additional context**
Also, "Install" button in depiction are still gray out when the package is not in queue anymore

**Comment by eve0415** [comment]
Another similar issue but not exactly the same.

1. Put anemone to queue as remove.
2. Put Snowboard to queue as install.

Zebra says Snowboard conflicts because "Anemone conflicts with Snowboard"

Check the conflict package if the queue will resolve the issue.

**Comment by wstyres** [comment]
Resolved in 2.0 alpha.
