### ISSUE TITLE
Zebra ignore dependencies for removing when the package that depends are already in queue 

### ISSUE THREAD

**Issue by eve0415** [zbrateam/Zebra#754]
**Describe the bug**
When trying to remove package that has dependencies, and any of the dependency are already in queue for reinstalling or whatever, zebra ignore all the dependencies for the removal of package

**To Reproduce**
ex.
1. queue filzaplus for reinstall
2. queue filza for remove
Now, you can see filza is going to be remove while filzaplus will show us it's gonna reinstall

**Expected behavior**
change the reinstall to be remove or show pop up that this operation will conflict or so. 

**Screenshots**
https://cdn.discordapp.com/attachments/572784833714192395/660715596605947934/RPReplay.mp4

**Device Information (please complete the following information):**
 - iOS Version : 12.4
 - Zebra Version : rc4
 - Device Type: iPhone
 - Jailbreak Type : unc0ver

**Comment by wstyres** [comment]
Resolved in 2.0 alpha.
