### ISSUE TITLE
Show available extensions for applications

### ISSUE THREAD

**Issue by worldlydev** [zbrateam/Zebra#852]
Screenshot:
![8069E37A-9744-405B-A832-850EEC18D3A1](https://user-images.githubusercontent.com/51668635/74367887-ec3b4680-4dd2-11ea-8b04-6aaaff60475b.jpeg)
Screenshots from Discord conversation:
![F8F1828A-3F47-46DA-A72B-9FECA49501B1](https://user-images.githubusercontent.com/51668635/74367914-f78e7200-4dd2-11ea-9bd4-19b630df1500.jpeg)
![62177C4E-70B9-4E6B-B2B7-FBC4EF1734CB](https://user-images.githubusercontent.com/51668635/74367922-fa896280-4dd2-11ea-90a5-525e5ccca939.png)
![EB44673E-FCC8-4824-96CF-CEB26EC60C3D](https://user-images.githubusercontent.com/51668635/74367926-fc532600-4dd2-11ea-8984-9ca6fa5f77e0.png)
![E6B4DD71-222D-44C3-BA11-BF195E4ADF36](https://user-images.githubusercontent.com/51668635/74367931-fd845300-4dd2-11ea-90f7-182d6c3cc0ee.png)
![6C7B700F-1CDE-482A-B4C7-99B52BBE90CB](https://user-images.githubusercontent.com/51668635/74367935-fe1ce980-4dd2-11ea-9b30-28de1edcef9f.png)
![ACCA2B8C-9661-492C-8ECA-C102F1EBA7CF](https://user-images.githubusercontent.com/51668635/74367938-ff4e1680-4dd2-11ea-900e-c54f00dacb34.png)
![85D3EDB1-522E-45AD-847E-36C38C858A59](https://user-images.githubusercontent.com/51668635/74367944-0117da00-4dd3-11ea-8842-c9e990eeb503.png)
![386C5F62-ACB8-4925-9F98-2CEAFDA45D35](https://user-images.githubusercontent.com/51668635/74367947-02490700-4dd3-11ea-9d2b-314ce20ee7a5.png)

**Comment by wstyres** [comment]
Because of the work that this would require on the server end and probably lack of adoption on the developer/package manager end we're not going to implement this at the current point in time. If it turns out in the future someone else has implemented a server-side package listing (possibly Parcility?) that would fit the needs of this then we will reconsider.

**Comment by worldlydev** [comment]
> Because of the work that this would require on the server end and probably lack of adoption on the developer/package manager end we're not going to implement this at the current point in time. If it turns out in the future someone else has implemented a server-side package listing (possibly Parcility?) that would fit the needs of this then we will reconsider.

Gotcha
