### ISSUE TITLE
Changes tab keeps showing old packages as new

### ISSUE THREAD

**Issue by Aransh** [zbrateam/Zebra#996]
**Describe the bug**
Well, every few days I'd refresh sources in Zebra, and suddenly the changes tab would show a REALLY long list of new packages, which is exciting until you take a look at them and see they are BigBoss packages which haven't been updated for 6 years (though not exclusive to BigBoss).
It's especially annoying as it prevents me from seeing the actual new packages.
My guess would be it's related to failed repo refreshes (which leaves the source appearing as empty), and then on the second refresh (which succeeds), Zebra shows all of the repo packages as "new", although they were there a few minutes ago, before the failed refresh.

**To Reproduce**
Refresh repos
Fail
Refresh repos again
(Could be that it's not the cause, just my guess)

**Expected behavior**
Zebra remembers packages it used to have, and doesn't put them in the changes tab.
OR, alternatively, Zebra doesn't clear a repo if it fails to refresh, leaving everything there until the next successful refresh.

**Screenshots**
![F89ACAFA-54AA-4671-B1B8-2EA0F9ED9813](https://user-images.githubusercontent.com/11724502/77763414-19267e80-704c-11ea-93fe-4aa4e6c2b3a1.png)
Screenshot shows the changes tab showing a lot of new packages from Skitty's repo, though non of them were updated recently, and I've had the repo for several months.

**Device Information (please complete the following information):**
 - iOS Version: 13.3
 - Zebra Version: 1.1~beta3-1
 - Device Type: iPhone 
 - Jailbreak Type: Uncover

**Comment by wstyres** [comment]
This is quite difficult to reproduce based on what you've mentioned so it might take awhile to reproduce this at all and then fix it.

**Comment by Aransh** [comment]
> This is quite difficult to reproduce based on what you've mentioned so it might take awhile to reproduce this at all and then fix it.

Well as I said I'm not sure if what I wrote is necessarily what causes this but it does happen to ne at least twice a week... Let me know if there's any way I could help

**Comment by PoomSmart** [comment]
Potential fix in a8d53b4fdaf3e2578001671d188b4089bf597161, let's see.

**Comment by Aransh** [comment]
> Potential fix in a8d53b4fdaf3e2578001671d188b4089bf597161, let's see.

@PoomSmart just got it again in BigBoss with 1.1.4

**Comment by PoomSmart** [comment]
And now 1.1.9?

**Comment by Aransh** [comment]
> And now 1.1.9?

@PoomSmart yes, just got it with BigBoss again

**Comment by wstyres** [comment]
Does this still occur in the latest beta (1.2~beta7b) of Zebra? We've restructured the Changes system to count recent packages a little better.

**Comment by wstyres** [comment]
Going to close as inactive for now.
